
/*
* Generated by MuukTest
* Test Case ID: TC85892
* Description: Confirm progress icon dynamically updates and reflects the current state of the instance
* Generated: 2026-09-11T04:36:05.811Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavgupzppbviuhmp,  dashboardStagingNavgd5olyf6yh8r8,  developerMozillaOrgxzdbdgwwbnu4,  w3schoolsComjzqsyei6j6jl,  dashboardStagingNavgsmjvggb6529n,  dashboardStagingNavgwqyd8p0t1aul,  dashboardStagingNavgn5033kkru0q,  dashboardStagingNavgjil8wrljoks,  dashboardStagingNavgxzu2dnc9uqgo,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarApp2fd37295.log';
const muukReport = new MuukReport('dashboardStagingNavgarApp2fd37295');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarApp2fd37295',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarApp2fd37295', muukReport);
  MK.setVideoTracker(200);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavgupzppbviuhmp();
	const pageDetails3 = new dashboardStagingNavgd5olyf6yh8r8();
	const pageDetails4 = new developerMozillaOrgxzdbdgwwbnu4();
	const pageDetails5 = new w3schoolsComjzqsyei6j6jl();
	const pageDetails6 = new dashboardStagingNavgsmjvggb6529n();
	const pageDetails7 = new dashboardStagingNavgwqyd8p0t1aul();
	const pageDetails8 = new dashboardStagingNavgn5033kkru0q();
	const pageDetails9 = new dashboardStagingNavgjil8wrljoks();
	const pageDetails10 = new dashboardStagingNavgxzu2dnc9uqgo();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm>span.text-xs.whitespace-break-spaces.w-fit.text-center.text-primary-10.font-bold\",\"index\":0},{\"selector\":\"li>span\",\"index\":0},{\"selector\":\"SPAN\",\"index\":3},{\"selector\":\"//SPAN[normalize-space() = \\"Applications\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Applications","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Applications","type":"undef"}');
  await MK.onClick(pageDetails2.spanaEUx60TWG2Field, 14, 'before', `Applications`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"div.MuiBox-root.css-3eqgl8>h6.MuiTypography-root.MuiTypography-subtitle1.css-bwj3c4\",\"index\":0},{\"selector\":\"div>h6\",\"index\":0},{\"selector\":\"H6\",\"index\":0},{\"selector\":\"//h6[normalize-space() = \\"Applications\\"]\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Applications","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails2.h65NhnAKumpXField, 15, 'after', `Applications`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"div.MuiStack-root.css-j7qwjs>p.MuiTypography-root.MuiTypography-body1.line-clamp-2.css-13ghd1g\",\"index\":0},{\"selector\":\"div>p\",\"index\":3},{\"selector\":\"P\",\"index\":3},{\"selector\":\"//P[normalize-space() = \\"Flow Template App Module\\"]\",\"index\":0}]', 3, 'p', '', 'click', '{"value":"Flow Template App Module","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Template App Module","type":"undef"}');
  await MK.onClick(pageDetails2.poXIv6PfRvField, 16, 'before', `Flow Template App Module`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"div.MuiBox-root.css-h300a0>h6.MuiTypography-root.MuiTypography-subtitle1.css-bwj3c4\",\"index\":0},{\"selector\":\"div>h6\",\"index\":0},{\"selector\":\"H6\",\"index\":0},{\"selector\":\"//h6[normalize-space() = \\"Flow Template App Module\\"]\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Template App Module","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails3.h6J8H1VJU8oKField, 17, 'after', `Flow Template - Header`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"div.MuiBox-root.css-1eiru37>button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.css-bj6f2k\",\"index\":0},{\"selector\":\"div>button\",\"index\":6},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":6},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Launch\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Launch","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Launch","type":"button"}');
  await MK.onClick(pageDetails9.button58s152hoNField, 18, 'before', `Launch`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 19, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.Mui-focused.MuiInputBase-formControl.css-329mgo>input.MuiInputBase-input.MuiOutlinedInput-input.css-1pk1fka\",\"index\":0},{\"selector\":\"div>input\",\"index\":2},{\"selector\":\"INPUT[name=\'Flow Instance Name\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':rfb:\'][@name=\'Flow Instance Name\'][@type=\'text\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":rfb:","name":"Flow Instance Name","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails9.inputjxsA8SG6bField, 19, 'after', `Test`, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"div.MuiBox-root.css-gmrfgn>button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeSmall.MuiButton-containedSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeSmall.MuiButton-containedSizeSmall.MuiButton-colorPrimary.css-7lu7cm\",\"index\":0},{\"selector\":\"div>button\",\"index\":32},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":30},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Execute\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Execute","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Execute","type":"button"}');
  await MK.onClick(pageDetails9.buttonl1tQ8ZS0JlField, 20, 'before', `Execute`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 21, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":1},{\"selector\":\"div>button\",\"index\":10},{\"selector\":\"BUTTON[type=\'button\'][id=\':rcr:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"0Filters\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"0Filters","searchType":"text","text":"undef"}', '{"id":":rcr:","name":"undef","text":"0Filters","type":"button"}');
  await MK.onClick(pageDetails9.buttona9CD0DFqXaField, 21, 'before', `Filters`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 22, page.url(), '[{\"selector\":\"div.MuiDataGrid-panelFooter.css-1csgm2j>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.css-1fbl5f9\",\"index\":0},{\"selector\":\"div>button\",\"index\":33},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":31},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Add filter\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Add filter","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Add filter","type":"button"}');
  await MK.onClick(pageDetails9.button2jf6NytnV2Field, 22, 'before', `Add Filter`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 23, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiDataGrid-filterFormColumnInput.MuiSelect-root.css-wtk1p4>div.MuiSelect-select.MuiSelect-outlined.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputSizeSmall.css-f3b8cd\",\"index\":1},{\"selector\":\"div>div\",\"index\":246},{\"selector\":\"DIV[role=\'combobox\'][id=\':rga:\']\",\"index\":0},{\"selector\":\"//DIV[@role=\'combobox\'][normalize-space() = \\"Chat\\"]\",\"index\":0}]', 3, 'div', '', 'click', '{"value":"Chat","searchType":"text","text":"undef"}', '{"id":":rga:","name":"undef","text":"Chat","type":"undef"}');
  await MK.onClick(pageDetails9.div0mFmp8H55Field, 23, 'before', `Chat`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 24, page.url(), '[{\"selector\":\"ul.MuiList-root.MuiList-padding.MuiMenu-list.css-ubifyk>li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters.css-7ea6lj\",\"index\":2},{\"selector\":\"ul>li\",\"index\":10},{\"selector\":\"LI[role=\'option\']\",\"index\":1},{\"selector\":\"//LI[@role=\'option\']\",\"index\":1}]', 2, 'li', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Status","type":"undef"}');
  await MK.onClick(pageDetails9.liejUng3F4LkField, 24, 'before', `0`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 25, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiSelect-root.css-fa7bsl>div.MuiSelect-select.MuiSelect-outlined.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputSizeSmall.css-f3b8cd\",\"index\":0},{\"selector\":\"div>div\",\"index\":253},{\"selector\":\"DIV[role=\'combobox\'][id=\':rgq:\']\",\"index\":0},{\"selector\":\"//DIV[@role=\'combobox\'][normalize-space() = \\"​\\"]\",\"index\":0}]', 3, 'div', '', 'click', '{"value":"​","searchType":"text","text":"undef"}', '{"id":":rgq:","name":"undef","text":"​","type":"undef"}');
  await MK.onClick(pageDetails9.divKLT81eTPYgField, 25, 'before', `​`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 26, page.url(), '[{\"selector\":\"ul.MuiList-root.MuiList-padding.MuiMenu-list.css-ubifyk>li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters.css-7ea6lj\",\"index\":2},{\"selector\":\"ul>li\",\"index\":10},{\"selector\":\"LI[role=\'option\']\",\"index\":1},{\"selector\":\"//LI[@role=\'option\']\",\"index\":1}]', 2, 'li', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Running","type":"undef"}');
  await MK.onClick(pageDetails9.likqS71eHr3Field, 26, 'before', `0`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 27, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":4},{\"selector\":\"div>button\",\"index\":11},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":11},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Expand tasks\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Expand tasks","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Expand tasks","type":"button"}');
  await MK.onClick(pageDetails9.button5eHgn5uNjPField, 27, 'before', `Expand Tasks`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 28, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails8.spaneNTewwivzXField, 28, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 29, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.h-fit.css-1uqcqne>input.PrivateSwitchBase-input.css-j8yymo\",\"index\":0},{\"selector\":\"span>input\",\"index\":1},{\"selector\":\"INPUT[type=\'checkbox\']\",\"index\":1},{\"selector\":\"//INPUT[@type=\'checkbox\']\",\"index\":1}]', 2, 'input', 'checkbox', 'click', '{"value":"on","searchType":"value","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"checkbox"}');
  await MK.onClick(pageDetails8.inputozI04Vs7k9Field, 29, 'before', `on`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 30, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails8.divbqIK0T5kvField, 30, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarApp2fd37295_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
