
/*
* Generated by MuukTest
* Test Case ID: TC85888
* Description: Apps Table action bar - Filters
* Generated: 2026-09-11T04:36:04.679Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavgupzppbviuhmp,  dashboardStagingNavgd5olyf6yh8r8,  developerMozillaOrgxzdbdgwwbnu4,  w3schoolsComjzqsyei6j6jl,  dashboardStagingNavgsmjvggb6529n,  dashboardStagingNavgwqyd8p0t1aul,  dashboardStagingNavgn5033kkru0q,  dashboardStagingNavgjil8wrljoks,  dashboardStagingNavgxzu2dnc9uqgo,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarApp2fd33d2d.log';
const muukReport = new MuukReport('dashboardStagingNavgarApp2fd33d2d');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarApp2fd33d2d',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarApp2fd33d2d', muukReport);
  MK.setVideoTracker(200);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavgupzppbviuhmp();
	const pageDetails3 = new dashboardStagingNavgd5olyf6yh8r8();
	const pageDetails4 = new developerMozillaOrgxzdbdgwwbnu4();
	const pageDetails5 = new w3schoolsComjzqsyei6j6jl();
	const pageDetails6 = new dashboardStagingNavgsmjvggb6529n();
	const pageDetails7 = new dashboardStagingNavgwqyd8p0t1aul();
	const pageDetails8 = new dashboardStagingNavgn5033kkru0q();
	const pageDetails9 = new dashboardStagingNavgjil8wrljoks();
	const pageDetails10 = new dashboardStagingNavgxzu2dnc9uqgo();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm>span.text-xs.whitespace-break-spaces.w-fit.text-center.text-primary-10.font-bold\",\"index\":0},{\"selector\":\"li>span\",\"index\":0},{\"selector\":\"SPAN\",\"index\":3},{\"selector\":\"//SPAN[normalize-space() = \\"Applications\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Applications","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Applications","type":"undef"}');
  await MK.onClick(pageDetails2.spanaEUx60TWG2Field, 14, 'before', `Applications`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"div.MuiBox-root.css-3eqgl8>h6.MuiTypography-root.MuiTypography-subtitle1.css-bwj3c4\",\"index\":0},{\"selector\":\"div>h6\",\"index\":0},{\"selector\":\"H6\",\"index\":0},{\"selector\":\"//h6[normalize-space() = \\"Applications\\"]\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Applications","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails2.h65NhnAKumpXField, 15, 'after', `Applications`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"div.MuiStack-root.css-j7qwjs>p.MuiTypography-root.MuiTypography-body1.line-clamp-2.css-13ghd1g\",\"index\":0},{\"selector\":\"div>p\",\"index\":3},{\"selector\":\"P\",\"index\":3},{\"selector\":\"//P[normalize-space() = \\"Flow Template App Module\\"]\",\"index\":0}]', 3, 'p', '', 'click', '{"value":"Flow Template App Module","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Template App Module","type":"undef"}');
  await MK.onClick(pageDetails2.poXIv6PfRvField, 16, 'before', `Flow Template App Module`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"div.MuiBox-root.css-h300a0>h6.MuiTypography-root.MuiTypography-subtitle1.css-bwj3c4\",\"index\":0},{\"selector\":\"div>h6\",\"index\":0},{\"selector\":\"H6\",\"index\":0},{\"selector\":\"//h6[normalize-space() = \\"Flow Template App Module\\"]\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Template App Module","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails3.h6J8H1VJU8oKField, 17, 'after', `Flow Template - Header`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":1},{\"selector\":\"div>button\",\"index\":8},{\"selector\":\"BUTTON[type=\'button\'][id=\':re:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"Filters\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"0Filters","searchType":"text","text":"undef"}', '{"id":":re:","name":"undef","text":"0Filters","type":"button"}');
  await MK.onClick(pageDetails3.buttonlOIlKC6NPField, 18, 'before', `Filters`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 19, page.url(), '[{\"selector\":\"div.MuiDataGrid-panelFooter.css-1csgm2j>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.css-1fbl5f9\",\"index\":0},{\"selector\":\"div>button\",\"index\":28},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":26},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Add filter\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Add filter","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Add filter","type":"button"}');
  await MK.onClick(pageDetails3.buttonYvSoK6hL1dField, 19, 'before', `+ Add Filter`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 20, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails5.aLzhRl5Txq0Field, 20, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 21, page.url(), '[{\"selector\":\"div.MuiDataGrid-panelFooter.css-1csgm2j>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.css-1fbl5f9\",\"index\":0},{\"selector\":\"div>button\",\"index\":28},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":26},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Add filter\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Add filter","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Add filter","type":"button"}');
  await MK.onClick(pageDetails3.buttonYvSoK6hL1dField, 21, 'before', `+ Add Filter`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 22, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails5.almHpe3f1DnField, 22, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 23, page.url(), '[{\"selector\":\"div.MuiDataGrid-panelFooter.css-1csgm2j>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.css-1fbl5f9\",\"index\":0},{\"selector\":\"div>button\",\"index\":28},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":26},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Add filter\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Add filter","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Add filter","type":"button"}');
  await MK.onClick(pageDetails3.buttonYvSoK6hL1dField, 23, 'before', `+ Add Filter`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 24, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails5.adWcxwxtwQlField, 24, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 25, page.url(), '[{\"selector\":\"div.MuiDataGrid-panelFooter.css-1csgm2j>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.css-1fbl5f9\",\"index\":1},{\"selector\":\"div>button\",\"index\":32},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":31},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Remove all\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Remove all","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Remove all","type":"button"}');
  await MK.onClick(pageDetails3.button32CKAxC9mnField, 25, 'before', `Remove All`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 26, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails5.a2AhxlumAaField, 26, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 27, page.url(), '[{\"selector\":\"div.MuiDataGrid-panelFooter.css-1csgm2j>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.css-1fbl5f9\",\"index\":0},{\"selector\":\"div>button\",\"index\":28},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":26},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Add filter\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Add filter","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Add filter","type":"button"}');
  await MK.onClick(pageDetails3.buttonYvSoK6hL1dField, 27, 'before', `+ Add Filter`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 28, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails5.aLzhRl5Txq0Field, 28, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 29, page.url(), '[{\"selector\":\"div.MuiDataGrid-panelFooter.css-1csgm2j>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.css-1fbl5f9\",\"index\":0},{\"selector\":\"div>button\",\"index\":28},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":26},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Add filter\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Add filter","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Add filter","type":"button"}');
  await MK.onClick(pageDetails3.buttonYvSoK6hL1dField, 29, 'before', `+ Add Filter`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 30, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails5.almHpe3f1DnField, 30, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 31, page.url(), '[{\"selector\":\"div.MuiDataGrid-panelFooter.css-1csgm2j>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.css-1fbl5f9\",\"index\":0},{\"selector\":\"div>button\",\"index\":28},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":26},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Add filter\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Add filter","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Add filter","type":"button"}');
  await MK.onClick(pageDetails3.buttonYvSoK6hL1dField, 31, 'before', `+ Add Filter`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 32, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails5.adWcxwxtwQlField, 32, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 33, page.url(), '[{\"selector\":\"mdn-dropdown>button.menu__tab-button\",\"index\":0},{\"selector\":\"mdn-dropdown>button\",\"index\":0},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":1},{\"selector\":\"//button[@title=\\"Delete\\"]\",\"index\":3}]', 3, 'button', 'button', 'click', '{"value":"HTML","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"HTML","type":"button"}');
  await MK.onClick(pageDetails4.buttonxQs9WuDjoField, 33, 'before', `Delete Filter`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 34, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails5.almHpe3f1DnField, 34, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 35, page.url(), '[{\"selector\":\"mdn-dropdown>button.menu__tab-button\",\"index\":1},{\"selector\":\"mdn-dropdown>button\",\"index\":1},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":2},{\"selector\":\"//button[@title=\\"Delete\\"]\",\"index\":2}]', 3, 'button', 'button', 'click', '{"value":"CSS","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"CSS","type":"button"}');
  await MK.onClick(pageDetails4.button7dFLJJtQ1Field, 35, 'before', `Delete Filter`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 36, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails5.aLzhRl5Txq0Field, 36, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 37, page.url(), '[{\"selector\":\"mdn-dropdown>button.menu__tab-button\",\"index\":2},{\"selector\":\"mdn-dropdown>button\",\"index\":2},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":3},{\"selector\":\"//button[@title=\\"Delete\\"]\",\"index\":1}]', 3, 'button', 'button', 'click', '{"value":"JavaScriptJS","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"JavaScriptJS","type":"button"}');
  await MK.onClick(pageDetails4.buttonp5sBB1iKKzField, 37, 'before', `Delete Filter`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 38, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails4.buttonDjHv06c2LyField, 38, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 39, page.url(), '[{\"selector\":\"mdn-dropdown>button.menu__tab-button\",\"index\":3},{\"selector\":\"mdn-dropdown>button\",\"index\":3},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":4},{\"selector\":\"//button[@title=\\"Delete\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Web APIs","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Web APIs","type":"button"}');
  await MK.onClick(pageDetails4.buttonaWCZZecE6Field, 39, 'before', `Delete Filter`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 40, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails5.a2AhxlumAaField, 40, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarApp2fd33d2d_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
