
/*
* Generated by MuukTest
* Test Case ID: TC85887
* Description: Apps Table action bar - Columns
* Generated: 2026-09-11T04:35:58.212Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavgupzppbviuhmp,  dashboardStagingNavgd5olyf6yh8r8,  dashboardStagingNavgjil8wrljoks,  dashboardStagingNavgn0j46qwxu3b,  dashboardStagingNavgnn85gpzwo4n,  dashboardStagingNavgg5sfwh45uvgi,  dashboardStagingNavgd727tjpj297,  dashboardStagingNavgjze79tmszlz,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarApp2fd33cb5.log';
const muukReport = new MuukReport('dashboardStagingNavgarApp2fd33cb5');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarApp2fd33cb5',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarApp2fd33cb5', muukReport);
  MK.setVideoTracker(200);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavgupzppbviuhmp();
	const pageDetails3 = new dashboardStagingNavgd5olyf6yh8r8();
	const pageDetails4 = new dashboardStagingNavgjil8wrljoks();
	const pageDetails5 = new dashboardStagingNavgn0j46qwxu3b();
	const pageDetails6 = new dashboardStagingNavgnn85gpzwo4n();
	const pageDetails7 = new dashboardStagingNavgg5sfwh45uvgi();
	const pageDetails8 = new dashboardStagingNavgd727tjpj297();
	const pageDetails9 = new dashboardStagingNavgjze79tmszlz();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm>span.text-xs.whitespace-break-spaces.w-fit.text-center.text-primary-10.font-bold\",\"index\":0},{\"selector\":\"li>span\",\"index\":0},{\"selector\":\"SPAN\",\"index\":3},{\"selector\":\"//SPAN[normalize-space() = \\"Applications\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Applications","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Applications","type":"undef"}');
  await MK.onClick(pageDetails2.spanaEUx60TWG2Field, 14, 'before', `Applications`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"div.MuiBox-root.css-3eqgl8>h6.MuiTypography-root.MuiTypography-subtitle1.css-bwj3c4\",\"index\":0},{\"selector\":\"div>h6\",\"index\":0},{\"selector\":\"H6\",\"index\":0},{\"selector\":\"//h6[normalize-space() = \\"Applications\\"]\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Applications","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails2.h65NhnAKumpXField, 15, 'after', `Applications`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"div.MuiStack-root.css-j7qwjs>p.MuiTypography-root.MuiTypography-body1.line-clamp-2.css-13ghd1g\",\"index\":0},{\"selector\":\"div>p\",\"index\":3},{\"selector\":\"P\",\"index\":3},{\"selector\":\"//P[normalize-space() = \\"Flow Template App Module\\"]\",\"index\":0}]', 3, 'p', '', 'click', '{"value":"Flow Template App Module","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Template App Module","type":"undef"}');
  await MK.onClick(pageDetails2.poXIv6PfRvField, 16, 'before', `Flow Template App Module`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"div.MuiBox-root.css-h300a0>h6.MuiTypography-root.MuiTypography-subtitle1.css-bwj3c4\",\"index\":0},{\"selector\":\"div>h6\",\"index\":0},{\"selector\":\"H6\",\"index\":0},{\"selector\":\"//h6[normalize-space() = \\"Flow Template App Module\\"]\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Template App Module","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails3.h6J8H1VJU8oKField, 17, 'after', `Flow Template - Header`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r1i7:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"olumns\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r1i7:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails3.buttonqgSWeDhpp7Field, 18, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 19, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.buttonPgF0GXHzjaField, 19, 'after', 'disabled'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-k9qqt8>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputTypeSearch.MuiInputBase-inputSizeSmall.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-1cludd7\",\"index\":0},{\"selector\":\"div>input\",\"index\":2},{\"selector\":\"INPUT[placeholder=\'Search\'][type=\'search\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r1l2:\'][@placeholder=\'Search\'][@type=\'search\']\",\"index\":0}]', 2, 'input', 'search', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r1l2:","name":"undef","text":"undef","type":"search"}');
  
  
  await MK.onAssignment(pageDetails3.input92InbPtKd3Field, 20, 'after', `Detail panel toggle`, 'search', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 21, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.labelPjsa95c9vJField, 21, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 22, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.css-fa3int>input.PrivateSwitchBase-input.css-j8yymo\",\"index\":0},{\"selector\":\"span>input\",\"index\":1},{\"selector\":\"INPUT[name=\'__detail_panel_toggle__\'][type=\'checkbox\']\",\"index\":0},{\"selector\":\"//button[@aria-label=\\"Clear\\"]\",\"index\":0}]', 3, 'input', 'checkbox', 'click', '{"value":"Clear","searchType":"value","text":"undef"}', '{"id":"undef","name":"__detail_panel_toggle__","text":"undef","type":"checkbox"}');
  await MK.onClick(pageDetails3.inputobT1ZGI4RField, 22, 'before', `Clear`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 23, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-k9qqt8>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputTypeSearch.MuiInputBase-inputSizeSmall.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-1cludd7\",\"index\":0},{\"selector\":\"div>input\",\"index\":2},{\"selector\":\"INPUT[placeholder=\'Search\'][type=\'search\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r1l2:\'][@placeholder=\'Search\'][@type=\'search\']\",\"index\":0}]', 2, 'input', 'search', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r1l2:","name":"undef","text":"undef","type":"search"}');
  
  
  await MK.onAssignment(pageDetails3.input92InbPtKd3Field, 23, 'after', `Flow Instance Name`, 'search', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 24, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.label0eTl5VC1pGField, 24, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 25, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.css-fa3int>input.PrivateSwitchBase-input.css-j8yymo\",\"index\":0},{\"selector\":\"span>input\",\"index\":1},{\"selector\":\"INPUT[name=\'__detail_panel_toggle__\'][type=\'checkbox\']\",\"index\":0},{\"selector\":\"//button[@aria-label=\\"Clear\\"]\",\"index\":0}]', 3, 'input', 'checkbox', 'click', '{"value":"Clear","searchType":"value","text":"undef"}', '{"id":"undef","name":"__detail_panel_toggle__","text":"undef","type":"checkbox"}');
  await MK.onClick(pageDetails3.inputobT1ZGI4RField, 25, 'before', `Clear`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 26, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-k9qqt8>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputTypeSearch.MuiInputBase-inputSizeSmall.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-1cludd7\",\"index\":0},{\"selector\":\"div>input\",\"index\":2},{\"selector\":\"INPUT[placeholder=\'Search\'][type=\'search\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r1l2:\'][@placeholder=\'Search\'][@type=\'search\']\",\"index\":0}]', 2, 'input', 'search', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r1l2:","name":"undef","text":"undef","type":"search"}');
  
  
  await MK.onAssignment(pageDetails3.input92InbPtKd3Field, 26, 'after', `Progress`, 'search', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 27, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.label0ZtkaHzZRField, 27, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 28, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.css-fa3int>input.PrivateSwitchBase-input.css-j8yymo\",\"index\":0},{\"selector\":\"span>input\",\"index\":1},{\"selector\":\"INPUT[name=\'__detail_panel_toggle__\'][type=\'checkbox\']\",\"index\":0},{\"selector\":\"//button[@aria-label=\\"Clear\\"]\",\"index\":0}]', 3, 'input', 'checkbox', 'click', '{"value":"Clear","searchType":"value","text":"undef"}', '{"id":"undef","name":"__detail_panel_toggle__","text":"undef","type":"checkbox"}');
  await MK.onClick(pageDetails3.inputobT1ZGI4RField, 28, 'before', `Clear`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 29, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-k9qqt8>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputTypeSearch.MuiInputBase-inputSizeSmall.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-1cludd7\",\"index\":0},{\"selector\":\"div>input\",\"index\":2},{\"selector\":\"INPUT[placeholder=\'Search\'][type=\'search\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r1l2:\'][@placeholder=\'Search\'][@type=\'search\']\",\"index\":0}]', 2, 'input', 'search', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r1l2:","name":"undef","text":"undef","type":"search"}');
  
  
  await MK.onAssignment(pageDetails3.input92InbPtKd3Field, 29, 'after', `Chat`, 'search', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 30, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.label2bCNZ6Fm3zField, 30, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 31, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.css-fa3int>input.PrivateSwitchBase-input.css-j8yymo\",\"index\":0},{\"selector\":\"span>input\",\"index\":1},{\"selector\":\"INPUT[name=\'__detail_panel_toggle__\'][type=\'checkbox\']\",\"index\":0},{\"selector\":\"//button[@aria-label=\\"Clear\\"]\",\"index\":0}]', 3, 'input', 'checkbox', 'click', '{"value":"Clear","searchType":"value","text":"undef"}', '{"id":"undef","name":"__detail_panel_toggle__","text":"undef","type":"checkbox"}');
  await MK.onClick(pageDetails3.inputobT1ZGI4RField, 31, 'before', `Clear`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 32, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-k9qqt8>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputTypeSearch.MuiInputBase-inputSizeSmall.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-1cludd7\",\"index\":0},{\"selector\":\"div>input\",\"index\":2},{\"selector\":\"INPUT[placeholder=\'Search\'][type=\'search\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r1l2:\'][@placeholder=\'Search\'][@type=\'search\']\",\"index\":0}]', 2, 'input', 'search', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r1l2:","name":"undef","text":"undef","type":"search"}');
  
  
  await MK.onAssignment(pageDetails3.input92InbPtKd3Field, 32, 'after', `Status`, 'search', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 33, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.label65cALNTzaXField, 33, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 34, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.css-fa3int>input.PrivateSwitchBase-input.css-j8yymo\",\"index\":0},{\"selector\":\"span>input\",\"index\":1},{\"selector\":\"INPUT[name=\'__detail_panel_toggle__\'][type=\'checkbox\']\",\"index\":0},{\"selector\":\"//button[@aria-label=\\"Clear\\"]\",\"index\":0}]', 3, 'input', 'checkbox', 'click', '{"value":"Clear","searchType":"value","text":"undef"}', '{"id":"undef","name":"__detail_panel_toggle__","text":"undef","type":"checkbox"}');
  await MK.onClick(pageDetails3.inputobT1ZGI4RField, 34, 'before', `Clear`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 35, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-k9qqt8>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputTypeSearch.MuiInputBase-inputSizeSmall.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-1cludd7\",\"index\":0},{\"selector\":\"div>input\",\"index\":2},{\"selector\":\"INPUT[placeholder=\'Search\'][type=\'search\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r1l2:\'][@placeholder=\'Search\'][@type=\'search\']\",\"index\":0}]', 2, 'input', 'search', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r1l2:","name":"undef","text":"undef","type":"search"}');
  
  
  await MK.onAssignment(pageDetails3.input92InbPtKd3Field, 35, 'after', `Alerts`, 'search', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 36, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.labelWmfRXOsY49Field, 36, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 37, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.css-fa3int>input.PrivateSwitchBase-input.css-j8yymo\",\"index\":0},{\"selector\":\"span>input\",\"index\":1},{\"selector\":\"INPUT[name=\'__detail_panel_toggle__\'][type=\'checkbox\']\",\"index\":0},{\"selector\":\"//button[@aria-label=\\"Clear\\"]\",\"index\":0}]', 3, 'input', 'checkbox', 'click', '{"value":"Clear","searchType":"value","text":"undef"}', '{"id":"undef","name":"__detail_panel_toggle__","text":"undef","type":"checkbox"}');
  await MK.onClick(pageDetails3.inputobT1ZGI4RField, 37, 'before', `Clear`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 38, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-k9qqt8>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputTypeSearch.MuiInputBase-inputSizeSmall.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-1cludd7\",\"index\":0},{\"selector\":\"div>input\",\"index\":2},{\"selector\":\"INPUT[placeholder=\'Search\'][type=\'search\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r1l2:\'][@placeholder=\'Search\'][@type=\'search\']\",\"index\":0}]', 2, 'input', 'search', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r1l2:","name":"undef","text":"undef","type":"search"}');
  
  
  await MK.onAssignment(pageDetails3.input92InbPtKd3Field, 38, 'after', `Launched at`, 'search', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 39, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.label7JHMn7t6kField, 39, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 40, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.css-fa3int>input.PrivateSwitchBase-input.css-j8yymo\",\"index\":0},{\"selector\":\"span>input\",\"index\":1},{\"selector\":\"INPUT[name=\'__detail_panel_toggle__\'][type=\'checkbox\']\",\"index\":0},{\"selector\":\"//button[@aria-label=\\"Clear\\"]\",\"index\":0}]', 3, 'input', 'checkbox', 'click', '{"value":"Clear","searchType":"value","text":"undef"}', '{"id":"undef","name":"__detail_panel_toggle__","text":"undef","type":"checkbox"}');
  await MK.onClick(pageDetails3.inputobT1ZGI4RField, 40, 'before', `Clear`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 41, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-k9qqt8>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputTypeSearch.MuiInputBase-inputSizeSmall.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-1cludd7\",\"index\":0},{\"selector\":\"div>input\",\"index\":2},{\"selector\":\"INPUT[placeholder=\'Search\'][type=\'search\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r1l2:\'][@placeholder=\'Search\'][@type=\'search\']\",\"index\":0}]', 2, 'input', 'search', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r1l2:","name":"undef","text":"undef","type":"search"}');
  
  
  await MK.onAssignment(pageDetails3.input92InbPtKd3Field, 41, 'after', `Concluded at`, 'search', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 42, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.labelYDTVb3FNqField, 42, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 43, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.css-fa3int>input.PrivateSwitchBase-input.css-j8yymo\",\"index\":0},{\"selector\":\"span>input\",\"index\":1},{\"selector\":\"INPUT[name=\'__detail_panel_toggle__\'][type=\'checkbox\']\",\"index\":0},{\"selector\":\"//button[@aria-label=\\"Clear\\"]\",\"index\":0}]', 3, 'input', 'checkbox', 'click', '{"value":"Clear","searchType":"value","text":"undef"}', '{"id":"undef","name":"__detail_panel_toggle__","text":"undef","type":"checkbox"}');
  await MK.onClick(pageDetails3.inputobT1ZGI4RField, 43, 'before', `Clear`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 44, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-k9qqt8>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputTypeSearch.MuiInputBase-inputSizeSmall.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-1cludd7\",\"index\":0},{\"selector\":\"div>input\",\"index\":2},{\"selector\":\"INPUT[placeholder=\'Search\'][type=\'search\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r1l2:\'][@placeholder=\'Search\'][@type=\'search\']\",\"index\":0}]', 2, 'input', 'search', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r1l2:","name":"undef","text":"undef","type":"search"}');
  
  
  await MK.onAssignment(pageDetails3.input92InbPtKd3Field, 44, 'after', `Current owners`, 'search', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 45, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.label47f42uXbwField, 45, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 46, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.css-fa3int>input.PrivateSwitchBase-input.css-j8yymo\",\"index\":0},{\"selector\":\"span>input\",\"index\":1},{\"selector\":\"INPUT[name=\'__detail_panel_toggle__\'][type=\'checkbox\']\",\"index\":0},{\"selector\":\"//button[@aria-label=\\"Clear\\"]\",\"index\":0}]', 3, 'input', 'checkbox', 'click', '{"value":"Clear","searchType":"value","text":"undef"}', '{"id":"undef","name":"__detail_panel_toggle__","text":"undef","type":"checkbox"}');
  await MK.onClick(pageDetails3.inputobT1ZGI4RField, 46, 'before', `Clear`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 47, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-k9qqt8>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputTypeSearch.MuiInputBase-inputSizeSmall.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-1cludd7\",\"index\":0},{\"selector\":\"div>input\",\"index\":2},{\"selector\":\"INPUT[placeholder=\'Search\'][type=\'search\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r1l2:\'][@placeholder=\'Search\'][@type=\'search\']\",\"index\":0}]', 2, 'input', 'search', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r1l2:","name":"undef","text":"undef","type":"search"}');
  
  
  await MK.onAssignment(pageDetails3.input92InbPtKd3Field, 47, 'after', `Task completion`, 'search', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 48, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.labelA6sY0CWB9Field, 48, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 49, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.css-fa3int>input.PrivateSwitchBase-input.css-j8yymo\",\"index\":0},{\"selector\":\"span>input\",\"index\":1},{\"selector\":\"INPUT[name=\'__detail_panel_toggle__\'][type=\'checkbox\']\",\"index\":0},{\"selector\":\"//button[@aria-label=\\"Clear\\"]\",\"index\":0}]', 3, 'input', 'checkbox', 'click', '{"value":"Clear","searchType":"value","text":"undef"}', '{"id":"undef","name":"__detail_panel_toggle__","text":"undef","type":"checkbox"}');
  await MK.onClick(pageDetails3.inputobT1ZGI4RField, 49, 'before', `Clear`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 50, page.url(), '[{\"selector\":\"label.MuiFormControlLabel-root.MuiFormControlLabel-labelPlacementEnd.MuiDataGrid-columnsManagementRow.css-swmvbm>span.MuiTypography-root.MuiTypography-body1.MuiFormControlLabel-label.css-q31gs0\",\"index\":0},{\"selector\":\"label>span\",\"index\":1},{\"selector\":\"SPAN\",\"index\":88},{\"selector\":\"//SPAN[normalize-space() = \\"Detail panel toggle\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Detail panel toggle","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Detail panel toggle","type":"undef"}');
  await MK.onClick(pageDetails3.span4AhQ9KC30DField, 50, 'before', `Detail panel toggle`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 51, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(51, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('assertProperty', 52, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.div4aHr71tAOVField, 52, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 53, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r1i7:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"olumns\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r1i7:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails3.buttonqgSWeDhpp7Field, 53, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 54, page.url(), '[{\"selector\":\"label.MuiFormControlLabel-root.MuiFormControlLabel-labelPlacementEnd.MuiDataGrid-columnsManagementRow.css-swmvbm>span.MuiTypography-root.MuiTypography-body1.MuiFormControlLabel-label.css-q31gs0\",\"index\":1},{\"selector\":\"label>span\",\"index\":3},{\"selector\":\"SPAN\",\"index\":91},{\"selector\":\"//SPAN[normalize-space() = \\"Flow Instance Name\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Flow Instance Name","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Instance Name","type":"undef"}');
  await MK.onClick(pageDetails3.spanWQuwv2FZq6Field, 54, 'before', `Flow Instance Name`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 55, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(55, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('assertProperty', 56, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divWPFq6qcQqField, 56, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 57, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r1i7:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"olumns\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r1i7:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails3.buttonqgSWeDhpp7Field, 57, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 58, page.url(), '[{\"selector\":\"label.MuiFormControlLabel-root.MuiFormControlLabel-labelPlacementEnd.MuiDataGrid-columnsManagementRow.css-swmvbm>span.MuiTypography-root.MuiTypography-body1.MuiFormControlLabel-label.css-q31gs0\",\"index\":2},{\"selector\":\"label>span\",\"index\":5},{\"selector\":\"SPAN\",\"index\":92},{\"selector\":\"//SPAN[normalize-space() = \\"Progress\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Progress","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Progress","type":"undef"}');
  await MK.onClick(pageDetails3.span9bTPEQS2bqField, 58, 'before', `Progress`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 59, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(59, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('assertProperty', 60, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.div35T2btJJ8Field, 60, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 61, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r1i7:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"olumns\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r1i7:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails3.buttonqgSWeDhpp7Field, 61, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 62, page.url(), '[{\"selector\":\"label.MuiFormControlLabel-root.MuiFormControlLabel-labelPlacementEnd.MuiDataGrid-columnsManagementRow.css-swmvbm>span.MuiTypography-root.MuiTypography-body1.MuiFormControlLabel-label.css-q31gs0\",\"index\":3},{\"selector\":\"label>span\",\"index\":7},{\"selector\":\"SPAN\",\"index\":93},{\"selector\":\"//SPAN[normalize-space() = \\"Chat\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Chat","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Chat","type":"undef"}');
  await MK.onClick(pageDetails3.spanrMTbqrCYEField, 62, 'before', `Chat`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 63, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(63, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('assertProperty', 64, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divb6UN3TLdField, 64, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 65, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r1i7:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"olumns\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r1i7:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails3.buttonqgSWeDhpp7Field, 65, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 66, page.url(), '[{\"selector\":\"label.MuiFormControlLabel-root.MuiFormControlLabel-labelPlacementEnd.MuiDataGrid-columnsManagementRow.css-swmvbm>span.MuiTypography-root.MuiTypography-body1.MuiFormControlLabel-label.css-q31gs0\",\"index\":4},{\"selector\":\"label>span\",\"index\":9},{\"selector\":\"SPAN\",\"index\":94},{\"selector\":\"//SPAN[normalize-space() = \\"Status\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Status","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Status","type":"undef"}');
  await MK.onClick(pageDetails3.span7XfyZMT7EdField, 66, 'before', `Status`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 67, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(67, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('assertProperty', 68, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divaPhDqVUB3RField, 68, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 69, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r1i7:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"olumns\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r1i7:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails3.buttonqgSWeDhpp7Field, 69, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 70, page.url(), '[{\"selector\":\"label.MuiFormControlLabel-root.MuiFormControlLabel-labelPlacementEnd.MuiDataGrid-columnsManagementRow.css-swmvbm>span.MuiTypography-root.MuiTypography-body1.MuiFormControlLabel-label.css-q31gs0\",\"index\":5},{\"selector\":\"label>span\",\"index\":11},{\"selector\":\"SPAN\",\"index\":96},{\"selector\":\"//SPAN[normalize-space() = \\"Alerts\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Alerts","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Alerts","type":"undef"}');
  await MK.onClick(pageDetails3.spanKXUVRCGYField, 70, 'before', `Alerts`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 71, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(71, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('assertProperty', 72, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divnjCkBqio68Field, 72, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 73, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r1i7:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"olumns\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r1i7:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails3.buttonqgSWeDhpp7Field, 73, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 74, page.url(), '[{\"selector\":\"label.MuiFormControlLabel-root.MuiFormControlLabel-labelPlacementEnd.MuiDataGrid-columnsManagementRow.css-swmvbm>span.MuiTypography-root.MuiTypography-body1.MuiFormControlLabel-label.css-q31gs0\",\"index\":6},{\"selector\":\"label>span\",\"index\":13},{\"selector\":\"SPAN\",\"index\":99},{\"selector\":\"//SPAN[normalize-space() = \\"Launched at\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Launched at","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Launched at","type":"undef"}');
  await MK.onClick(pageDetails3.spanzwcNQ1hDvLField, 74, 'before', `Launched at`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 75, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(75, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('assertProperty', 76, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divP0hJgNHDoField, 76, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 77, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r1i7:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"olumns\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r1i7:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails3.buttonqgSWeDhpp7Field, 77, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 78, page.url(), '[{\"selector\":\"label.MuiFormControlLabel-root.MuiFormControlLabel-labelPlacementEnd.MuiDataGrid-columnsManagementRow.css-swmvbm>span.MuiTypography-root.MuiTypography-body1.MuiFormControlLabel-label.css-q31gs0\",\"index\":7},{\"selector\":\"label>span\",\"index\":15},{\"selector\":\"SPAN\",\"index\":101},{\"selector\":\"//SPAN[normalize-space() = \\"Concluded at\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Concluded at","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Concluded at","type":"undef"}');
  await MK.onClick(pageDetails3.spane9TAqXUey4Field, 78, 'before', `Concluded at`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 79, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(79, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('assertProperty', 80, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divOGfOp3saJZField, 80, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 81, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r1i7:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"olumns\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r1i7:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails3.buttonqgSWeDhpp7Field, 81, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 82, page.url(), '[{\"selector\":\"label.MuiFormControlLabel-root.MuiFormControlLabel-labelPlacementEnd.MuiDataGrid-columnsManagementRow.css-swmvbm>span.MuiTypography-root.MuiTypography-body1.MuiFormControlLabel-label.css-q31gs0\",\"index\":8},{\"selector\":\"label>span\",\"index\":17},{\"selector\":\"SPAN\",\"index\":103},{\"selector\":\"//SPAN[normalize-space() = \\"Current owners\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Current owners","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Current owners","type":"undef"}');
  await MK.onClick(pageDetails3.spanYAHAZH8O6Field, 82, 'before', `Current owners`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 83, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(83, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('assertProperty', 84, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divDAulPeCLqbField, 84, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 85, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r1i7:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"olumns\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r1i7:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails3.buttonqgSWeDhpp7Field, 85, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 86, page.url(), '[{\"selector\":\"label.MuiFormControlLabel-root.MuiFormControlLabel-labelPlacementEnd.MuiDataGrid-columnsManagementRow.css-swmvbm>span.MuiTypography-root.MuiTypography-body1.MuiFormControlLabel-label.css-q31gs0\",\"index\":9},{\"selector\":\"label>span\",\"index\":19},{\"selector\":\"SPAN\",\"index\":106},{\"selector\":\"//SPAN[normalize-space() = \\"Task completion\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Task completion","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Task completion","type":"undef"}');
  await MK.onClick(pageDetails3.spanjkI7AqCmeField, 86, 'before', `Task completion`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 87, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(87, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('assertProperty', 88, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divW0CvDlflx3Field, 88, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 89, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r1i7:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"olumns\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r1i7:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails3.buttonqgSWeDhpp7Field, 89, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 90, page.url(), '[{\"selector\":\"div.MuiDataGrid-columnsManagementFooter.css-qar90g>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.css-1fbl5f9\",\"index\":0},{\"selector\":\"div>button\",\"index\":21},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":19},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Reset\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Reset","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Reset","type":"button"}');
  await MK.onClick(pageDetails3.buttonPgF0GXHzjaField, 90, 'before', `Reset`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 91, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-mvaxqr>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeSmall.MuiButton-textSizeSmall.MuiButton-colorPrimary.css-ti7hx8\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r1i7:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][contains(text(), \\"olumns\\")]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r1i7:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails3.buttonqgSWeDhpp7Field, 91, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 94, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divWPFq6qcQqField, 94, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 95, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.div35T2btJJ8Field, 95, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 96, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divb6UN3TLdField, 96, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 97, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divaPhDqVUB3RField, 97, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 98, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divnjCkBqio68Field, 98, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 99, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divP0hJgNHDoField, 99, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 100, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divOGfOp3saJZField, 100, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 101, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divDAulPeCLqbField, 101, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 102, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divW0CvDlflx3Field, 102, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarApp2fd33cb5_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
