
/*
* Generated by MuukTest
* Test Case ID: TC78356
* Description: Confirm form task card button appears bold when form is attached to the task
* Generated: 2026-09-07T06:45:53.500Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavg23ukecibpwgt,  dashboardStagingNavg6aff5134ynezp,  dashboardStagingNavgi6v6em6ewluq,  dashboardStagingNavgkofw0eq9mwnj,  dashboardStagingNavgqphivbi190z,  dashboardStagingNavgd1gvyjomrq89,  dashboardStagingNavgedfekzv2p7h,  dashboardStagingNavgxcoaxm0cje3b,  dashboardStagingNavgxmxlzhntddzi,  dashboardStagingNavgulttdticq4c,  dashboardStagingNavgq0rqbwd69gz,  plWikipediaOrglfo8gnuqfflu,  deWikipediaOrgtmcq5hxffw9h,  dashboardStagingNavgqvs1p6as76e,  dashboardStagingNavgmg3hwg5v8at,  w3schoolsComjzqsyei6j6jl,  dashboardStagingNavghs7nom07p9nr,  dashboardStagingNavgtiw21r43k3ne,  dashboardStagingNavg500ungjzym7e,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarAppc6686cad.log';
const muukReport = new MuukReport('dashboardStagingNavgarAppc6686cad');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarAppc6686cad',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarAppc6686cad', muukReport);
  MK.setVideoTracker(200);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavg23ukecibpwgt();
	const pageDetails3 = new dashboardStagingNavg6aff5134ynezp();
	const pageDetails4 = new dashboardStagingNavgi6v6em6ewluq();
	const pageDetails5 = new dashboardStagingNavgkofw0eq9mwnj();
	const pageDetails6 = new dashboardStagingNavgqphivbi190z();
	const pageDetails7 = new dashboardStagingNavgd1gvyjomrq89();
	const pageDetails8 = new dashboardStagingNavgedfekzv2p7h();
	const pageDetails9 = new dashboardStagingNavgxcoaxm0cje3b();
	const pageDetails10 = new dashboardStagingNavgxmxlzhntddzi();
	const pageDetails11 = new dashboardStagingNavgulttdticq4c();
	const pageDetails12 = new dashboardStagingNavgq0rqbwd69gz();
	const pageDetails13 = new plWikipediaOrglfo8gnuqfflu();
	const pageDetails14 = new deWikipediaOrgtmcq5hxffw9h();
	const pageDetails15 = new dashboardStagingNavgqvs1p6as76e();
	const pageDetails16 = new dashboardStagingNavgmg3hwg5v8at();
	const pageDetails17 = new w3schoolsComjzqsyei6j6jl();
	const pageDetails18 = new dashboardStagingNavghs7nom07p9nr();
	const pageDetails19 = new dashboardStagingNavgtiw21r43k3ne();
	const pageDetails20 = new dashboardStagingNavg500ungjzym7e();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('snippet', 1, page.url());
  
  
  
  
  
  
  
   console.log('step:1'); 
  logIndex = 1;
  /*
await page.setViewportSize({
  width: 2560,
  height: 1440,
});
*/
   await MK.takeScreenshot(1); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('setValueGV', 2, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 3, page.url());
  
  
  
  
  
  
  
   console.log('step:3'); 
  logIndex = 3;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(3); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"ul.MuiList-root.MuiList-padding.flex.flex-col.gap-4.p-2.css-1wduhak>li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm\",\"index\":2},{\"selector\":\"ul>li\",\"index\":2},{\"selector\":\"LI\",\"index\":2},{\"selector\":\"//span[contains(text(), \\"Flow Templates\\")]\",\"index\":0}]', 3, 'li', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Templates","type":"undef"}');
  await MK.onClick(pageDetails2.liabIwKNSQYKField, 15, 'before', `Flow Templates`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('waitForLoadState', 16, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
   await MK.onWaitForLoadState(16, 'after', 'load', 60000); 
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"div.flex.flex-col.gap-2>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.py-2.px-4.flex.justify-start.css-1wvg4b\",\"index\":0},{\"selector\":\"div>button\",\"index\":2},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":2},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"+ New Flow Group\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"+ New Flow Group","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"+ New Flow Group","type":"button"}');
  await MK.onClick(pageDetails3.buttonX6CGBRCbonField, 17, 'before', `+ New Flow Group`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('setValueGV', 18, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 19, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.css-1k66m85>input.MuiInputBase-input.MuiOutlinedInput-input.css-1x5jdmq\",\"index\":0},{\"selector\":\"div>input\",\"index\":6},{\"selector\":\"INPUT[name=\'name\'][type=\'string\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r21:\'][@name=\'name\'][@type=\'string\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r21:","name":"name","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails3.inputp6fpkzSXjPField, 19, 'after', `Test` + randNum + ``, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"form.flex.gap-2>button.MuiButtonBase-root.MuiButton-root.MuiButton-outlined.MuiButton-outlinedSecondary.MuiButton-sizeSmall.MuiButton-outlinedSizeSmall.MuiButton-colorSecondary.MuiButton-root.MuiButton-outlined.MuiButton-outlinedSecondary.MuiButton-sizeSmall.MuiButton-outlinedSizeSmall.MuiButton-colorSecondary.css-s9suba\",\"index\":0},{\"selector\":\"form>button\",\"index\":1},{\"selector\":\"BUTTON[type=\'submit\'][id=\':r10:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'submit\'][normalize-space() = \\"Save\\"]\",\"index\":0}]', 3, 'button', 'submit', 'click', '{"value":"Save","searchType":"text","text":"undef"}', '{"id":":r10:","name":"undef","text":"Save","type":"submit"}');
  await MK.onClick(pageDetails6.button4AUwACYYQField, 20, 'before', `Save`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 21, page.url(), '[{\"selector\":\"div.flex.items-center.gap-2>p.MuiTypography-root.MuiTypography-body1.css-18r2qr7\",\"index\":0},{\"selector\":\"div>p\",\"index\":8},{\"selector\":\"P\",\"index\":8},{\"selector\":\"//P[normalize-space() = \\"Angel Ramirez\\"]\",\"index\":0}]', 3, 'p', '', 'mouseover', '{"value":"Angel Ramirez","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Angel Ramirez","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails6.pemH465UnjmField, 21, 'after', `Angel Ramirez`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 22, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(22, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('snippet', 23, page.url());
  
  
  
  
  
  
  
   console.log('step:23'); 
  logIndex = 23;
  //await page.locator('//P[contains(text(), "Test' + randNum + '")]').first().click();


container = page.locator('#template-groups-desktop-list');
timeoutMs = 60_000;
start = Date.now();

lastScrollTop = -1;
found = false;

while (Date.now() - start < timeoutMs) {
  row = page.locator(
    `//p[contains(text(), "Test${randNum}")]`
  );

  if (await row.count() > 0) {
    await row.first().scrollIntoViewIfNeeded();
    await row.first().click();
    found = true;
    break;
  }

  currentScrollTop = await container.evaluate(el => el.scrollTop);

  if (currentScrollTop === lastScrollTop) {
    await page.waitForTimeout(200); // allow UI to render
  }

  lastScrollTop = currentScrollTop;

  await container.evaluate(el => {
    el.scrollBy(0, 120);
  });

  await page.waitForTimeout(120);
}

if (!found) {
  throw new Error(`Element Test${randNum} not found after 1 min`);
}

   await MK.takeScreenshot(23); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 24, page.url(), '[{\"selector\":\"div.w-full.flex.gap-4.justify-end>button.MuiButtonBase-root.MuiButton-root.MuiButton-filled.MuiButton-filledPrimary.MuiButton-sizeMedium.MuiButton-filledSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-filled.MuiButton-filledPrimary.MuiButton-sizeMedium.MuiButton-filledSizeMedium.MuiButton-colorPrimary.w-fit.flex.items-center.gap-2.rounded-3xl.px-5.css-x051nh\",\"index\":0},{\"selector\":\"div>button\",\"index\":3},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":3},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"New\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"New","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"New","type":"button"}');
  await MK.onClick(pageDetails4.buttonNrcaoVI6DField, 24, 'before', `New`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 25, page.url(), '[{\"selector\":\"li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters.css-4lsp2c>p.MuiTypography-root.MuiTypography-body2.css-mnp47j\",\"index\":0},{\"selector\":\"li>p\",\"index\":0},{\"selector\":\"P\",\"index\":7},{\"selector\":\"//P[normalize-space() = \\"Flow Template\\"]\",\"index\":0}]', 3, 'p', '', 'click', '{"value":"Flow Template","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Template","type":"undef"}');
  await MK.onClick(pageDetails4.pMDtD4lhOR2Field, 25, 'before', `Flow Template`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 27, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.Mui-focused.MuiInputBase-formControl.css-dkp0g4>input.MuiInputBase-input.MuiOutlinedInput-input.css-1pk1fka\",\"index\":0},{\"selector\":\"div>input\",\"index\":5},{\"selector\":\"INPUT[name=\'name\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':rd8:\'][@name=\'name\'][@type=\'text\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":rd8:","name":"name","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails5.inputdjfnxeTqRJField, 27, 'after', `` + randName + `` + randNum + ``, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 28, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(28, 'after', `Enter`, 60000); 
  
  
  
  await muukReport.addStepInfo('waitForLoadState', 30, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
   await MK.onWaitForLoadState(30, 'after', 'domcontentloaded', 60000); 
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 31, page.url());
  
  
  
  
  await MK.onSleep(31, 'after', 1); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 32, page.url(), '[{\"selector\":\"div.flex.items-center.gap-2>button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.css-116ytbn\",\"index\":1},{\"selector\":\"div>button\",\"index\":24},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":23},{\"selector\":\"(//div[@class=\\"flex items-center justify-start gap-2\\"]//button)[last()]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"button"}');
  await MK.onClick(pageDetails18.buttonovh7xupEMField, 32, 'before', ``, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 33, page.url(), '[{\"selector\":\"div.flex.items-center.gap-2.w-\\\\[calc\\\\(100\\\\%-16rem\\\\)\\\\]>div.flex.w-full.flex-wrap.gap-2\",\"index\":0},{\"selector\":\"div>div\",\"index\":128},{\"selector\":\"DIV\",\"index\":145},{\"selector\":\"//div[@class=\\"flex w-full flex-wrap gap-2\\"]\",\"index\":0}]', 3, 'div', '', 'mouseover', '{"value":"Test3504 Test3504issues","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Test3504 Test3504issues","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails19.divnQsOWrivQlField, 33, 'after', `Test3504 Test3504issues`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 34, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(34, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('step', 37, page.url(), '[{\"selector\":\"div>a.no-checkmark\",\"index\":4},{\"selector\":\"div>a\",\"index\":246},{\"selector\":\"A\",\"index\":255},{\"selector\":\"//h6[contains(text(), \'Flow Templates\')]/following::button[contains(., \'New\')]/following::p[contains(text(), \'Test\')]\",\"index\":0}]', 3, 'a', '', 'mouseover', '{"value":"css_ref_pseudo_classes.php","searchType":"href","text":"CSS Pseudo-classes"}', '{"id":"undef","name":"undef","text":"CSS Pseudo-classes","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails17.avoc8m7SrMVField, 37, 'after', `Flow Template`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 38, page.url(), '[{\"selector\":\"div.flex.items-center.gap-2>button.MuiButtonBase-root.MuiButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeMedium.MuiButton-outlinedSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeMedium.MuiButton-outlinedSizeMedium.MuiButton-colorPrimary.rounded-3xl.whitespace-nowrap.css-9ohqbi\",\"index\":0},{\"selector\":\"div>button\",\"index\":8},{\"selector\":\"BUTTON[type=\'button\'][id=\':r69:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"View details\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"View details","searchType":"text","text":"undef"}', '{"id":":r69:","name":"undef","text":"View details","type":"button"}');
  await MK.onClick(pageDetails7.buttonVdfpGJImaField, 38, 'before', `View details`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 39, page.url(), '[{\"selector\":\"div.MuiTabs-flexContainer.css-1902i5q>button.MuiButtonBase-root.MuiTab-root.MuiTab-textColorPrimary.MuiTab-fullWidth.css-1df0jyd\",\"index\":0},{\"selector\":\"div>button\",\"index\":18},{\"selector\":\"BUTTON[type=\'button\'][role=\'tab\'][id=\'navgar-tab-flow-template-tasks\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][@role=\'tab\'][normalize-space() = \\"Template\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Template","searchType":"text","text":"undef"}', '{"id":"navgar-tab-flow-template-tasks","name":"undef","text":"Template","type":"button"}');
  await MK.onClick(pageDetails8.buttonqDHdqof4dRField, 39, 'before', `Template Tab`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 40, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.Mui-focused.MuiInputBase-formControl.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-l4bcd9>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-fvgl9b\",\"index\":0},{\"selector\":\"div>input\",\"index\":7},{\"selector\":\"INPUT[id=\':r23a:\'][name=\'legend\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@name=\'legend\'][@type=\'text\']\",\"index\":0}]', 3, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r23a:","name":"legend","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails9.inputv6T4PPHAQField, 40, 'after', `Task`, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 41, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(41, 'after', `Enter`, 60000); 
  
  
  
  await muukReport.addStepInfo('step', 42, page.url(), '[{\"selector\":\"div.flex.flex-1.items-start.justify-between.w-full>span.w-0.flex-1.overflow-hidden.text-ellipsis.whitespace-nowrap.max-w-full.text-sm.false\",\"index\":1},{\"selector\":\"div>span\",\"index\":32},{\"selector\":\"SPAN\",\"index\":81},{\"selector\":\"//SPAN[normalize-space() = \\"Task\\"]\",\"index\":1}]', 3, 'span', '', 'mouseover', '{"value":"Task","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Task","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails9.span8ptMXsWnMField, 42, 'after', `Task`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 43, page.url(), '[{\"selector\":\"div.ml-3.flex.gap-2.justify-end.items-center>button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.css-17x95qm\",\"index\":0},{\"selector\":\"div>button\",\"index\":0},{\"selector\":\"path\",\"index\":0},{\"selector\":\"//Button[@aria-label=\\"Add form\\"]\",\"index\":0}]', 3, 'path', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails11.path8GhQbfdYYField, 43, 'before', `Add Form`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 44, page.url(), '[{\"selector\":\"div.p-4.border-b.border-neutral-90.flex.justify-between.items-start.gap-4>div.flex.gap-2.w-full.h-full.undefined\",\"index\":25},{\"selector\":\"div>div\",\"index\":710},{\"selector\":\"DIV\",\"index\":769},{\"selector\":\"//DIV[normalize-space() = \\"Build your form\\"]\",\"index\":1}]', 3, 'div', '', 'mouseover', '{"value":"Build your form","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Build your form","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails11.divdkS05ecDmrField, 44, 'after', `Build your form`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 45, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.Mui-focused.MuiInputBase-formControl.css-dkp0g4>input.MuiInputBase-input.MuiOutlinedInput-input.css-1pk1fka\",\"index\":0},{\"selector\":\"div>input\",\"index\":32},{\"selector\":\"INPUT[name=\'input-builder-form-field-0\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r8q:\'][@name=\'input-builder-form-field-0\'][@type=\'text\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r8q:","name":"input-builder-form-field-0","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails11.inputMnTbmMh7GbField, 45, 'after', `Test Request`, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 46, page.url(), '[{\"selector\":\"div.flex.items-center.gap-3>button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeLarge.MuiButton-containedSizeLarge.MuiButton-colorPrimary.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeLarge.MuiButton-containedSizeLarge.MuiButton-colorPrimary.w-fit.css-x93ji5\",\"index\":0},{\"selector\":\"div>button\",\"index\":168},{\"selector\":\"BUTTON[type=\'button\'][id=\':rdd:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Save form\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Save form","searchType":"text","text":"undef"}', '{"id":":rdd:","name":"undef","text":"Save form","type":"button"}');
  await MK.onClick(pageDetails12.buttonVbhDObf5JNField, 46, 'before', `Save form`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 47, page.url(), '[{\"selector\":\"p>a\",\"index\":51},{\"selector\":\"p>a\",\"index\":51},{\"selector\":\"A[title=\'\']\",\"index\":0},{\"selector\":\"//SPAN[normalize-space() = \\"Task\\"]//*[local-name()=\\"svg\\"][@fill=\\"currentColor\\"]\",\"index\":0}]', 3, 'a', '', 'mouseover', '{"value":"/wiki/Michai%C5%82_%C5%81azariew","searchType":"href","text":"Michaiła Łazariewa"}', '{"id":"undef","name":"undef","text":"Michaiła Łazariewa","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails13.aRMFMRoHelField, 47, 'after', `Form Bold Icon`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 48, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(48, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('snippet', 52, page.url());
  
  
  
  
  
  
  
   console.log('step:52'); 
  logIndex = 52;
  /*
await page
  .locator(
    "//p[contains(@class, 'MuiTypography-root') and contains(text(),'" +
      randNum + "')]"
  )
  .nth(0)
  .hover();
  
  */
  
  await page
  .locator(
    "//p[contains(@class,'MuiTypography-root') and contains(text(),'" +
      randNum +
      "') and preceding-sibling::*[1][name()='svg']]"
  )
  .nth(1)
  .hover();
   await MK.takeScreenshot(52); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 53, page.url(), '[{\"selector\":\"div>button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.p-1.css-116ytbn\",\"index\":0},{\"selector\":\"div>button\",\"index\":0},{\"selector\":\"svg\",\"index\":0},{\"selector\":\"(//button[normalize-space()=\'View details\']/ancestor::div[contains(@class,\'group\')]//button)[3]\",\"index\":0}]', 3, 'svg', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails20.svg7Zcm45F94GField, 53, 'before', `3 dots`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 54, page.url(), '[{\"selector\":\"li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters.css-7ea6lj>span.text-xs.pr-3.pl-2.text-error-50\",\"index\":0},{\"selector\":\"li>span\",\"index\":16},{\"selector\":\"SPAN\",\"index\":64},{\"selector\":\"//SPAN[normalize-space() = \\"Delete flow\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Delete flow","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Delete flow","type":"undef"}');
  await MK.onClick(pageDetails4.span0EIe46t4zzField, 54, 'before', `Delete flow`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 60, page.url());
  
  
  
  
  
  
  
   console.log('step:60'); 
  logIndex = 60;
  //const input = page.locator('input[placeholder*="confirm the deletion" i]:visible');
//await input.fill(randName + randNum);

await page.locator('input[placeholder*="confirm the deletion" i]:visible')
.fill(randName + randNum);

await page.locator("(//div[@role='presentation'][contains(@class,'MuiModal-root')][not(contains(@class,'MuiModal-hidden'))][not(@aria-hidden='true')]//button[contains(@class,'MuiButton-containedPrimary')][.//text()[contains(.,'Yes, delete it')] or contains(., 'Yes, delete it')][not(@disabled)])[1]")
.first()
.click();
   await MK.takeScreenshot(60); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 63, page.url());
  
  
  
  
  
  
  
   console.log('step:63'); 
  logIndex = 63;
  // 1. Llenar el search input con el número random
searchInput = page.locator('input[placeholder="Search"]');
await searchInput.fill(`Test${randNum}`);
await page.waitForTimeout(300); // Esperar que filtre la lista

// 2. Esperar que aparezca exactamente un resultado en la lista
container = page.locator('#template-groups-desktop-list');
await expect(
  container.locator(`p.MuiTypography-body1:text-is("Test${randNum}")`)
).toHaveCount(1, { timeout: 10_000 });

// 3. Hacer hover sobre el único elemento encontrado
row = container.locator(`(//div[@class="flex w-full overflow-hidden gap-2"])[4]`);
await row.scrollIntoViewIfNeeded();
await row.hover();
   await MK.takeScreenshot(63); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 64, page.url(), '[{\"selector\":\"button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.css-p8cfh1>svg.MuiSvgIcon-root.MuiSvgIcon-fontSizeMedium.w-5.h-5.css-vubbuv\",\"index\":1},{\"selector\":\"button>svg\",\"index\":2},{\"selector\":\"svg[data-testid=\\"DeleteOutlineOutlinedIcon\\"]\",\"index\":0},{\"selector\":\"//div[contains(@class,\'flex items-center\')]//div[contains(@class,\'relative\')][2]/button[1]\",\"index\":0}]', 3, 'svg', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails3.svg8yHjjYhGYLField, 64, 'before', `Delete Icon`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 65, page.url(), '[{\"selector\":\"div.p-4.border-t.border-neutral-90.flex.justify-end.gap-2>button.MuiButtonBase-root.MuiButton-root.MuiButton-filled.MuiButton-filledPrimary.MuiButton-sizeMedium.MuiButton-filledSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-filled.MuiButton-filledPrimary.MuiButton-sizeMedium.MuiButton-filledSizeMedium.MuiButton-colorPrimary.css-x051nh\",\"index\":0},{\"selector\":\"div>button\",\"index\":17},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":16},{\"selector\":\"//h6[normalize-space() = \\"Delete group\\"]/following::BUTTON[@type=\'button\'][normalize-space() = \\"Yes, delete it\\"][1]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Yes, delete it","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Yes, delete it","type":"button"}');
  await MK.onClick(pageDetails3.buttongoh1zXcgBNField, 65, 'before', `Yes, Delete it`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 66, page.url());
  
  
  
  
  
  
  
   console.log('step:66'); 
  logIndex = 66;
  //locator = page.locator(`//P[contains(text(), "Test' + randNum + '")]`); 
//await page.waitForTimeout(2000); 
//isVisible = await locator.isVisible(); 
 
//if (isVisible) { 
//  throw new Error(`Flow Group shouldn't be visible`); 
//} 

   await MK.takeScreenshot(66); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarAppc6686cad_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
