
/*
* Generated by MuukTest
* Test Case ID: TC79395
* Description: Email: Confirm change button opens the email template selector overlay
* Generated: 2026-09-07T06:46:22.222Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavg23ukecibpwgt,  dashboardStagingNavg6aff5134ynezp,  dashboardStagingNavg500ungjzym7e,  dashboardStagingNavgy68pt464ms,  dashboardStagingNavgi6v6em6ewluq,  dashboardStagingNavgkofw0eq9mwnj,  dashboardStagingNavgqphivbi190z,  dashboardStagingNavgd1gvyjomrq89,  dashboardStagingNavgedfekzv2p7h,  dashboardStagingNavgxcoaxm0cje3b,  dashboardStagingNavgn7hgqxb2co,  dashboardStagingNavgdoodt65jvdel,  dashboardStagingNavgrrfvcdccwgg8,  dashboardStagingNavgm43e77ii3i5r,  dashboardStagingNavgwbc57d4ge2d,  dashboardStagingNavgk9zr1e6nyrh,  dashboardStagingNavgn19a290mdr2c,  dashboardStagingNavgyk699jlqza4s,  w3schoolsComjzqsyei6j6jl,  dashboardStagingNavghs7nom07p9nr,  dashboardStagingNavgtiw21r43k3ne,  dashboardStagingNavgpe4gqiep3kct,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarApp5143d79a.log';
const muukReport = new MuukReport('dashboardStagingNavgarApp5143d79a');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarApp5143d79a',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarApp5143d79a', muukReport);
  MK.setVideoTracker(200);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavg23ukecibpwgt();
	const pageDetails3 = new dashboardStagingNavg6aff5134ynezp();
	const pageDetails4 = new dashboardStagingNavg500ungjzym7e();
	const pageDetails5 = new dashboardStagingNavgy68pt464ms();
	const pageDetails6 = new dashboardStagingNavgi6v6em6ewluq();
	const pageDetails7 = new dashboardStagingNavgkofw0eq9mwnj();
	const pageDetails8 = new dashboardStagingNavgqphivbi190z();
	const pageDetails9 = new dashboardStagingNavgd1gvyjomrq89();
	const pageDetails10 = new dashboardStagingNavgedfekzv2p7h();
	const pageDetails11 = new dashboardStagingNavgxcoaxm0cje3b();
	const pageDetails12 = new dashboardStagingNavgn7hgqxb2co();
	const pageDetails13 = new dashboardStagingNavgdoodt65jvdel();
	const pageDetails14 = new dashboardStagingNavgrrfvcdccwgg8();
	const pageDetails15 = new dashboardStagingNavgm43e77ii3i5r();
	const pageDetails16 = new dashboardStagingNavgwbc57d4ge2d();
	const pageDetails17 = new dashboardStagingNavgk9zr1e6nyrh();
	const pageDetails18 = new dashboardStagingNavgn19a290mdr2c();
	const pageDetails19 = new dashboardStagingNavgyk699jlqza4s();
	const pageDetails20 = new w3schoolsComjzqsyei6j6jl();
	const pageDetails21 = new dashboardStagingNavghs7nom07p9nr();
	const pageDetails22 = new dashboardStagingNavgtiw21r43k3ne();
	const pageDetails23 = new dashboardStagingNavgpe4gqiep3kct();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"ul.MuiList-root.MuiList-padding.flex.flex-col.gap-4.p-2.css-1wduhak>li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm\",\"index\":2},{\"selector\":\"ul>li\",\"index\":2},{\"selector\":\"LI\",\"index\":2},{\"selector\":\"//span[contains(text(), \\"Flow Templates\\")]\",\"index\":0}]', 3, 'li', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Templates","type":"undef"}');
  await MK.onClick(pageDetails2.liabIwKNSQYKField, 14, 'before', `Flow Templates`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"div.flex.flex-col.gap-2>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.py-2.px-4.flex.justify-start.css-1wvg4b\",\"index\":0},{\"selector\":\"div>button\",\"index\":2},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":2},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"+ New Flow Group\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"+ New Flow Group","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"+ New Flow Group","type":"button"}');
  await MK.onClick(pageDetails3.buttonX6CGBRCbonField, 15, 'before', `+ New Flow Group`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('setValueGV', 16, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.css-1k66m85>input.MuiInputBase-input.MuiOutlinedInput-input.css-1x5jdmq\",\"index\":0},{\"selector\":\"div>input\",\"index\":6},{\"selector\":\"INPUT[name=\'name\'][type=\'string\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r21:\'][@name=\'name\'][@type=\'string\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r21:","name":"name","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails3.inputp6fpkzSXjPField, 17, 'after', `Test` + randNum + ``, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"form.flex.gap-2>button.MuiButtonBase-root.MuiButton-root.MuiButton-outlined.MuiButton-outlinedSecondary.MuiButton-sizeSmall.MuiButton-outlinedSizeSmall.MuiButton-colorSecondary.MuiButton-root.MuiButton-outlined.MuiButton-outlinedSecondary.MuiButton-sizeSmall.MuiButton-outlinedSizeSmall.MuiButton-colorSecondary.css-s9suba\",\"index\":0},{\"selector\":\"form>button\",\"index\":1},{\"selector\":\"BUTTON[type=\'submit\'][id=\':r10:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'submit\'][normalize-space() = \\"Save\\"]\",\"index\":0}]', 3, 'button', 'submit', 'click', '{"value":"Save","searchType":"text","text":"undef"}', '{"id":":r10:","name":"undef","text":"Save","type":"submit"}');
  await MK.onClick(pageDetails8.button4AUwACYYQField, 18, 'before', `Save`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 19, page.url(), '[{\"selector\":\"div.flex.items-center.gap-2>p.MuiTypography-root.MuiTypography-body1.css-18r2qr7\",\"index\":0},{\"selector\":\"div>p\",\"index\":8},{\"selector\":\"P\",\"index\":8},{\"selector\":\"//P[normalize-space() = \\"Angel Ramirez\\"]\",\"index\":0}]', 3, 'p', '', 'mouseover', '{"value":"Angel Ramirez","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Angel Ramirez","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails8.pemH465UnjmField, 19, 'after', `Angel Ramirez`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 20, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(20, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('snippet', 21, page.url());
  
  
  
  
  
  
  
   console.log('step:21'); 
  logIndex = 21;
  //await page.locator('//P[contains(text(), "Test' + randNum + '")]').first().click();


container = page.locator('#template-groups-desktop-list');
timeoutMs = 60_000;
start = Date.now();

lastScrollTop = -1;
found = false;

while (Date.now() - start < timeoutMs) {
  row = page.locator(
    `//p[contains(text(), "Test${randNum}")]`
  );

  if (await row.count() > 0) {
    await row.first().scrollIntoViewIfNeeded();
    await row.first().click();
    found = true;
    break;
  }

  currentScrollTop = await container.evaluate(el => el.scrollTop);

  if (currentScrollTop === lastScrollTop) {
    await page.waitForTimeout(200); // allow UI to render
  }

  lastScrollTop = currentScrollTop;

  await container.evaluate(el => {
    el.scrollBy(0, 120);
  });

  await page.waitForTimeout(120);
}

if (!found) {
  throw new Error(`Element Test${randNum} not found after 1 min`);
}

   await MK.takeScreenshot(21); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 22, page.url(), '[{\"selector\":\"div.w-full.flex.gap-4.justify-end>button.MuiButtonBase-root.MuiButton-root.MuiButton-filled.MuiButton-filledPrimary.MuiButton-sizeMedium.MuiButton-filledSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-filled.MuiButton-filledPrimary.MuiButton-sizeMedium.MuiButton-filledSizeMedium.MuiButton-colorPrimary.w-fit.flex.items-center.gap-2.rounded-3xl.px-5.css-x051nh\",\"index\":0},{\"selector\":\"div>button\",\"index\":3},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":3},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"New\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"New","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"New","type":"button"}');
  await MK.onClick(pageDetails6.buttonNrcaoVI6DField, 22, 'before', `New`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 23, page.url(), '[{\"selector\":\"li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters.css-4lsp2c>p.MuiTypography-root.MuiTypography-body2.css-mnp47j\",\"index\":0},{\"selector\":\"li>p\",\"index\":0},{\"selector\":\"P\",\"index\":7},{\"selector\":\"//P[normalize-space() = \\"Flow Template\\"]\",\"index\":0}]', 3, 'p', '', 'click', '{"value":"Flow Template","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Template","type":"undef"}');
  await MK.onClick(pageDetails6.pMDtD4lhOR2Field, 23, 'before', `Flow Template`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 25, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.Mui-focused.MuiInputBase-formControl.css-dkp0g4>input.MuiInputBase-input.MuiOutlinedInput-input.css-1pk1fka\",\"index\":0},{\"selector\":\"div>input\",\"index\":5},{\"selector\":\"INPUT[name=\'name\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':rd8:\'][@name=\'name\'][@type=\'text\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":rd8:","name":"name","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails7.inputdjfnxeTqRJField, 25, 'after', `` + randName + `` + randNum + ``, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 26, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(26, 'after', `Enter`, 60000); 
  
  
  
  await muukReport.addStepInfo('waitForLoadState', 28, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
   await MK.onWaitForLoadState(28, 'after', 'domcontentloaded', 60000); 
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 29, page.url());
  
  
  
  
  await MK.onSleep(29, 'after', 1); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 30, page.url(), '[{\"selector\":\"div.flex.items-center.gap-2>button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.css-116ytbn\",\"index\":1},{\"selector\":\"div>button\",\"index\":24},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":23},{\"selector\":\"(//div[@class=\\"flex items-center justify-start gap-2\\"]//button)[last()]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"button"}');
  await MK.onClick(pageDetails21.buttonovh7xupEMField, 30, 'before', ``, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 31, page.url(), '[{\"selector\":\"div.flex.items-center.gap-2.w-\\\\[calc\\\\(100\\\\%-16rem\\\\)\\\\]>div.flex.w-full.flex-wrap.gap-2\",\"index\":0},{\"selector\":\"div>div\",\"index\":128},{\"selector\":\"DIV\",\"index\":145},{\"selector\":\"//div[@class=\\"flex w-full flex-wrap gap-2\\"]\",\"index\":0}]', 3, 'div', '', 'mouseover', '{"value":"Test3504 Test3504issues","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Test3504 Test3504issues","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails22.divnQsOWrivQlField, 31, 'after', `Test3504 Test3504issues`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 32, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(32, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('step', 35, page.url(), '[{\"selector\":\"div>a.no-checkmark\",\"index\":4},{\"selector\":\"div>a\",\"index\":246},{\"selector\":\"A\",\"index\":255},{\"selector\":\"//h6[contains(text(), \'Flow Templates\')]/following::button[contains(., \'New\')]/following::p[contains(text(), \'Test\')]\",\"index\":0}]', 3, 'a', '', 'mouseover', '{"value":"css_ref_pseudo_classes.php","searchType":"href","text":"CSS Pseudo-classes"}', '{"id":"undef","name":"undef","text":"CSS Pseudo-classes","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails20.avoc8m7SrMVField, 35, 'after', `Flow Template`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 36, page.url(), '[{\"selector\":\"div.flex.items-center.gap-2>button.MuiButtonBase-root.MuiButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeMedium.MuiButton-outlinedSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeMedium.MuiButton-outlinedSizeMedium.MuiButton-colorPrimary.rounded-3xl.whitespace-nowrap.css-9ohqbi\",\"index\":0},{\"selector\":\"div>button\",\"index\":8},{\"selector\":\"BUTTON[type=\'button\'][id=\':r69:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"View details\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"View details","searchType":"text","text":"undef"}', '{"id":":r69:","name":"undef","text":"View details","type":"button"}');
  await MK.onClick(pageDetails9.buttonVdfpGJImaField, 36, 'before', `View details`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 37, page.url(), '[{\"selector\":\"div.MuiTabs-flexContainer.css-1902i5q>button.MuiButtonBase-root.MuiTab-root.MuiTab-textColorPrimary.MuiTab-fullWidth.css-1df0jyd\",\"index\":0},{\"selector\":\"div>button\",\"index\":18},{\"selector\":\"BUTTON[type=\'button\'][role=\'tab\'][id=\'navgar-tab-flow-template-tasks\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][@role=\'tab\'][normalize-space() = \\"Template\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Template","searchType":"text","text":"undef"}', '{"id":"navgar-tab-flow-template-tasks","name":"undef","text":"Template","type":"button"}');
  await MK.onClick(pageDetails10.buttonqDHdqof4dRField, 37, 'before', `Template Tab`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 38, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.Mui-focused.MuiInputBase-formControl.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-l4bcd9>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-fvgl9b\",\"index\":0},{\"selector\":\"div>input\",\"index\":7},{\"selector\":\"INPUT[id=\':r23a:\'][name=\'legend\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@name=\'legend\'][@type=\'text\']\",\"index\":0}]', 3, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r23a:","name":"legend","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails11.inputv6T4PPHAQField, 38, 'after', `Task`, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 39, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(39, 'after', `Enter`, 60000); 
  
  
  
  await muukReport.addStepInfo('step', 40, page.url(), '[{\"selector\":\"div.flex.flex-1.items-start.justify-between.w-full>span.w-0.flex-1.overflow-hidden.text-ellipsis.whitespace-nowrap.max-w-full.text-sm.false\",\"index\":1},{\"selector\":\"div>span\",\"index\":32},{\"selector\":\"SPAN\",\"index\":81},{\"selector\":\"//SPAN[normalize-space() = \\"Task\\"]\",\"index\":1}]', 3, 'span', '', 'mouseover', '{"value":"Task","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Task","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails11.span8ptMXsWnMField, 40, 'after', `Task`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 41, page.url(), '[{\"selector\":\"div.ml-3.flex.gap-2.justify-end.items-center>button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.css-2pwci3\",\"index\":0},{\"selector\":\"div>button\",\"index\":32},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":31},{\"selector\":\"//*[@aria-label=\\"Owner: unassigned\\"]/parent::button\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"button"}');
  await MK.onClick(pageDetails16.buttonbbtNJsWDYField, 41, 'before', `Unassigned`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 42, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-dense.MuiListItem-gutters.css-br3psm>div.MuiButtonBase-root.MuiListItemButton-root.MuiListItemButton-dense.MuiListItemButton-gutters.MuiListItemButton-root.MuiListItemButton-dense.MuiListItemButton-gutters.css-qcs2fg\",\"index\":1},{\"selector\":\"li>div\",\"index\":16},{\"selector\":\"DIV[role=\'button\']\",\"index\":67},{\"selector\":\"//span[contains(normalize-space(), \\"Angel Ramirez\\")]\",\"index\":0}]', 3, 'div', '', 'click', '{"value":"ARAR Angel Ramirez","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"ARAR Angel Ramirez","type":"undef"}');
  await MK.onClick(pageDetails16.divXdCzowtELXField, 42, 'before', `Angel Ramirez`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 43, page.url(), '[{\"selector\":\"span.MuiAccordionSummary-expandIconWrapper.css-f8wb7g>div.p-1.rounded-2xl.bg-primary-95\",\"index\":0},{\"selector\":\"span>div\",\"index\":0},{\"selector\":\"svg\",\"index\":0},{\"selector\":\"//button[@aria-label=\\"Add step below\\"]\",\"index\":0}]', 3, 'svg', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails13.svglwTBXdHoeeField, 43, 'before', `Expand Icon`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 44, page.url(), '[{\"selector\":\"div.flex.flex-col.gap-2.items-center.justify-center.max-w-20.break-words.text-center>div.bg-primary-50.border.border-primary-50.rounded-full.p-3.cursor-pointer\",\"index\":0},{\"selector\":\"div>div\",\"index\":169},{\"selector\":\"DIV\",\"index\":203},{\"selector\":\"//span[normalize-space()=\'Task\']/preceding-sibling::div\",\"index\":0}]', 3, 'div', '', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails19.divZ8h6pYf0YField, 44, 'before', `Human`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 45, page.url(), '[{\"selector\":\"div.flex.flex-1.items-start.justify-between.w-full>span.w-0.flex-1.overflow-hidden.text-ellipsis.whitespace-nowrap.max-w-full.text-sm.text-base.text-gray-400.bg-orange-100.hover:bg-orange-200.w-fit\",\"index\":0},{\"selector\":\"div>span\",\"index\":29},{\"selector\":\"SPAN\",\"index\":88},{\"selector\":\"//SPAN[normalize-space() = \\"+ Add a task name\\"]\",\"index\":1}]', 3, 'span', '', 'click', '{"value":"+ Add a task name","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"+ Add a task name","type":"undef"}');
  await MK.onClick(pageDetails16.span5rsgoFaPGField, 45, 'before', `+ Add a task name`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 46, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiInput-root.MuiInput-underline.MuiInputBase-colorPrimary.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-multiline.css-5mznhh>textarea.MuiInputBase-input.MuiInput-input.MuiInputBase-inputMultiline.MuiInputBase-inputSizeSmall.css-n2bewn\",\"index\":0},{\"selector\":\"div>textarea\",\"index\":0},{\"selector\":\"TEXTAREA[name=\'legend\'][placeholder=\'+ Add a task name\']\",\"index\":0},{\"selector\":\"//span[contains(text(), \'+ Add a task name\')]\",\"index\":0}]', 2, 'textarea', 'textarea', 'assignment', '{"value":"Second Task","searchType":"value","text":"undef"}', '{"id":"taskname-input-de4695ad-2dad-4fde-ad8a-cc141c82f9a0","name":"legend","text":"undef","type":"textarea"}');
  
  
  await MK.onAssignment(pageDetails16.textareaAOuPnQTwNpField, 46, 'after', `Second Task`, 'textarea', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 47, page.url(), '[{\"selector\":\"div.ml-3.flex.gap-2.justify-end.items-center>button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.css-2pwci3\",\"index\":0},{\"selector\":\"div>button\",\"index\":32},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":31},{\"selector\":\"//*[@aria-label=\\"Owner: unassigned\\"]/parent::button\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"button"}');
  await MK.onClick(pageDetails16.buttonbbtNJsWDYField, 47, 'before', `Unassigned`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 48, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-dense.MuiListItem-gutters.css-br3psm>div.MuiButtonBase-root.MuiListItemButton-root.MuiListItemButton-dense.MuiListItemButton-gutters.MuiListItemButton-root.MuiListItemButton-dense.MuiListItemButton-gutters.css-qcs2fg\",\"index\":1},{\"selector\":\"li>div\",\"index\":16},{\"selector\":\"DIV[role=\'button\']\",\"index\":67},{\"selector\":\"//span[contains(normalize-space(), \\"Angel Ramirez\\")]\",\"index\":0}]', 3, 'div', '', 'click', '{"value":"ARAR Angel Ramirez","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"ARAR Angel Ramirez","type":"undef"}');
  await MK.onClick(pageDetails16.divXdCzowtELXField, 48, 'before', `Angel Ramirez`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 51, page.url(), '[{\"selector\":\"div.ml-3.flex.gap-2.justify-end.items-center>button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.css-17x95qm\",\"index\":0},{\"selector\":\"div>button\",\"index\":0},{\"selector\":\"path\",\"index\":0},{\"selector\":\"//div[contains(@class, \\"justify-end\\")]//button[contains(@class, \\"MuiIconButton-root\\")]\",\"index\":5}]', 3, 'path', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails12.pathBJc0YbU9OField, 51, 'before', `Human Icon`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 52, page.url(), '[{\"selector\":\"div.p-4.max-w-72>p.MuiTypography-root.MuiTypography-body1.font-bold.css-1r8bcx0\",\"index\":0},{\"selector\":\"div>p\",\"index\":45},{\"selector\":\"P\",\"index\":47},{\"selector\":\"//P[normalize-space() = \\"Select a task type\\"]\",\"index\":0}]', 3, 'p', '', 'mouseover', '{"value":"Select a task type","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Select a task type","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails12.pEWHKz5t43rField, 52, 'after', `Select a task type`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 53, page.url(), '[{\"selector\":\"div.flex.flex-col.gap-2.items-center.justify-center.max-w-20.break-words.text-center>div.bg-white.border.border-primary-50.rounded-full.p-3.cursor-pointer\",\"index\":0},{\"selector\":\"div>div\",\"index\":0},{\"selector\":\"svg\",\"index\":0},{\"selector\":\"//span[normalize-space()=\\"Navgar Email\\"]/parent::div\",\"index\":0}]', 3, 'svg', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails12.svg9QcDMTeOwField, 53, 'before', `Mail Icon`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 54, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(54, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('step', 55, page.url(), '[{\"selector\":\"span.MuiAccordionSummary-expandIconWrapper.css-f8wb7g>div.p-1.rounded-2xl.bg-primary-95\",\"index\":0},{\"selector\":\"span>div\",\"index\":0},{\"selector\":\"svg\",\"index\":0},{\"selector\":\"//span[contains(@class, \\"MuiAccordionSummary-expandIconWrapper\\")]\",\"index\":0}]', 3, 'svg', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails18.svg9aTPy9HY5AField, 55, 'before', `Expand icon`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 56, page.url(), '[{\"selector\":\"div.p-4.w-full.rounded-2xl.bg-error-95.flex.flex-col.items-center.justify-center.gap-3>button.MuiButtonBase-root.MuiButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeMedium.MuiButton-outlinedSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeMedium.MuiButton-outlinedSizeMedium.MuiButton-colorPrimary.rounded-3xl.css-9ohqbi\",\"index\":0},{\"selector\":\"div>button\",\"index\":175},{\"selector\":\"BUTTON[type=\'button\'][id=\':rpb:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Add new\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Add new","searchType":"text","text":"undef"}', '{"id":":rpb:","name":"undef","text":"Add new","type":"button"}');
  await MK.onClick(pageDetails13.buttonqRFP6JSlAQField, 56, 'before', `Add New`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarApp5143d79a_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
