
/*
* Generated by MuukTest
* Test Case ID: TC77378
* Description: Email Template Confirm delete button opens confirmation prompt
* Generated: 2026-09-07T06:45:16.878Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavg23ukecibpwgt,  dashboardStagingNavg6aff5134ynezp,  dashboardStagingNavg500ungjzym7e,  dashboardStagingNavgi6v6em6ewluq,  dashboardStagingNavgkofw0eq9mwnj,  dashboardStagingNavgltc4sug8epm,  dashboardStagingNavgjqieau50ddm,  dashboardStagingNavghm8rzbqubw,  dashboardStagingNavgmxjmxomvd4i,  dashboardStagingNavgqphivbi190z,  dashboardStagingNavgoqdvkm3dllff,  dashboardStagingNavgk77s3ialci3q,  zhWikipediaOrggtouzdy6get,  zhWikipediaOrgdhcsxqdifezc,  zhWikipediaOrgllh0fypz36l,  dashboardStagingNavgqi1mhst77qgp,  dashboardStagingNavgd1gvyjomrq89,  dashboardStagingNavgnfkiio9tjt9v,  dashboardStagingNavgm2rologlbca,  developerMozillaOrgxzdbdgwwbnu4,  w3schoolsComjzqsyei6j6jl,  dashboardStagingNavghs7nom07p9nr,  dashboardStagingNavgtiw21r43k3ne,  dashboardStagingNavgc0aaxv9q4tc,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarApp684987eb.log';
const muukReport = new MuukReport('dashboardStagingNavgarApp684987eb');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarApp684987eb',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarApp684987eb', muukReport);
  MK.setVideoTracker(0);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavg23ukecibpwgt();
	const pageDetails3 = new dashboardStagingNavg6aff5134ynezp();
	const pageDetails4 = new dashboardStagingNavg500ungjzym7e();
	const pageDetails5 = new dashboardStagingNavgi6v6em6ewluq();
	const pageDetails6 = new dashboardStagingNavgkofw0eq9mwnj();
	const pageDetails7 = new dashboardStagingNavgltc4sug8epm();
	const pageDetails8 = new dashboardStagingNavgjqieau50ddm();
	const pageDetails9 = new dashboardStagingNavghm8rzbqubw();
	const pageDetails10 = new dashboardStagingNavgmxjmxomvd4i();
	const pageDetails11 = new dashboardStagingNavgqphivbi190z();
	const pageDetails12 = new dashboardStagingNavgoqdvkm3dllff();
	const pageDetails13 = new dashboardStagingNavgk77s3ialci3q();
	const pageDetails14 = new zhWikipediaOrggtouzdy6get();
	const pageDetails15 = new zhWikipediaOrgdhcsxqdifezc();
	const pageDetails16 = new zhWikipediaOrgllh0fypz36l();
	const pageDetails17 = new dashboardStagingNavgqi1mhst77qgp();
	const pageDetails18 = new dashboardStagingNavgd1gvyjomrq89();
	const pageDetails19 = new dashboardStagingNavgnfkiio9tjt9v();
	const pageDetails20 = new dashboardStagingNavgm2rologlbca();
	const pageDetails21 = new developerMozillaOrgxzdbdgwwbnu4();
	const pageDetails22 = new w3schoolsComjzqsyei6j6jl();
	const pageDetails23 = new dashboardStagingNavghs7nom07p9nr();
	const pageDetails24 = new dashboardStagingNavgtiw21r43k3ne();
	const pageDetails25 = new dashboardStagingNavgc0aaxv9q4tc();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"ul.MuiList-root.MuiList-padding.flex.flex-col.gap-4.p-2.css-1wduhak>li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm\",\"index\":2},{\"selector\":\"ul>li\",\"index\":2},{\"selector\":\"LI\",\"index\":2},{\"selector\":\"//span[contains(text(), \\"Flow Templates\\")]\",\"index\":0}]', 3, 'li', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Templates","type":"undef"}');
  await MK.onClick(pageDetails2.liabIwKNSQYKField, 14, 'before', `Flow Templates`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"div.w-full.flex.gap-4.justify-end>button.MuiButtonBase-root.MuiButton-root.MuiButton-filled.MuiButton-filledPrimary.MuiButton-sizeMedium.MuiButton-filledSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-filled.MuiButton-filledPrimary.MuiButton-sizeMedium.MuiButton-filledSizeMedium.MuiButton-colorPrimary.w-fit.flex.items-center.gap-2.rounded-3xl.px-5.css-x051nh\",\"index\":0},{\"selector\":\"div>button\",\"index\":3},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":3},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"New\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"New","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"New","type":"button"}');
  await MK.onClick(pageDetails5.buttonNrcaoVI6DField, 15, 'before', `New`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters.css-4lsp2c>p.MuiTypography-root.MuiTypography-body2.css-mnp47j\",\"index\":1},{\"selector\":\"li>p\",\"index\":1},{\"selector\":\"P\",\"index\":13},{\"selector\":\"//P[normalize-space() = \\"Email Template\\"]\",\"index\":0}]', 3, 'p', '', 'click', '{"value":"Email Template","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Email Template","type":"undef"}');
  await MK.onClick(pageDetails4.ppn8tN9t4K0Field, 16, 'before', `Email Template`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('setValueGV', 17, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.rounded-lg.border-secondary-80.border.MuiInputBase-colorPrimary.Mui-focused.MuiInputBase-formControl.MuiInputBase-adornedStart.css-11879au>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputAdornedStart.css-1ooubvk\",\"index\":0},{\"selector\":\"div>input\",\"index\":5},{\"selector\":\"INPUT[placeholder=\'Add the email template name\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r2p:\'][@placeholder=\'Add the email template name\'][@type=\'text\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r2p:","name":"undef","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails12.inputl1tA05sgQQField, 18, 'after', `Test` + randNum + ``, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 19, page.url(), '[{\"selector\":\"div.flex.flex-col.gap-4.w-full.p-6.overflow-auto>div.flex.gap-2.p-2.rounded-lg.border.border-solid.border-secondary-80\",\"index\":1},{\"selector\":\"div>div\",\"index\":141},{\"selector\":\"DIV\",\"index\":165},{\"selector\":\"//p[@data-placeholder=\\"Subject\\"]\",\"index\":0}]', 3, 'div', '', 'assignment', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  
  
  await MK.onAssignment(pageDetails12.divgDuXzES1jpField, 19, 'after', `Test Subject`, '', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"div.flex.items-start.gap-2.w-full>div.break-words.w-full.max-h-64.overflow-auto.py-2.undefined\",\"index\":2},{\"selector\":\"div>div\",\"index\":150},{\"selector\":\"DIV[id=\'reply_to_raw-undefined\']\",\"index\":0},{\"selector\":\"//p[@data-placeholder=\\"Reply to\\"]\",\"index\":0}]', 3, 'div', '', 'assignment', '{"value":"","searchType":"text","text":"undef"}', '{"id":"reply_to_raw-undefined","name":"undef","text":"undef","type":"undef"}');
  
  
  await MK.onAssignment(pageDetails12.divAkT95mf80JField, 20, 'after', `nul@nul.com`, '', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 21, page.url(), '[{\"selector\":\"div.flex.flex-1.w-full.items-center.justify-between.gap-2.p-4.hover:bg-neutralVariant-90>div.w-fit.px-2.py-1.text-tertiary-40.text-ellipsis.overflow-hidden.whitespace-nowrap\",\"index\":0},{\"selector\":\"div>div\",\"index\":460},{\"selector\":\"DIV\",\"index\":484},{\"selector\":\"//H6[normalize-space() = \\"Variables created\\"]/following::DIV[normalize-space() = \\"{{email address to be sent}}\\"][1]\",\"index\":0}]', 3, 'div', '', 'mouseover', '{"value":"{{email address to be sent}}","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"{{email address to be sent}}","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails13.divYgT0Y8fQAPField, 21, 'after', `{{email address to be sent}}`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 22, page.url(), '[{\"selector\":\"div.flex.items-center.gap-3>div\",\"index\":0},{\"selector\":\"div>div\",\"index\":0},{\"selector\":\"svg\",\"index\":0},{\"selector\":\"//div[@aria-label=\\"Delete variable\\"]\",\"index\":0}]', 3, 'svg', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails13.svgkzIm1FbPdField, 22, 'before', `Delete Icon`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 23, page.url(), '[{\"selector\":\"div.flex.gap-2.w-full.h-full.undefined>h6.MuiTypography-root.MuiTypography-h6.flex.items-center.gap-1.text-lg.leading-6.css-o9z1z5\",\"index\":1},{\"selector\":\"div>h6\",\"index\":3},{\"selector\":\"H6\",\"index\":3},{\"selector\":\"//H6[contains(text(),\\"Delete variable\\")]\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Delete variable","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails12.h6OgI1QYHAP7Field, 23, 'after', `Delete variable`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 24, page.url(), '[{\"selector\":\"div.p-4.border-t.border-neutral-90.flex.justify-end.gap-2>button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.css-whu7dn\",\"index\":0},{\"selector\":\"div>button\",\"index\":104},{\"selector\":\"BUTTON[type=\'button\'][id=\':rbh:\']\",\"index\":0},{\"selector\":\"(//h6[contains(text(),\\"Delete variable\\")]/following::BUTTON[@type=\'button\'][normalize-space() = \\"Yes, delete it\\"])[1]\",\"index\":0}]', 3, 'button', 'button', 'mouseover', '{"value":"Yes, delete it","searchType":"text","text":"undef"}', '{"id":":rbh:","name":"undef","text":"Yes, delete it","type":"button"}');
  
  
  
  await MK.onMouseover(pageDetails12.buttonvqH0RaCMAvField, 24, 'after', `Yes, delete it`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 25, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(25, 'after', `Escape`, 60000); 
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarApp684987eb_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
