
/*
* Generated by MuukTest
* Test Case ID: TC85411
* Description: Confirm instance variable fields are not editable
* Generated: 2026-09-11T05:00:13.203Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavgdgn1vrnzb8i,  dashboardStagingNavgsc2nzmxtl6i,  dashboardStagingNavgpdf06d4i7z5h,  dashboardStagingNavge2hrlw3e2g,  dashboardStagingNavgd9lhsn4zm4hm,  dashboardStagingNavga1abchplkmi,  dashboardStagingNavghb1ldm1m6wx,  dashboardStagingNavghma43jsmvjtj,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarAppba25432f.log';
const muukReport = new MuukReport('dashboardStagingNavgarAppba25432f');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarAppba25432f',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarAppba25432f', muukReport);
  MK.setVideoTracker(200);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavgdgn1vrnzb8i();
	const pageDetails3 = new dashboardStagingNavgsc2nzmxtl6i();
	const pageDetails4 = new dashboardStagingNavgpdf06d4i7z5h();
	const pageDetails5 = new dashboardStagingNavge2hrlw3e2g();
	const pageDetails6 = new dashboardStagingNavgd9lhsn4zm4hm();
	const pageDetails7 = new dashboardStagingNavga1abchplkmi();
	const pageDetails8 = new dashboardStagingNavghb1ldm1m6wx();
	const pageDetails9 = new dashboardStagingNavghma43jsmvjtj();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm>span.text-xs.whitespace-break-spaces.w-fit.text-center.text-primary-10.font-bold\",\"index\":0},{\"selector\":\"li>span\",\"index\":5},{\"selector\":\"SPAN\",\"index\":23},{\"selector\":\"//SPAN[normalize-space() = \\"Running Flows\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Running Flows","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Running Flows","type":"undef"}');
  await MK.onClick(pageDetails2.spanNBH4dJhX1Field, 14, 'before', `Running Flows`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"div.MuiBox-root.css-3eqgl8>h6.MuiTypography-root.MuiTypography-subtitle1.css-bwj3c4\",\"index\":0},{\"selector\":\"div>h6\",\"index\":0},{\"selector\":\"H6\",\"index\":0},{\"selector\":\"//h6[normalize-space() = \'Running Flows\']\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Running Flows","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails3.h6MKsWgxI4nField, 15, 'after', `Running Flows - header`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"div.flex.items-center.gap-4.w-full>a.MuiTypography-root.MuiTypography-inherit.MuiLink-root.MuiLink-underlineAlways.no-underline.font-bold.max-w-full.overflow-hidden.text-ellipsis.whitespace-nowrap.cursor-pointer.css-5cdlzg\",\"index\":0},{\"selector\":\"div>a\",\"index\":15},{\"selector\":\"A\",\"index\":15},{\"selector\":\"//A[normalize-space() = \\"TestRunningFlowTemplate\\"]\",\"index\":0}]', 3, 'a', '', 'click', '{"value":"/104/apps/instances/116073?task=116073","searchType":"href","text":"TestRunningFlowTemplate"}', '{"id":"undef","name":"undef","text":"TestRunningFlowTemplate","type":"undef"}');
  await MK.onClick(pageDetails3.aBdsK5Zfrr9Field, 16, 'before', `Instance Name`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"div.MuiTabs-list.MuiTabs-flexContainer.css-17do188>button.MuiButtonBase-root.MuiTab-root.MuiTab-labelIcon.MuiTab-textColorPrimary.MuiTab-fullWidth.Mui-selected.css-p4gvcn\",\"index\":0},{\"selector\":\"div>button\",\"index\":15},{\"selector\":\"BUTTON[type=\'button\'][role=\'tab\'][id=\'mui-p-7332-T-flow-variables\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][@role=\'tab\'][normalize-space() = \\"Variables\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Variables","searchType":"text","text":"undef"}', '{"id":"mui-p-7332-T-flow-variables","name":"undef","text":"Variables","type":"button"}');
  await MK.onClick(pageDetails4.button1Atqk7S2A3Field, 17, 'before', `Variables`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"form.flex.flex-col.gap-2.h-full.w-full.gap-6>div.instance_field.bg-white.shadow.rounded-lg.focus-within:border-2.focus-within:border-primary-70.flex.flex-col.p-4.gap-4\",\"index\":0},{\"selector\":\"form>div\",\"index\":0},{\"selector\":\"DIV\",\"index\":101},{\"selector\":\"//DIV[normalize-space() = \\"Flow Instance Name *Required​\\"]\",\"index\":1}]', 3, 'div', '', 'mouseover', '{"value":"Flow Instance Name *Required​","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Instance Name *Required​","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails4.divG5Sejvh3D4Field, 18, 'after', `Flow Instance Name *Required​`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"div.flex.items-center.justify-between>button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.css-rdhv34\",\"index\":0},{\"selector\":\"div>button\",\"index\":18},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":16},{\"selector\":\"//button[@aria-label=\\"Copy information\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"button"}');
  await MK.onClick(pageDetails4.button7DIxqPUgmField, 20, 'before', `Copy information`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarAppba25432f_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
