
/*
* Generated by MuukTest
* Test Case ID: TC85093
* Description: Confirm columns organizer is searchable
* Generated: 2026-09-11T04:59:35.377Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavgdgn1vrnzb8i,  dashboardStagingNavgsc2nzmxtl6i,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarApp3841784e.log';
const muukReport = new MuukReport('dashboardStagingNavgarApp3841784e');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarApp3841784e',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarApp3841784e', muukReport);
  MK.setVideoTracker(200);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavgdgn1vrnzb8i();
	const pageDetails3 = new dashboardStagingNavgsc2nzmxtl6i();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm>span.text-xs.whitespace-break-spaces.w-fit.text-center.text-primary-10.font-bold\",\"index\":0},{\"selector\":\"li>span\",\"index\":5},{\"selector\":\"SPAN\",\"index\":23},{\"selector\":\"//SPAN[normalize-space() = \\"Running Flows\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Running Flows","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Running Flows","type":"undef"}');
  await MK.onClick(pageDetails2.spanNBH4dJhX1Field, 14, 'before', `Running Flows`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"div.MuiBox-root.css-3eqgl8>h6.MuiTypography-root.MuiTypography-subtitle1.css-bwj3c4\",\"index\":0},{\"selector\":\"div>h6\",\"index\":0},{\"selector\":\"H6\",\"index\":0},{\"selector\":\"//h6[normalize-space() = \'Running Flows\']\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Running Flows","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails3.h6MKsWgxI4nField, 15, 'after', `Running Flows - header`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"div.MuiDataGrid-toolbar.MuiDataGrid-toolbarContainer.css-1219n4p>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.css-1fbl5f9\",\"index\":0},{\"selector\":\"div>button\",\"index\":7},{\"selector\":\"BUTTON[type=\'button\'][id=\':r46l:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Columns\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Columns","searchType":"text","text":"undef"}', '{"id":":r46l:","name":"undef","text":"Columns","type":"button"}');
  await MK.onClick(pageDetails2.buttonoZCG2bcW3gField, 16, 'before', `Columns`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 17, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.span7MT733H1WAField, 17, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 18, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spanYmiG2yuARWField, 18, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 19, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spanP7ULwGfD0Field, 19, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 20, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spanY7hzGatYzDField, 20, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 21, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spang3UAkbIn98Field, 21, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 22, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.span73uoAOiZoyField, 22, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 23, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spanbOtjWaTK6jField, 23, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 24, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spandXH02H8AField, 24, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 25, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spanXeT5o7U44Field, 25, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 26, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spanZOh7O9sYg1Field, 26, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 27, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.css-k9qqt8>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputTypeSearch.MuiInputBase-inputSizeSmall.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-1cludd7\",\"index\":0},{\"selector\":\"div>input\",\"index\":6},{\"selector\":\"INPUT[placeholder=\'Search\'][type=\'search\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r4dd:\'][@placeholder=\'Search\'][@type=\'search\']\",\"index\":0}]', 2, 'input', 'search', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r4dd:","name":"undef","text":"undef","type":"search"}');
  
  
  await MK.onAssignment(pageDetails2.input4duN8DfBR7Field, 27, 'after', `Progress`, 'search', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 28, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.span7MT733H1WAField, 28, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 29, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spanYmiG2yuARWField, 29, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 30, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spanP7ULwGfD0Field, 30, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 31, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spanY7hzGatYzDField, 31, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 32, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spang3UAkbIn98Field, 32, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 33, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.span73uoAOiZoyField, 33, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 34, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spanbOtjWaTK6jField, 34, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 35, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spandXH02H8AField, 35, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 36, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spanXeT5o7U44Field, 36, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 37, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.spanZOh7O9sYg1Field, 37, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarApp3841784e_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
