
/*
* Generated by MuukTest
* Test Case ID: TC62642
* Description: Expand and contract a projects details
* Generated: 2026-08-25T18:43:04.335Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavg8zknx3pwmq,  dashboardStagingNavgsvgjf9u9ic6c,  dashboardStagingNavgmplpa9pgfa1s,  dashboardStagingNavgz7snpgzx4j9,  dashboardStagingNavggkkunmz2eab4,  dashboardStagingNavgxbjq67s8dieo,  dashboardStagingNavguvl2nbhuceg,  dashboardStagingNavgih9c0gh020t,  dashboardStagingNavgmvgrarla3quv,  dashboardStagingNavgs0l2cigdpfs3,  dashboardStagingNavgrg2gimj88mcg,  dashboardStagingNavgbu2835wca43,  dashboardStagingNavgsi6c4i615ygw,  dashboardStagingNavghjd1d4fgnkm,  dashboardStagingNavgjavnn8xjum,  dashboardStagingNavgwnry5jsnivb,  dashboardStagingNavgijb9s2r7b6md,  itWikipediaOrgelwvcigco5sl,  dashboardStagingNavgius0qrnmfld,  dashboardStagingNavgysemqxais74,  dashboardStagingNavgkvacgcgttzh,  w3schoolsComafj2me66hboa,  w3schoolsComx3k8k9hatrta,  dashboardStagingNavgh7ywfwqsmdx,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarApp111c1e5f.log';
const muukReport = new MuukReport('dashboardStagingNavgarApp111c1e5f');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarApp111c1e5f',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarApp111c1e5f', muukReport);
  MK.setVideoTracker(0);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavg8zknx3pwmq();
	const pageDetails3 = new dashboardStagingNavgsvgjf9u9ic6c();
	const pageDetails4 = new dashboardStagingNavgmplpa9pgfa1s();
	const pageDetails5 = new dashboardStagingNavgz7snpgzx4j9();
	const pageDetails6 = new dashboardStagingNavggkkunmz2eab4();
	const pageDetails7 = new dashboardStagingNavgxbjq67s8dieo();
	const pageDetails8 = new dashboardStagingNavguvl2nbhuceg();
	const pageDetails9 = new dashboardStagingNavgih9c0gh020t();
	const pageDetails10 = new dashboardStagingNavgmvgrarla3quv();
	const pageDetails11 = new dashboardStagingNavgs0l2cigdpfs3();
	const pageDetails12 = new dashboardStagingNavgrg2gimj88mcg();
	const pageDetails13 = new dashboardStagingNavgbu2835wca43();
	const pageDetails14 = new dashboardStagingNavgsi6c4i615ygw();
	const pageDetails15 = new dashboardStagingNavghjd1d4fgnkm();
	const pageDetails16 = new dashboardStagingNavgjavnn8xjum();
	const pageDetails17 = new dashboardStagingNavgwnry5jsnivb();
	const pageDetails18 = new dashboardStagingNavgijb9s2r7b6md();
	const pageDetails19 = new itWikipediaOrgelwvcigco5sl();
	const pageDetails20 = new dashboardStagingNavgius0qrnmfld();
	const pageDetails21 = new dashboardStagingNavgysemqxais74();
	const pageDetails22 = new dashboardStagingNavgkvacgcgttzh();
	const pageDetails23 = new w3schoolsComafj2me66hboa();
	const pageDetails24 = new w3schoolsComx3k8k9hatrta();
	const pageDetails25 = new dashboardStagingNavgh7ywfwqsmdx();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('sleep', 2, page.url());
  
  
  
  
  await MK.onSleep(2, 'after', 2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('setValueGV', 3, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 4, page.url(), '[{\"selector\":\"div.mb-4.text-center>h2.mb-px\",\"index\":0},{\"selector\":\"div>h2\",\"index\":0},{\"selector\":\"H2\",\"index\":0},{\"selector\":\"//a[contains(text(),\\"Log In\\")]\",\"index\":0}]', 3, 'h2', '', 'click', '{"value":"Log in","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Log in","type":"undef"}');
  await MK.onClick(pageDetails1.h2VKUvVlcxo9Field, 4, 'before', `Log in`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 5, page.url());
  
  
  
  
  await MK.onSleep(5, 'after', 1); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 6, page.url(), '[{\"selector\":\"div.form-group>input.form-control\",\"index\":0},{\"selector\":\"div>input\",\"index\":0},{\"selector\":\"INPUT[type=\'email\'][name=\'user[email]\'][id=\'user_email\']\",\"index\":0},{\"selector\":\"//INPUT[@type=\'email\'][@name=\'user[email]\'][@id=\'user_email\']\",\"index\":0}]', 2, 'input', 'email', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"user_email","name":"user[email]","text":"undef","type":"email"}');
  
  
  await MK.onAssignment(pageDetails1.inputaPC0oahLxOField, 6, 'after', `` + email + ``, 'email', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 7, page.url());
  
  
  
  
  await MK.onSleep(7, 'after', 1); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 8, page.url(), '[{\"selector\":\"div.form-group>input.form-control\",\"index\":1},{\"selector\":\"div>input\",\"index\":1},{\"selector\":\"INPUT[type=\'password\'][name=\'user[password]\'][id=\'user_password\']\",\"index\":0},{\"selector\":\"//INPUT[@type=\'password\'][@name=\'user[password]\'][@id=\'user_password\']\",\"index\":0}]', 2, 'input', 'password', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"user_password","name":"user[password]","text":"undef","type":"password"}');
  
  
  await MK.onAssignment(pageDetails1.inputNoTndoCpdqField, 8, 'after', `` + password + ``, 'password', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 9, page.url());
  
  
  
  
  await MK.onSleep(9, 'after', 1); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 10, page.url(), '[{\"selector\":\"div.form-group>input.btn.btn-primary.btn-expanded\",\"index\":0},{\"selector\":\"div>input\",\"index\":4},{\"selector\":\"INPUT[type=\'submit\'][name=\'commit\']\",\"index\":0},{\"selector\":\"//INPUT[@type=\'submit\'][@name=\'commit\']\",\"index\":0}]', 2, 'input', 'submit', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"commit","text":"undef","type":"submit"}');
  await MK.onClick(pageDetails1.inputPriEV9ualJField, 10, 'before', `Log in`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 12, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(12, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('step', 13, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-m3hfr4>span.text-xs.whitespace-break-spaces.w-fit.text-center\",\"index\":4},{\"selector\":\"li>span\",\"index\":4},{\"selector\":\"SPAN\",\"index\":19},{\"selector\":\"//SPAN[contains(text(),\\"Projects\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Projects","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Projects","type":"undef"}');
  await MK.onClick(pageDetails3.spanvRCaYwC8g4Field, 13, 'before', `Projects`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 14, page.url());
  
  
  
  
  
  
  
   console.log('step:14'); 
  logIndex = 14;
  const emptyState = page.locator('//div[normalize-space(text())="No rows"]');

try {
    // Wait briefly to see if the empty state appears
    await emptyState.waitFor({
        state: 'visible',
        timeout: 5000
    });

    snippetLog("El selector 'projects.emptyState' ya es visible. No es necesario realizar acciones.");

} catch {
    snippetLog("El selector 'projects.emptyState' no es visible. Realizando acciones...");

    // Click history button
    await page
        .locator('(//button[@aria-label="more"])[1]', {timeout: 10000})
        .click();

    // Click "Delete Project"
    await page
        .locator('//SPAN[contains(text(),"Delete Project")]')
        .click({timeout: 10000});

    // Click confirmation
    await page
        .locator('//BUTTON[@type="button"][normalize-space() = "Yes, delete it"]')
        .click({timeout: 10000});

    // Reload page
    await page.reload({ waitUntil: 'networkidle', timeout: 30000 });

    // Validate again
    try {
        await emptyState.waitFor({
            state: 'visible',
            timeout: 50000
        });

        snippetLog("El selector 'projects.emptyState' es visible después de las acciones.");

    } catch {
        snippetLog("El selector 'projects.emptyState' sigue sin ser visible después de las acciones.");
    }
}
   await MK.takeScreenshot(14); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"div.MuiStack-root.css-1gyjcoa>button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.css-bj6f2k\",\"index\":0},{\"selector\":\"div>button\",\"index\":4},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":4},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"New Project\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"New Project","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"New Project","type":"button"}');
  await MK.onClick(pageDetails2.buttonGgi4xgiYN5Field, 15, 'before', `New Project`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('setValueGV', 16, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.css-1jtlw65>input.MuiInputBase-input.MuiOutlinedInput-input.css-1pk1fka\",\"index\":0},{\"selector\":\"div>input\",\"index\":1},{\"selector\":\"INPUT[id=\':rj:\'][type=\'text\']\",\"index\":0},{\"selector\":\"//label[normalize-space()=\'Name\']/following::input[1]\",\"index\":0}]', 3, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":rj:","name":"undef","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails2.inputR9HZWoh5bField, 17, 'after', `Muuk Project` + randNum + ``, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 18, page.url());
  
  
  
  
  
  
  
   console.log('step:18'); 
  logIndex = 18;
  await page.keyboard.press('Enter'); 

   await MK.takeScreenshot(18); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"div.MuiPaper-root.MuiPaper-elevation.MuiPaper-rounded.MuiPaper-elevation0.MuiAlert-root.MuiAlert-colorSuccess.MuiAlert-standardSuccess.MuiAlert-standard.css-1uh9sau>div.MuiAlert-message.css-1xsto0d\",\"index\":0},{\"selector\":\"div>div\",\"index\":6},{\"selector\":\"DIV\",\"index\":7},{\"selector\":\"//DIV[contains(text(),\\"Your new project has been created succes\\")]\",\"index\":0}]', 3, 'div', '', 'mouseover', '{"value":"Your new project has been created successfully","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Your new project has been created successfully","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails4.divGJhlwghmWkField, 20, 'after', `Your new project has been created successfully`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 22, page.url(), '[{\"selector\":\"div.MuiTabs-flexContainer.css-1902i5q>button.MuiButtonBase-root.MuiTab-root.MuiTab-textColorPrimary.MuiTab-fullWidth.Mui-selected.css-v1e7gc\",\"index\":0},{\"selector\":\"div>button\",\"index\":12},{\"selector\":\"BUTTON[type=\'button\'][role=\'tab\'][id=\'mui-p-89812-T-project-basic-information\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][@role=\'tab\'][normalize-space() = \\"Overview\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Overview","searchType":"text","text":"undef"}', '{"id":"mui-p-89812-T-project-basic-information","name":"undef","text":"Overview","type":"button"}');
  await MK.onClick(pageDetails20.button1GFYBf3xField, 22, 'before', `Overview`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 23, page.url());
  
  
  
  
  
  
  
   console.log('step:23'); 
  logIndex = 23;
  await page.keyboard.press('Escape');
   await MK.takeScreenshot(23); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 24, page.url(), '[{\"selector\":\"div.flex.items-center.gap-4>span.text-md.font-bold.text-ellipsis.overflow-hidden\",\"index\":0},{\"selector\":\"div>span\",\"index\":13},{\"selector\":\"SPAN\",\"index\":33},{\"selector\":\"//h6[contains(text(),\\"Muuk Project\\")]\",\"index\":0}]', 3, 'span', '', 'mouseover', '{"value":"Muuk Project","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Muuk Project","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails2.span0jToXsBb2Field, 24, 'after', `Muuk Project`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 25, page.url(), '[{\"selector\":\"div.MuiTabs-list.MuiTabs-flexContainer.css-17do188>button.MuiButtonBase-root.MuiTab-root.MuiTab-textColorPrimary.MuiTab-fullWidth.css-1ejwzeh\",\"index\":1},{\"selector\":\"div>button\",\"index\":5},{\"selector\":\"BUTTON[type=\'button\'][role=\'tab\'][id=\'mui-p-57148-T-project-tasks\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][@role=\'tab\'][normalize-space() = \\"Tasks\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Tasks","searchType":"text","text":"undef"}', '{"id":"mui-p-57148-T-project-tasks","name":"undef","text":"Tasks","type":"button"}');
  await MK.onClick(pageDetails25.buttonxocaVHZZPField, 25, 'before', `Tasks`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 26, page.url(), '[{\"selector\":\"div.MuiDataGrid-columnHeaderDraggableContainer>div.MuiDataGrid-columnHeaderTitleContainer\",\"index\":1},{\"selector\":\"div>div\",\"index\":116},{\"selector\":\"DIV[role=\'presentation\']\",\"index\":8},{\"selector\":\"//DIV[@role=\'presentation\'][normalize-space() = \\"Task Name\\"]\",\"index\":1}]', 3, 'div', '', 'mouseover', '{"value":"Task Name","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Task Name","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails2.dive1tveYH9jrField, 26, 'after', `Task Name`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 27, page.url(), '[{\"selector\":\"div.MuiDataGrid-columnHeaderDraggableContainer>div.MuiDataGrid-columnHeaderTitleContainer\",\"index\":2},{\"selector\":\"div>div\",\"index\":124},{\"selector\":\"DIV[role=\'presentation\']\",\"index\":11},{\"selector\":\"//div[contains(text(), \\"Code\\")]\",\"index\":0}]', 3, 'div', '', 'mouseover', '{"value":"code","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"code","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails2.divVdT8O2Fwg7Field, 27, 'after', `code`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 28, page.url(), '[{\"selector\":\"div.MuiDataGrid-columnHeaderDraggableContainer>div.MuiDataGrid-columnHeaderTitleContainer\",\"index\":4},{\"selector\":\"div>div\",\"index\":138},{\"selector\":\"DIV[role=\'presentation\']\",\"index\":15},{\"selector\":\"//DIV[@role=\'presentation\'][normalize-space() = \\"Due Date\\"]\",\"index\":1}]', 3, 'div', '', 'mouseover', '{"value":"Due Date","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Due Date","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails2.divBLC2NoFDLvField, 28, 'after', `Due Date`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 29, page.url(), '[{\"selector\":\"div.MuiDataGrid-columnHeaderDraggableContainer>div.MuiDataGrid-columnHeaderTitleContainer\",\"index\":6},{\"selector\":\"div>div\",\"index\":152},{\"selector\":\"DIV[role=\'presentation\']\",\"index\":19},{\"selector\":\"//DIV[@role=\'presentation\'][normalize-space() = \\"Owner\\"]\",\"index\":1}]', 3, 'div', '', 'mouseover', '{"value":"Owner","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Owner","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails2.div0MuO2xFYWField, 29, 'after', `Owner`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 30, page.url(), '[{\"selector\":\"div.MuiDataGrid-columnHeaderDraggableContainer>div.MuiDataGrid-columnHeaderTitleContainer\",\"index\":8},{\"selector\":\"div>div\",\"index\":167},{\"selector\":\"DIV[role=\'presentation\']\",\"index\":24},{\"selector\":\"//DIV[@role=\'presentation\'][normalize-space() = \\"Alerts\\"]\",\"index\":1}]', 3, 'div', '', 'mouseover', '{"value":"Actions","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Actions","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails2.div1BUokkcbaField, 30, 'after', `Actions`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 31, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-m3hfr4>span.text-xs.whitespace-break-spaces.w-fit.text-center\",\"index\":4},{\"selector\":\"li>span\",\"index\":4},{\"selector\":\"SPAN\",\"index\":19},{\"selector\":\"//SPAN[contains(text(),\\"Projects\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Projects","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Projects","type":"undef"}');
  await MK.onClick(pageDetails3.spanvRCaYwC8g4Field, 31, 'before', `Projects`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 32, page.url(), '[{\"selector\":\"div.flex.items-center.justify-end.gap-4>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.w-fit.whitespace-nowrap.rounded-3xl.py-1.px-2.mt-1.text-sm.css-xbucmq\",\"index\":1},{\"selector\":\"div>button\",\"index\":6},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":6},{\"selector\":\"(//button[@aria-label=\\"more\\"])[1]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"button"}');
  await MK.onClick(pageDetails11.buttonPrHrA8sZXpField, 32, 'before', `3 DOTS`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 33, page.url(), '[{\"selector\":\"li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters.css-1qyfo9m>span.text-xs.pr-3.pl-2.text-danger-800\",\"index\":0},{\"selector\":\"li>span\",\"index\":13},{\"selector\":\"SPAN\",\"index\":51},{\"selector\":\"//SPAN[contains(text(),\\"Delete Project\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Delete Project","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Delete Project","type":"undef"}');
  await MK.onClick(pageDetails11.spanLqsK6rtPBField, 33, 'before', `Delete Project`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 34, page.url(), '[{\"selector\":\"div.bg-white.shadow-md.rounded-.overflow-auto.scrollbar-hide.relative.flex.flex-col.justify-start.rounded-2xl.w-fit.h-fit.MuiBox-root.css-0>div.p-6.overflow-auto.scrollbar-hide\",\"index\":0},{\"selector\":\"div>div\",\"index\":107},{\"selector\":\"DIV\",\"index\":134},{\"selector\":\"//p[contains(text(), \\"Are you sure you want to delete the project\\")]\",\"index\":0}]', 3, 'div', '', 'mouseover', '{"value":"Are you sure you want to delete the project \\\"Muuk Project\\\"? The remaining tasks in this project wont be deleted","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Are you sure you want to delete the project \\\"Muuk Project\\\"? The remaining tasks in this project won\'t be deleted","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails11.div1juYdS61Field, 34, 'after', `Are you sure you want to delete the project \"Muuk Project\"? The remaining tasks in this project won\'t be deleted`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 35, page.url(), '[{\"selector\":\"div.p-4.border-t.border-neutral-90.flex.justify-end.gap-2>button.MuiButtonBase-root.MuiButton-root.MuiLoadingButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiLoadingButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.css-1e2zdr8\",\"index\":0},{\"selector\":\"div>button\",\"index\":10},{\"selector\":\"BUTTON[type=\'button\'][id=\':r74:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Yes, delete it\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Yes, delete it","searchType":"text","text":"undef"}', '{"id":":r74:","name":"undef","text":"Yes, delete it","type":"button"}');
  await MK.onClick(pageDetails11.buttonGGCdRMFljNField, 35, 'before', `Yes, delete it`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 36, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails11.spanjLirZ3U7QWField, 36, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarApp111c1e5f_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
