
/*
* Generated by MuukTest
* Test Case ID: TC_A84086
* Description: Confirm Switch button sets account as active
* Generated: 2026-08-25T18:50:02.647Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavgkfsq0sqyxlg,  dashboardStagingNavgvjr1scz3vz9l,  dashboardStagingNavgdm2hlm5bgbh,  dashboardStagingNavgs2xobrrm80o6,  dashboardStagingNavgp0y1vwxva1e8,  dashboardStagingNavgeh7wsg0a2ub,  dashboardStagingNavgupzppbviuhmp,  dashboardStagingNavgkoyr3hqnctqq,  dashboardStagingNavguciflemiatuk,  dashboardStagingNavgkat21kg28a4,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarAppa4f91fb8.log';
const muukReport = new MuukReport('dashboardStagingNavgarAppa4f91fb8');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarAppa4f91fb8',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarAppa4f91fb8', muukReport);
  MK.setVideoTracker(0);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavgkfsq0sqyxlg();
	const pageDetails3 = new dashboardStagingNavgvjr1scz3vz9l();
	const pageDetails4 = new dashboardStagingNavgdm2hlm5bgbh();
	const pageDetails5 = new dashboardStagingNavgs2xobrrm80o6();
	const pageDetails6 = new dashboardStagingNavgp0y1vwxva1e8();
	const pageDetails7 = new dashboardStagingNavgeh7wsg0a2ub();
	const pageDetails8 = new dashboardStagingNavgupzppbviuhmp();
	const pageDetails9 = new dashboardStagingNavgkoyr3hqnctqq();
	const pageDetails10 = new dashboardStagingNavguciflemiatuk();
	const pageDetails11 = new dashboardStagingNavgkat21kg28a4();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('sleep', 2, page.url());
  
  
  
  
  await MK.onSleep(2, 'after', 2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('setValueGV', 3, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 4, page.url(), '[{\"selector\":\"div.mb-4.text-center>h2.mb-px\",\"index\":0},{\"selector\":\"div>h2\",\"index\":0},{\"selector\":\"H2\",\"index\":0},{\"selector\":\"//a[contains(text(),\\"Log In\\")]\",\"index\":0}]', 3, 'h2', '', 'click', '{"value":"Log in","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Log in","type":"undef"}');
  await MK.onClick(pageDetails1.h2VKUvVlcxo9Field, 4, 'before', `Log in`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 5, page.url());
  
  
  
  
  await MK.onSleep(5, 'after', 1); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 6, page.url(), '[{\"selector\":\"div.form-group>input.form-control\",\"index\":0},{\"selector\":\"div>input\",\"index\":0},{\"selector\":\"INPUT[type=\'email\'][name=\'user[email]\'][id=\'user_email\']\",\"index\":0},{\"selector\":\"//INPUT[@type=\'email\'][@name=\'user[email]\'][@id=\'user_email\']\",\"index\":0}]', 2, 'input', 'email', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"user_email","name":"user[email]","text":"undef","type":"email"}');
  
  
  await MK.onAssignment(pageDetails1.inputaPC0oahLxOField, 6, 'after', `` + email + ``, 'email', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 7, page.url());
  
  
  
  
  await MK.onSleep(7, 'after', 1); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 8, page.url(), '[{\"selector\":\"div.form-group>input.form-control\",\"index\":1},{\"selector\":\"div>input\",\"index\":1},{\"selector\":\"INPUT[type=\'password\'][name=\'user[password]\'][id=\'user_password\']\",\"index\":0},{\"selector\":\"//INPUT[@type=\'password\'][@name=\'user[password]\'][@id=\'user_password\']\",\"index\":0}]', 2, 'input', 'password', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"user_password","name":"user[password]","text":"undef","type":"password"}');
  
  
  await MK.onAssignment(pageDetails1.inputNoTndoCpdqField, 8, 'after', `` + password + ``, 'password', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 9, page.url());
  
  
  
  
  await MK.onSleep(9, 'after', 1); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 10, page.url(), '[{\"selector\":\"div.form-group>input.btn.btn-primary.btn-expanded\",\"index\":0},{\"selector\":\"div>input\",\"index\":4},{\"selector\":\"INPUT[type=\'submit\'][name=\'commit\']\",\"index\":0},{\"selector\":\"//INPUT[@type=\'submit\'][@name=\'commit\']\",\"index\":0}]', 2, 'input', 'submit', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"commit","text":"undef","type":"submit"}');
  await MK.onClick(pageDetails1.inputPriEV9ualJField, 10, 'before', `Log in`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 12, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(12, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('step', 13, page.url(), '[{\"selector\":\"div.inline-block.select-none>span.flex.items-center.text-gray-700.appearance-none\",\"index\":0},{\"selector\":\"div>span\",\"index\":9},{\"selector\":\"SPAN\",\"index\":37},{\"selector\":\"//div[@role=\\"button\\"][@aria-label=\\"Profile Menu\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails8.spandBsGveI6J1Field, 13, 'before', `Profile button`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"div.overflow-hidden.bg-white.border.border-gray-200.rounded.shadow-md>a.no-underline.block.px-6.py-3.text-gray-800.bg-white.hover:bg-primary-50.transition.ease-in-out.duration-200.whitespace-nowrap\",\"index\":0},{\"selector\":\"div>a\",\"index\":9},{\"selector\":\"A\",\"index\":9},{\"selector\":\"//A[normalize-space() = \\"Accounts\\"]\",\"index\":1}]', 3, 'a', '', 'click', '{"value":"/accounts","searchType":"href","text":"Accounts"}', '{"id":"undef","name":"undef","text":"Accounts","type":"undef"}');
  await MK.onClick(pageDetails8.a0DFVpQilnbField, 14, 'before', `Accounts`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 15, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.h190uQpSB1mField, 15, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"td.hidden.sm:table-cell.text-sm.text-center>a.btn.btn-white\",\"index\":0},{\"selector\":\"td>a\",\"index\":1},{\"selector\":\"A\",\"index\":24},{\"selector\":\"//tr[.//span[contains(text(), \'MuukTest - Feature Flag Environment\')]]//a[@label=\'Switch\']\",\"index\":0}]', 3, 'a', '', 'click', '{"value":"https://dashboard.staging.navgar.app/105/accounts/","searchType":"href","text":"Switch"}', '{"id":"undef","name":"undef","text":"Switch","type":"undef"}');
  await MK.onClick(pageDetails2.amOUgGJtA6Field, 16, 'before', `Switch`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 17, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.divMNIPe7sX5DField, 17, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 18, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails2.amOUgGJtA6Field, 18, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarAppa4f91fb8_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
