
/*
* Generated by MuukTest
* Test Case ID: TC64593
* Description: Filters change depending on the category selected 
* Generated: 2026-09-11T05:15:51.022Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavg8mqlmcoxvr5,  dashboardStagingNavgvg07xcaki6n,  dashboardStagingNavg8vs84fttrzne,  dashboardStagingNavgsvgjf9u9ic6c,  deWikipediaOrgkjomqby699kg,  dashboardStagingNavgndk0qdypi4rh,  demoqaComlxqts6h6xsgx,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarApp5a75e161.log';
const muukReport = new MuukReport('dashboardStagingNavgarApp5a75e161');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarApp5a75e161',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarApp5a75e161', muukReport);
  MK.setVideoTracker(0);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavg8mqlmcoxvr5();
	const pageDetails3 = new dashboardStagingNavgvg07xcaki6n();
	const pageDetails4 = new dashboardStagingNavg8vs84fttrzne();
	const pageDetails5 = new dashboardStagingNavgsvgjf9u9ic6c();
	const pageDetails6 = new deWikipediaOrgkjomqby699kg();
	const pageDetails7 = new dashboardStagingNavgndk0qdypi4rh();
	const pageDetails8 = new demoqaComlxqts6h6xsgx();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardDown', 14, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
   await MK.onKeyboardDown(14, 'after', `Alt`, 60000); 
  
  await muukReport.addStepInfo('keyboardpress', 15, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(15, 'after', `K`, 60000); 
  
  
  
  await muukReport.addStepInfo('keyboardUp', 16, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
   await MK.onKeyboardUp(16, 'after', `Alt`, 60000); 
  await muukReport.addStepInfo('keyboardType', 17, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
   await MK.onKeyboardType(17, 'after', `Test`, 60000); 
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"div.flex.gap-2.overflow-auto.scrollbar-hide.px-4>button.border-secondary-80.border.px-3.order-2.h-fit.text-neutral-30.hover:bg-primary-95.font-normal.text-neutral-40.cursor-pointer.flex.gap-2.whitespace-nowrap.items-center.justify-center.rounded-md.leading-5.py-1.false\",\"index\":0},{\"selector\":\"div>button\",\"index\":4},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":4},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Tasks\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Tasks","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Tasks","type":"button"}');
  await MK.onClick(pageDetails7.buttonPxu7LVTAovField, 18, 'before', `Tasks`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 19, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails8.buttonynIKeXF3o4Field, 19, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 20, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails8.buttonpWc1A5ukROField, 20, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 21, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails8.buttonKKU2M8svJBField, 21, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 22, page.url(), '[{\"selector\":\"div.flex.gap-2.overflow-auto.scrollbar-hide.px-4>button.border-secondary-80.border.px-3.order-2.h-fit.text-neutral-30.hover:bg-primary-95.font-normal.text-neutral-40.cursor-pointer.flex.gap-2.whitespace-nowrap.items-center.justify-center.rounded-md.leading-5.py-1.false\",\"index\":0},{\"selector\":\"div>button\",\"index\":5},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":5},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Running flows\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Running flows","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Running flows","type":"button"}');
  await MK.onClick(pageDetails7.button23s3buV6QField, 22, 'before', `Running Flows`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 23, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails8.buttonpWc1A5ukROField, 23, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 24, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails8.buttonynIKeXF3o4Field, 24, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 25, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails8.buttonKKU2M8svJBField, 25, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 26, page.url(), '[{\"selector\":\"div.flex.gap-2.overflow-auto.scrollbar-hide.px-4>button.border-secondary-80.border.px-3.order-2.h-fit.text-neutral-30.hover:bg-primary-95.font-normal.text-neutral-40.cursor-pointer.flex.gap-2.whitespace-nowrap.items-center.justify-center.rounded-md.leading-5.py-1.false\",\"index\":0},{\"selector\":\"div>button\",\"index\":6},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":6},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Groups\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Groups","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Groups","type":"button"}');
  await MK.onClick(pageDetails7.buttonB8tz8sxWBField, 26, 'before', `Groups`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 27, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails8.buttonKKU2M8svJBField, 27, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 28, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails8.buttonpWc1A5ukROField, 28, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 29, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails8.buttonynIKeXF3o4Field, 29, 'after', 'notVisible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarApp5a75e161_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
