
/*
* Generated by MuukTest
* Test Case ID: TC64032
* Description: Test functionality of the module button sidebar
* Generated: 2026-09-11T05:15:28.224Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavgxbd4woeujd2i,  dashboardStagingNavg8mqlmcoxvr5,  dashboardStagingNavgsvgjf9u9ic6c,  dashboardStagingNavg500ungjzym7e,  dashboardStagingNavgsc2nzmxtl6i,  dashboardStagingNavg8zknx3pwmq,  dashboardStagingNavggwnh7lkg1kl,  dashboardStagingNavgwnry5jsnivb,  dashboardStagingNavg90djub1wboef,  dashboardStagingNavgoy1kmmmd2m,  dashboardStagingNavgj19joroqlg5n,  dashboardStagingNavgdm2hlm5bgbh,  helpNavgarCom77a01lk2p32l,  navgarComqb3jsinpfu,  navgarComur4oay2d1yog,  dashboardStagingNavg23ukecibpwgt,  dashboardStagingNavgoqflzk1fgxo,  dashboardStagingNavgl7n3b1miy3j,  helpNavgarComydlpwqy3m6,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarAppeb94463e.log';
const muukReport = new MuukReport('dashboardStagingNavgarAppeb94463e');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarAppeb94463e',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarAppeb94463e', muukReport);
  MK.setVideoTracker(0);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavgxbd4woeujd2i();
	const pageDetails3 = new dashboardStagingNavg8mqlmcoxvr5();
	const pageDetails4 = new dashboardStagingNavgsvgjf9u9ic6c();
	const pageDetails5 = new dashboardStagingNavg500ungjzym7e();
	const pageDetails6 = new dashboardStagingNavgsc2nzmxtl6i();
	const pageDetails7 = new dashboardStagingNavg8zknx3pwmq();
	const pageDetails8 = new dashboardStagingNavggwnh7lkg1kl();
	const pageDetails9 = new dashboardStagingNavgwnry5jsnivb();
	const pageDetails10 = new dashboardStagingNavg90djub1wboef();
	const pageDetails11 = new dashboardStagingNavgoy1kmmmd2m();
	const pageDetails12 = new dashboardStagingNavgj19joroqlg5n();
	const pageDetails13 = new dashboardStagingNavgdm2hlm5bgbh();
	const pageDetails14 = new helpNavgarCom77a01lk2p32l();
	const pageDetails15 = new navgarComqb3jsinpfu();
	const pageDetails16 = new navgarComur4oay2d1yog();
	const pageDetails17 = new dashboardStagingNavg23ukecibpwgt();
	const pageDetails18 = new dashboardStagingNavgoqflzk1fgxo();
	const pageDetails19 = new dashboardStagingNavgl7n3b1miy3j();
	const pageDetails20 = new helpNavgarComydlpwqy3m6();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm>span.text-xs.whitespace-break-spaces.w-fit.text-center\",\"index\":0},{\"selector\":\"li>span\",\"index\":0},{\"selector\":\"SPAN\",\"index\":3},{\"selector\":\"//SPAN[contains(text(),\\"Messages\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Messages","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Messages","type":"undef"}');
  await MK.onClick(pageDetails4.spanD6s4p6SrnNField, 14, 'before', `Messages`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"li.MuiBreadcrumbs-li>h6.MuiTypography-root.MuiTypography-subtitle1.css-qzd3up\",\"index\":1},{\"selector\":\"li>h6\",\"index\":1},{\"selector\":\"H6\",\"index\":2},{\"selector\":\"//h6[contains(text(), \\"All Messages\\")]\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"All Messages","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails4.h6K5SaLkF10xField, 15, 'after', `All messages`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm>span.text-xs.whitespace-break-spaces.w-fit.text-center\",\"index\":1},{\"selector\":\"li>span\",\"index\":1},{\"selector\":\"SPAN\",\"index\":7},{\"selector\":\"//SPAN[contains(text(),\\"Tasks\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Tasks","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Tasks","type":"undef"}');
  await MK.onClick(pageDetails4.spanw5Uw1KIEMRField, 16, 'before', `Tasks`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"div.w-fit>h6.MuiTypography-root.MuiTypography-subtitle1.css-qzd3up\",\"index\":0},{\"selector\":\"div>h6\",\"index\":0},{\"selector\":\"H6\",\"index\":0},{\"selector\":\"//h6[contains(text(), \\"Inbox\\")]\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Inbox","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails3.h6DkFWdWsPE4Field, 17, 'after', `Inbox`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm>span.text-xs.whitespace-break-spaces.w-fit.text-center\",\"index\":2},{\"selector\":\"li>span\",\"index\":2},{\"selector\":\"SPAN\",\"index\":11},{\"selector\":\"//SPAN[contains(text(),\\"Flow Templates\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Flow Templates","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Templates","type":"undef"}');
  await MK.onClick(pageDetails3.spanj7fgo7UnMMField, 18, 'before', `Flow Templates`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 19, page.url(), '[{\"selector\":\"div.w-fit>h6.MuiTypography-root.MuiTypography-subtitle1.css-qzd3up\",\"index\":0},{\"selector\":\"div>h6\",\"index\":0},{\"selector\":\"H6\",\"index\":0},{\"selector\":\"//h6[contains(text(), \\"Flow Templates\\")]\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Flow Templates","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails5.h60XC4zLtlEField, 19, 'after', `Flow templates`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"div.flex.flex-col.gap-2.h-full>button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.py-2.px-4.flex.justify-start.css-1wvg4b\",\"index\":0},{\"selector\":\"div>button\",\"index\":1},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":1},{\"selector\":\"//button[contains(text(), \\"New Flow Group\\")]\",\"index\":0}]', 3, 'button', 'button', 'mouseover', '{"value":"+ Create Flow Group","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"+ Create Flow Group","type":"button"}');
  
  
  
  await MK.onMouseover(pageDetails5.button5rcVmsNZBField, 20, 'after', `Create flow group`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 21, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm>span.text-xs.whitespace-break-spaces.w-fit.text-center\",\"index\":3},{\"selector\":\"li>span\",\"index\":3},{\"selector\":\"SPAN\",\"index\":15},{\"selector\":\"//SPAN[contains(text(),\\"Running Flows\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Running Flows","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Running Flows","type":"undef"}');
  await MK.onClick(pageDetails5.spanvpuqbHjpVField, 21, 'before', `Running Flows`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 22, page.url(), '[{\"selector\":\"div.w-fit>h6.MuiTypography-root.MuiTypography-subtitle1.css-qzd3up\",\"index\":0},{\"selector\":\"div>h6\",\"index\":0},{\"selector\":\"H6\",\"index\":0},{\"selector\":\"//h6[contains(text(), \\"Running Flows\\")]\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Running Flows","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails6.h60oIP51HjGMField, 22, 'after', `Running Flows`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 23, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm>span.text-xs.whitespace-break-spaces.w-fit.text-center\",\"index\":4},{\"selector\":\"li>span\",\"index\":4},{\"selector\":\"SPAN\",\"index\":19},{\"selector\":\"//SPAN[contains(text(),\\"Projects\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Projects","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Projects","type":"undef"}');
  await MK.onClick(pageDetails6.spanZzH5v7FbNGField, 23, 'before', `Projects`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 24, page.url(), '[{\"selector\":\"div.MuiTabs-flexContainer.css-7sga7m>button.MuiButtonBase-root.MuiTab-root.MuiTab-textColorPrimary.Mui-selected.css-ivfzdy\",\"index\":0},{\"selector\":\"div>button\",\"index\":1},{\"selector\":\"BUTTON[type=\'button\'][role=\'tab\'][id=\'navgar-tab-active-projects\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"My projects\\"]\",\"index\":0}]', 3, 'button', 'button', 'mouseover', '{"value":"My projects","searchType":"text","text":"undef"}', '{"id":"navgar-tab-active-projects","name":"undef","text":"My projects","type":"button"}');
  
  
  
  await MK.onMouseover(pageDetails7.buttonvkhzJlI2bField, 24, 'after', `My projects`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarAppeb94463e_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
