
/*
* Generated by MuukTest
* Test Case ID: TC64521
* Description: Reminders Create Recurring reminder
* Generated: 2026-09-11T05:15:43.343Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   googleComw1zlr5y53vu,  dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavg8mqlmcoxvr5,  dashboardStagingNavg8zknx3pwmq,  dashboardStagingNavgsvgjf9u9ic6c,  dashboardStagingNavggnw70cgklbfr,  dashboardStagingNavg8tjcsnuzj3qe,  dashboardStagingNavg23ukecibpwgt,  dashboardStagingNavgoqflzk1fgxo,  dashboardStagingNavgl7n3b1miy3j,  dashboardStagingNavge1ynuou0dcop,  dashboardStagingNavgiu4m1aiovm79,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarApp29611c68.log';
const muukReport = new MuukReport('dashboardStagingNavgarApp29611c68');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarApp29611c68',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarApp29611c68', muukReport);
  MK.setVideoTracker(200);
	const pageDetails1 = new googleComw1zlr5y53vu();
	const pageDetails2 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails3 = new dashboardStagingNavg8mqlmcoxvr5();
	const pageDetails4 = new dashboardStagingNavg8zknx3pwmq();
	const pageDetails5 = new dashboardStagingNavgsvgjf9u9ic6c();
	const pageDetails6 = new dashboardStagingNavggnw70cgklbfr();
	const pageDetails7 = new dashboardStagingNavg8tjcsnuzj3qe();
	const pageDetails8 = new dashboardStagingNavg23ukecibpwgt();
	const pageDetails9 = new dashboardStagingNavgoqflzk1fgxo();
	const pageDetails10 = new dashboardStagingNavgl7n3b1miy3j();
	const pageDetails11 = new dashboardStagingNavge1ynuou0dcop();
	const pageDetails12 = new dashboardStagingNavgiu4m1aiovm79();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"svg.MuiSvgIcon-root.MuiSvgIcon-fontSizeMedium.text-primary-50.css-vubbuv>path\",\"index\":0},{\"selector\":\"svg>path\",\"index\":17},{\"selector\":\"path\",\"index\":18},{\"selector\":\"//button[.//span[contains(@class,\'MuiBadge-root\')]]\",\"index\":0}]', 3, 'path', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails8.path7ks7qXFx6Field, 14, 'after', `Reminders`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"svg.MuiSvgIcon-root.MuiSvgIcon-fontSizeMedium.text-primary-50.css-vubbuv>path\",\"index\":0},{\"selector\":\"svg>path\",\"index\":17},{\"selector\":\"path\",\"index\":18},{\"selector\":\"//button[.//span[contains(@class,\'MuiBadge-root\')]]\",\"index\":0}]', 3, 'path', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails8.path7ks7qXFx6Field, 15, 'before', `Reminders`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.css-1k66m85>input.MuiInputBase-input.MuiOutlinedInput-input.css-1x5jdmq\",\"index\":0},{\"selector\":\"div>input\",\"index\":3},{\"selector\":\"INPUT[name=\'content_plain\'][placeholder=\'Remind me about...\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':rj:\'][@name=\'content_plain\'][@placeholder=\'Remind me about...\'][@type=\'text\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":rj:","name":"content_plain","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails9.input70TRj6FN0BField, 16, 'after', `Reminder`, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"p.MuiTypography-root.MuiTypography-body1.flex.items-center.gap-1.capitalize.css-16qymjc>span.max-w-52.text-ellipsis.overflow-hidden\",\"index\":4},{\"selector\":\"p>span\",\"index\":4},{\"selector\":\"SPAN\",\"index\":53},{\"selector\":\"//SPAN[contains(text(),\\"Recurring\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Recurring","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Recurring","type":"undef"}');
  await MK.onClick(pageDetails9.spanj7IKOU626Field, 17, 'before', `Recurring`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"div.flex.gap-2.w-full.h-full.undefined>h6.MuiTypography-root.MuiTypography-h6.flex.items-center.gap-1.text-lg.leading-6.css-18dnnej\",\"index\":0},{\"selector\":\"div>h6\",\"index\":2},{\"selector\":\"H6\",\"index\":4},{\"selector\":\"//h6[contains(text(), \\"Recurring reminder\\")]\",\"index\":0}]', 3, 'h6', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Recurring reminder","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails9.h6vRTBmmhQQPField, 18, 'after', `Recurring reminder`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 19, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiRadio-root.MuiRadio-colorPrimary.PrivateSwitchBase-root.MuiRadio-root.MuiRadio-colorPrimary.MuiRadio-root.MuiRadio-colorPrimary.css-151zdcv>input.PrivateSwitchBase-input.css-j8yymo\",\"index\":0},{\"selector\":\"span>input\",\"index\":0},{\"selector\":\"INPUT[name=\'type\'][type=\'radio\']\",\"index\":0},{\"selector\":\"//input[@value=\\"weekly\\"]\",\"index\":0}]', 3, 'input', 'radio', 'click', '{"value":"weekly","searchType":"value","text":"undef"}', '{"id":"undef","name":"type","text":"undef","type":"radio"}');
  await MK.onClick(pageDetails9.inputBvSYdh0PBField, 19, 'before', `weekly`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"div.flex.items-center.gap-4>div.rounded-full.w-8.h-9.flex.items-center.justify-center.cursor-pointer.bg-neutral-80.hover:bg-neutral-70.text-neutral-20\",\"index\":0},{\"selector\":\"div>div\",\"index\":155},{\"selector\":\"DIV\",\"index\":204},{\"selector\":\"//DIV[normalize-space() = \\"M\\"]\",\"index\":0}]', 3, 'div', '', 'click', '{"value":"M","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"M","type":"undef"}');
  await MK.onClick(pageDetails9.divxaHooXIKvField, 20, 'before', `M`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 21, page.url(), '[{\"selector\":\"div.rounded-full.w-8.h-9.flex.items-center.justify-center.cursor-pointer.bg-neutral-80.hover:bg-neutral-70.text-neutral-20>span.text-sm\",\"index\":0},{\"selector\":\"div>span\",\"index\":13},{\"selector\":\"SPAN\",\"index\":66},{\"selector\":\"//SPAN[contains(text(),\\"W\\")]\",\"index\":1}]', 3, 'span', '', 'click', '{"value":"W","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"W","type":"undef"}');
  await MK.onClick(pageDetails9.spanX4cpytrngField, 21, 'before', `W`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 22, page.url(), '[{\"selector\":\"div.flex.items-center.gap-4>div.rounded-full.w-8.h-9.flex.items-center.justify-center.cursor-pointer.bg-neutral-80.hover:bg-neutral-70.text-neutral-20\",\"index\":0},{\"selector\":\"div>div\",\"index\":159},{\"selector\":\"DIV\",\"index\":208},{\"selector\":\"//DIV[normalize-space() = \\"F\\"]\",\"index\":0}]', 3, 'div', '', 'click', '{"value":"F","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"F","type":"undef"}');
  await MK.onClick(pageDetails9.divqBh6NiaO2Field, 22, 'before', `F`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 23, page.url(), '[{\"selector\":\"div.py-2.w-full>label.MuiFormLabel-root.MuiFormLabel-colorPrimary.css-17jq6nx\",\"index\":0},{\"selector\":\"div>label\",\"index\":5},{\"selector\":\"LABEL[id=\'time_config\']\",\"index\":0},{\"selector\":\"//LABEL[@id=\'time_config\'][contains(text(),\\"Choose a time for the launch\\")]\",\"index\":0}]', 3, 'label', '', 'mouseover', '{"value":"Choose a time for the launch","searchType":"text","text":"undef"}', '{"id":"time_config","name":"undef","text":"Choose a time for the launch","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails9.label6ginByHj08Field, 23, 'after', `Choose a time for the launch`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 24, page.url(), '[{\"selector\":\"ul.MuiList-root.MuiList-padding.MuiMenu-list.css-ubifyk>li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters.css-7ea6lj\",\"index\":2},{\"selector\":\"ul>li\",\"index\":15},{\"selector\":\"LI[role=\'option\']\",\"index\":0},{\"selector\":\"//div[@aria-labelledby=\\"time-selection time-selection\\"]\",\"index\":0}]', 3, 'li', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"00:00","type":"undef"}');
  await MK.onClick(pageDetails9.liaYCjB4TG4aField, 24, 'before', `Choose a time for the launch`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 25, page.url(), '[{\"selector\":\"div.MuiSelect-select.MuiSelect-outlined.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputSizeSmall.css-f3b8cd>div.MuiBox-root.css-1i27l4i\",\"index\":0},{\"selector\":\"div>div\",\"index\":166},{\"selector\":\"DIV\",\"index\":215},{\"selector\":\"//li[@data-value=\\"00:00\\"]\",\"index\":0}]', 3, 'div', '', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails9.divx5toMNSw8YField, 25, 'before', `00:00`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 26, page.url(), '[{\"selector\":\"div.p-4.border-t.border-neutral-90.flex.justify-end.gap-2>button.MuiButtonBase-root.MuiButton-root.MuiLoadingButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeLarge.MuiButton-containedSizeLarge.MuiButton-colorPrimary.MuiButton-root.MuiLoadingButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeLarge.MuiButton-containedSizeLarge.MuiButton-colorPrimary.rounded-3xl.css-hvmfs5\",\"index\":0},{\"selector\":\"div>button\",\"index\":17},{\"selector\":\"BUTTON[type=\'submit\'][id=\':r52:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'submit\'][contains(text(),\\"Add reminder\\")]\",\"index\":0}]', 3, 'button', 'submit', 'mouseover', '{"value":"Add reminder","searchType":"text","text":"undef"}', '{"id":":r52:","name":"undef","text":"Add reminder","type":"submit"}');
  
  
  
  await MK.onMouseover(pageDetails9.buttony7une3SA82Field, 26, 'after', `Add Reminders`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 27, page.url(), '[{\"selector\":\"div.p-4.border-t.border-neutral-90.flex.justify-end.gap-2>button.MuiButtonBase-root.MuiButton-root.MuiLoadingButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeLarge.MuiButton-containedSizeLarge.MuiButton-colorPrimary.MuiButton-root.MuiLoadingButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeLarge.MuiButton-containedSizeLarge.MuiButton-colorPrimary.rounded-3xl.css-hvmfs5\",\"index\":0},{\"selector\":\"div>button\",\"index\":17},{\"selector\":\"BUTTON[type=\'submit\'][id=\':r52:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'submit\'][contains(text(),\\"Add reminder\\")]\",\"index\":0}]', 3, 'button', 'submit', 'click', '{"value":"Add reminder","searchType":"text","text":"undef"}', '{"id":":r52:","name":"undef","text":"Add reminder","type":"submit"}');
  await MK.onClick(pageDetails9.buttony7une3SA82Field, 27, 'before', `Add Reminders`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 28, page.url(), '[{\"selector\":\"div.MuiPaper-root.MuiPaper-elevation.MuiPaper-rounded.MuiPaper-elevation0.MuiAlert-root.MuiAlert-colorSuccess.MuiAlert-standardSuccess.MuiAlert-standard.css-6rmxgy>div.MuiAlert-message.css-127h8j3\",\"index\":0},{\"selector\":\"div>div\",\"index\":6},{\"selector\":\"DIV\",\"index\":7},{\"selector\":\"//DIV[contains(text(),\\"Your reminder has been created successfu\\")]\",\"index\":0}]', 3, 'div', '', 'mouseover', '{"value":"Your reminder has been created successfully","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Your reminder has been created successfully","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails9.divY3SJJU4deField, 28, 'after', `Your reminder has been created successfully`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 29, page.url(), '[{\"selector\":\"button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.break-all.w-full.flex.justify-start.px-1.py-0.rounded-md.text-base.text-neutral-20.font-normal.text-left.hover:bg-secondary-90.css-1wvg4b>p\",\"index\":0},{\"selector\":\"button>p\",\"index\":7},{\"selector\":\"P\",\"index\":20},{\"selector\":\"//P[contains(text(),\\"Reminder\\")]\",\"index\":1}]', 3, 'p', '', 'mouseover', '{"value":"Reminder","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Reminder","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails9.pnmI2B7FRl4Field, 29, 'after', `Reminder`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 30, page.url(), '[{\"selector\":\"button.flex.items-center.border.rounded-lg.border-neutral-80.bg-white.px-2.gap-1>span.MuiTypography-root.MuiTypography-caption.whitespace-nowrap.font-bold.text-neutral-40.css-1p728zq\",\"index\":0},{\"selector\":\"button>span\",\"index\":14},{\"selector\":\"SPAN\",\"index\":55},{\"selector\":\"//SPAN[contains(text(),\\"Clear\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Clear","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Clear","type":"undef"}');
  await MK.onClick(pageDetails9.span8gi2N0Fpd4Field, 30, 'before', `Clear`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 31, page.url(), '[{\"selector\":\"div.MuiPaper-root.MuiPaper-elevation.MuiPaper-rounded.MuiPaper-elevation0.MuiAlert-root.MuiAlert-colorSuccess.MuiAlert-standardSuccess.MuiAlert-standard.css-6rmxgy>div.MuiAlert-message.css-127h8j3\",\"index\":0},{\"selector\":\"div>div\",\"index\":6},{\"selector\":\"DIV\",\"index\":7},{\"selector\":\"//DIV[contains(text(),\\"The reminder has been updated successful\\")]\",\"index\":0}]', 3, 'div', '', 'mouseover', '{"value":"The reminder has been updated successfully","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"The reminder has been updated successfully","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails9.divYJtllNCorMField, 31, 'after', `The reminder has been updated successfully`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarApp29611c68_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
