
/*
* Generated by MuukTest
* Test Case ID: TC64174
* Description: Main Command Bar Tasks can be created and assigned to users
* Generated: 2026-09-11T05:15:36.459Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavg8mqlmcoxvr5,  dashboardStagingNavgn9e8i02fzig,  dashboardStagingNavgsvgjf9u9ic6c,  dashboardStagingNavg500ungjzym7e,  dashboardStagingNavg8zknx3pwmq,  dashboardStagingNavg90djub1wboef,  dashboardStagingNavgoy1kmmmd2m,  dashboardStagingNavgj19joroqlg5n,  dashboardStagingNavgp5szekdzq1xf,  dashboardStagingNavgybvw8equak2q,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarAppc9a29393.log';
const muukReport = new MuukReport('dashboardStagingNavgarAppc9a29393');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarAppc9a29393',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarAppc9a29393', muukReport);
  MK.setVideoTracker(0);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavg8mqlmcoxvr5();
	const pageDetails3 = new dashboardStagingNavgn9e8i02fzig();
	const pageDetails4 = new dashboardStagingNavgsvgjf9u9ic6c();
	const pageDetails5 = new dashboardStagingNavg500ungjzym7e();
	const pageDetails6 = new dashboardStagingNavg8zknx3pwmq();
	const pageDetails7 = new dashboardStagingNavg90djub1wboef();
	const pageDetails8 = new dashboardStagingNavgoy1kmmmd2m();
	const pageDetails9 = new dashboardStagingNavgj19joroqlg5n();
	const pageDetails10 = new dashboardStagingNavgp5szekdzq1xf();
	const pageDetails11 = new dashboardStagingNavgybvw8equak2q();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-br3psm>span.text-xs.whitespace-break-spaces.w-fit.text-center\",\"index\":1},{\"selector\":\"li>span\",\"index\":1},{\"selector\":\"SPAN\",\"index\":7},{\"selector\":\"//SPAN[contains(text(),\\"Tasks\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Tasks","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Tasks","type":"undef"}');
  await MK.onClick(pageDetails2.span2oTGPrUp8VField, 14, 'before', `Tasks`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.rounded-2xl.bg-white.h-full.css-l4bcd9>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-fvgl9b\",\"index\":0},{\"selector\":\"div>input\",\"index\":6},{\"selector\":\"INPUT[id=\'command-bar-input\'][name=\'legend\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\'command-bar-input\'][@name=\'legend\'][@type=\'text\']\",\"index\":0}]', 2, 'input', 'text', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"command-bar-input","name":"legend","text":"undef","type":"text"}');
  
  
  
  await MK.onMouseover(pageDetails2.inputy9s7b6IgvGField, 15, 'after', `Task `, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 16, page.url());
  
  
  
  
  await MK.onSleep(16, 'after', 2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 17, page.url());
  
  
  
  
  
  
  
   console.log('step:17'); 
  logIndex = 17;
  // Selector for task rows in the grid
const taskSelector =
  '//div[@role="gridcell"][@data-field="legend"]/a/span[normalize-space() = "Task"]';
const emptyGridSelector = '//div[contains(text(),"No rows")]';

// Wait briefly for the grid to settle, then count matches
const taskLocator = page.locator(taskSelector);
let taskCount = 0;

try {
  await taskLocator.first().waitFor({ state: 'visible', timeout: 5000 });
  taskCount = await taskLocator.count();
} catch {
  taskCount = 0;
}

if (taskCount > 0) {
  snippetLog(`Found ${taskCount} task(s). Running delete actions...`);

  // Click the "Select Tasks" button
  await page.click('//button[contains(text(), "Select Tasks")]');
  //await page.waitForTimeout(2000);

  // Click the "select all" checkbox
  await page.click('//input[@name="select_all_rows"]');
  //await page.waitForTimeout(2000);

  // Open "More options"
  await page.click('//button[@id="more-menu"]');

  // Click the "Delete" option
  await page.click('//span[contains(text(), "Delete")]');

  // Confirm the dialog
  await page.keyboard.press('Enter');
  for (let i = 0; i < 3; i++) {
    await page.keyboard.press('Tab');
  }
  await page.keyboard.press('Enter');
} else {
  snippetLog('No tasks found. Nothing to delete.');
}

// Verify the grid is empty afterwards
const isGridEmpty = await page
  .locator(emptyGridSelector)
  .isVisible()
  .catch(() => false);

if (isGridEmpty) {
  snippetLog('Grid is empty after the actions.');
} else {
  snippetLog(`Grid still has ${await taskLocator.count()} task(s).`);
}
   await MK.takeScreenshot(17); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 18, page.url());
  
  
  
  
  await MK.onSleep(18, 'after', 2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 19, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.rounded-2xl.bg-white.h-full.css-l4bcd9>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputAdornedStart.MuiInputBase-inputAdornedEnd.css-fvgl9b\",\"index\":0},{\"selector\":\"div>input\",\"index\":6},{\"selector\":\"INPUT[id=\'command-bar-input\'][name=\'legend\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\'command-bar-input\'][@name=\'legend\'][@type=\'text\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"command-bar-input","name":"legend","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails2.inputy9s7b6IgvGField, 19, 'after', `Task @`, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 20, page.url());
  
  
  
  
  await MK.onSleep(20, 'after', 1); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 21, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiInputBase-colorPrimary.css-9y8mdg>input.MuiInputBase-input.css-aae3xl\",\"index\":0},{\"selector\":\"div>input\",\"index\":7},{\"selector\":\"INPUT[placeholder=\'Search\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@placeholder=\'Search\'][@type=\'text\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails2.inputomUr7bsEj0Field, 21, 'after', `victor`, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 22, page.url());
  
  
  
  
  
  
  
   console.log('step:22'); 
  logIndex = 22;
  await page.keyboard.press('Enter'); 

   await MK.takeScreenshot(22); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 23, page.url());
  
  
  
  
  await MK.onSleep(23, 'after', 2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 24, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.MuiInputBase-adornedStart.MuiInputBase-adornedEnd.rounded-2xl.bg-white.h-full.css-l4bcd9>button.MuiButtonBase-root.MuiButton-root.MuiLoadingButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeSmall.MuiButton-outlinedSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiLoadingButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeSmall.MuiButton-outlinedSizeSmall.MuiButton-colorPrimary.rounded-2xl.border-rad.css-12kixt\",\"index\":0},{\"selector\":\"div>button\",\"index\":13},{\"selector\":\"BUTTON[type=\'submit\'][id=\':r9l:\']\",\"index\":0},{\"selector\":\"//BUTTON[@type=\'submit\'][normalize-space() = \\"Add\\"]\",\"index\":0}]', 3, 'button', 'submit', 'click', '{"value":"Add","searchType":"text","text":"undef"}', '{"id":":r9l:","name":"undef","text":"Add","type":"submit"}');
  await MK.onClick(pageDetails2.buttonryfpB5s9BField, 24, 'before', `Add`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 25, page.url());
  
  
  
  
  await MK.onSleep(25, 'after', 2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 26, page.url(), '[{\"selector\":\"div.flex.items-center.justify-between.gap-2.w-full.text-neutralVariant-30.rounded-2xl.px-3.py-3.cursor-pointer.false.false>p.MuiTypography-root.MuiTypography-body1.false.flex-1.css-16qymjc\",\"index\":4},{\"selector\":\"div>p\",\"index\":7},{\"selector\":\"P\",\"index\":7},{\"selector\":\"//a[@href=\\"/104/tasks?filter=me-to-others\\"]\",\"index\":0}]', 3, 'p', '', 'click', '{"value":"To Others","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"To Others","type":"undef"}');
  await MK.onClick(pageDetails2.pnNoc66pSABEField, 26, 'before', `To Others`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 27, page.url(), '[{\"selector\":\"div.flex.max-lines-1>p.MuiTypography-root.MuiTypography-body2.max-lines-1.text-left.inline-block.whitespace-nowrap.overflow-hidden.text-ellipsis.h-fit.w-fit.max-w-full.css-mnp47j\",\"index\":0},{\"selector\":\"div>p\",\"index\":11},{\"selector\":\"P\",\"index\":18},{\"selector\":\"//P[contains(text(),\\"Task\\")]\",\"index\":0}]', 3, 'p', '', 'mouseover', '{"value":"Task","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Task","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails3.pXpcD8JfmDMField, 27, 'after', `Task`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 28, page.url(), '[{\"selector\":\"span.MuiButtonBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.PrivateSwitchBase-root.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.MuiCheckbox-root.MuiCheckbox-colorPrimary.MuiCheckbox-sizeMedium.h-fit.css-q9kyqd>input.PrivateSwitchBase-input.css-1m9pwf3\",\"index\":0},{\"selector\":\"span>input\",\"index\":0},{\"selector\":\"INPUT[type=\'checkbox\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\'3fc24a0e-5c6d-48c1-a318-b03bf2c315b1\'][@type=\'checkbox\']\",\"index\":0}]', 2, 'input', 'checkbox', 'click', '{"value":"Checkbox","searchType":"value","text":"undef"}', '{"id":"3fc24a0e-5c6d-48c1-a318-b03bf2c315b1","name":"undef","text":"undef","type":"checkbox"}');
  await MK.onClick(pageDetails3.inputZKet5tYnField, 28, 'before', `Checkbox`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 29, page.url(), '[{\"selector\":\"div.flex.flex-col.items-center.justify-center.gap-3.p-10>p.MuiTypography-root.MuiTypography-body1.text-neutral-20.text-lg.font-bold.css-16qymjc\",\"index\":0},{\"selector\":\"div>p\",\"index\":10},{\"selector\":\"P\",\"index\":17},{\"selector\":\"//div[contains(text(),\\"No rows\\")]\",\"index\":0}]', 3, 'p', '', 'mouseover', '{"value":"No tasks assigned to others","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"No tasks assigned to others","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails3.pxMbH2a3S61RField, 29, 'after', `No tasks assigned to others`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('sleep', 30, page.url());
  
  
  
  
  await MK.onSleep(30, 'after', 1); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarAppc9a29393_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
