
/*
* Generated by MuukTest
* Test Case ID: TC64128
* Description: Test functionality of the User button Accounts
* Generated: 2026-09-11T05:15:28.660Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavgxbd4woeujd2i,  dashboardStagingNavg8mqlmcoxvr5,  dashboardStagingNavgsvgjf9u9ic6c,  dashboardStagingNavg500ungjzym7e,  dashboardStagingNavgsc2nzmxtl6i,  dashboardStagingNavg8zknx3pwmq,  dashboardStagingNavggwnh7lkg1kl,  dashboardStagingNavgwnry5jsnivb,  dashboardStagingNavg90djub1wboef,  dashboardStagingNavgoy1kmmmd2m,  dashboardStagingNavgj19joroqlg5n,  dashboardStagingNavgdm2hlm5bgbh,  helpNavgarCom77a01lk2p32l,  navgarComqb3jsinpfu,  navgarComur4oay2d1yog,  dashboardStagingNavg23ukecibpwgt,  dashboardStagingNavgoqflzk1fgxo,  dashboardStagingNavgl7n3b1miy3j,  helpNavgarComydlpwqy3m6,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarAppebfc53f6.log';
const muukReport = new MuukReport('dashboardStagingNavgarAppebfc53f6');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarAppebfc53f6',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarAppebfc53f6', muukReport);
  MK.setVideoTracker(200);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavgxbd4woeujd2i();
	const pageDetails3 = new dashboardStagingNavg8mqlmcoxvr5();
	const pageDetails4 = new dashboardStagingNavgsvgjf9u9ic6c();
	const pageDetails5 = new dashboardStagingNavg500ungjzym7e();
	const pageDetails6 = new dashboardStagingNavgsc2nzmxtl6i();
	const pageDetails7 = new dashboardStagingNavg8zknx3pwmq();
	const pageDetails8 = new dashboardStagingNavggwnh7lkg1kl();
	const pageDetails9 = new dashboardStagingNavgwnry5jsnivb();
	const pageDetails10 = new dashboardStagingNavg90djub1wboef();
	const pageDetails11 = new dashboardStagingNavgoy1kmmmd2m();
	const pageDetails12 = new dashboardStagingNavgj19joroqlg5n();
	const pageDetails13 = new dashboardStagingNavgdm2hlm5bgbh();
	const pageDetails14 = new helpNavgarCom77a01lk2p32l();
	const pageDetails15 = new navgarComqb3jsinpfu();
	const pageDetails16 = new navgarComur4oay2d1yog();
	const pageDetails17 = new dashboardStagingNavg23ukecibpwgt();
	const pageDetails18 = new dashboardStagingNavgoqflzk1fgxo();
	const pageDetails19 = new dashboardStagingNavgl7n3b1miy3j();
	const pageDetails20 = new helpNavgarComydlpwqy3m6();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"span.flex.items-center.text-gray-700.appearance-none>img.rounded-full.h-8.w-8\",\"index\":0},{\"selector\":\"span>img\",\"index\":0},{\"selector\":\"IMG\",\"index\":1},{\"selector\":\"//div[@aria-label=\\"Profile Menu\\"]\",\"index\":0}]', 3, 'img', '', 'mouseover', '{"value":"https://dashboard.staging.navgar.app/104/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NDA5MywicHVyIjoiYmxvYl9pZCJ9fQ==--943b629d6ae4daba73634002a6854460f9d5cf86/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJqcGciLCJyZXNpemVfdG9fZml0IjpbNDgsNDhdfSwicHVyIjoidmFyaWF0aW9uIn19--7c18acaa0ca5dffdc146ad169307c36e90b60afb/g5xRN_qk_400x400.jpg","searchType":"imgsrc","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails4.imgpgCly7sbXoField, 14, 'after', `Muuk icon`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"div.inline-block.select-none>span.flex.items-center.text-gray-700.appearance-none\",\"index\":0},{\"selector\":\"div>span\",\"index\":6},{\"selector\":\"SPAN\",\"index\":24},{\"selector\":\"//div[@aria-label=\\"Profile Menu\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"\\n        \\n        \\n      ","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"\\n        \\n        \\n      ","type":"undef"}');
  await MK.onClick(pageDetails4.spanrEcpEzFNg9Field, 15, 'before', `Muuk icon                      `, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"div.overflow-hidden.bg-white.border.border-gray-200.rounded.shadow-md>a.no-underline.block.px-6.py-3.text-gray-800.bg-white.hover:bg-primary-50.transition.ease-in-out.duration-200.whitespace-nowrap\",\"index\":0},{\"selector\":\"div>a\",\"index\":5},{\"selector\":\"A\",\"index\":5},{\"selector\":\"//A[contains(text(),\\"Profile\\")]\",\"index\":1}]', 3, 'a', '', 'mouseover', '{"value":"/104/users/edit","searchType":"href","text":"Profile"}', '{"id":"undef","name":"undef","text":"Profile","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails4.a14I2XNcZdPField, 16, 'after', `Profile`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"div.overflow-hidden.bg-white.border.border-gray-200.rounded.shadow-md>a.no-underline.block.px-6.py-3.text-gray-800.bg-white.hover:bg-primary-50.transition.ease-in-out.duration-200.whitespace-nowrap\",\"index\":0},{\"selector\":\"div>a\",\"index\":6},{\"selector\":\"A\",\"index\":6},{\"selector\":\"//A[contains(text(),\\"Password\\")]\",\"index\":0}]', 3, 'a', '', 'mouseover', '{"value":"/104/account/password","searchType":"href","text":"Password"}', '{"id":"undef","name":"undef","text":"Password","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails4.aqXHMwTLdVField, 17, 'after', `Password`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"div.overflow-hidden.bg-white.border.border-gray-200.rounded.shadow-md>a.no-underline.block.px-6.py-3.text-gray-800.bg-white.hover:bg-primary-50.transition.ease-in-out.duration-200.whitespace-nowrap\",\"index\":0},{\"selector\":\"div>a\",\"index\":7},{\"selector\":\"A\",\"index\":7},{\"selector\":\"//A[contains(text(),\\"Connected Accounts\\")]\",\"index\":0}]', 3, 'a', '', 'mouseover', '{"value":"/104/user/connected_accounts","searchType":"href","text":"Connected Accounts"}', '{"id":"undef","name":"undef","text":"Connected Accounts","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails4.adlhwNrHJw8Field, 18, 'after', `Connected Accounts`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 19, page.url(), '[{\"selector\":\"div.overflow-hidden.bg-white.border.border-gray-200.rounded.shadow-md>a.no-underline.block.px-6.py-3.text-gray-800.bg-white.hover:bg-primary-50.transition.ease-in-out.duration-200.whitespace-nowrap\",\"index\":0},{\"selector\":\"div>a\",\"index\":8},{\"selector\":\"A\",\"index\":8},{\"selector\":\"//A[contains(text(),\\"Billing\\")]\",\"index\":0}]', 3, 'a', '', 'mouseover', '{"value":"/104/subscriptions","searchType":"href","text":"Billing"}', '{"id":"undef","name":"undef","text":"Billing","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails4.aPRiG4wS8WBField, 19, 'after', `Billing`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"div.overflow-hidden.bg-white.border.border-gray-200.rounded.shadow-md>a.no-underline.block.px-6.py-3.text-gray-800.bg-white.hover:bg-primary-50.transition.ease-in-out.duration-200.whitespace-nowrap\",\"index\":0},{\"selector\":\"div>a\",\"index\":5},{\"selector\":\"A\",\"index\":5},{\"selector\":\"//A[contains(text(),\\"Profile\\")]\",\"index\":1}]', 3, 'a', '', 'click', '{"value":"/104/users/edit","searchType":"href","text":"Profile"}', '{"id":"undef","name":"undef","text":"Profile","type":"undef"}');
  await MK.onClick(pageDetails4.a14I2XNcZdPField, 20, 'before', `Profile`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 21, page.url(), '[{\"selector\":\"div.p-4.bg-white.border.border-gray-200.rounded-lg.lg:p-10>h1.h3.mb-4\",\"index\":0},{\"selector\":\"div>h1\",\"index\":0},{\"selector\":\"H1\",\"index\":0},{\"selector\":\"//H1[contains(text(),\\"Edit Profile\\")]\",\"index\":0}]', 3, 'h1', '', 'mouseover', '{"value":"Edit Profile","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Edit Profile","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails10.h1Z4TrPHzdgField, 21, 'after', `Edit Profile`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 22, page.url(), '[{\"selector\":\"div.inline-block.select-none>span.flex.items-center.text-gray-700.appearance-none\",\"index\":0},{\"selector\":\"div>span\",\"index\":6},{\"selector\":\"SPAN\",\"index\":24},{\"selector\":\"//div[@aria-label=\\"Profile Menu\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"\\n        \\n        \\n      ","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"\\n        \\n        \\n      ","type":"undef"}');
  await MK.onClick(pageDetails4.spanrEcpEzFNg9Field, 22, 'before', `Muuk icon                      `, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 23, page.url(), '[{\"selector\":\"div.overflow-hidden.bg-white.border.border-gray-200.rounded.shadow-md>a.no-underline.block.px-6.py-3.text-gray-800.bg-white.hover:bg-primary-50.transition.ease-in-out.duration-200.whitespace-nowrap\",\"index\":0},{\"selector\":\"div>a\",\"index\":7},{\"selector\":\"A\",\"index\":7},{\"selector\":\"//A[contains(text(),\\"Password\\")]\",\"index\":0}]', 3, 'a', '', 'click', '{"value":"/104/account/password","searchType":"href","text":"Password"}', '{"id":"undef","name":"undef","text":"Password","type":"undef"}');
  await MK.onClick(pageDetails10.aZ3S4GcxvxField, 23, 'before', `Password`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 24, page.url(), '[{\"selector\":\"div.lg:p-10.p-4.bg-white.rounded-lg.border.border-gray-200>h1.h3.mb-4\",\"index\":0},{\"selector\":\"div>h1\",\"index\":0},{\"selector\":\"H1\",\"index\":0},{\"selector\":\"//H1[contains(text(),\\"Update Password\\")]\",\"index\":0}]', 3, 'h1', '', 'mouseover', '{"value":"Update Password","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Update Password","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails11.h1EZUB91TlNKField, 24, 'after', `Update Password`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 25, page.url(), '[{\"selector\":\"div.lg:p-10.p-4.bg-white.rounded-lg.border.border-gray-200>h1.h3.mb-4\",\"index\":0},{\"selector\":\"div>h1\",\"index\":0},{\"selector\":\"H1\",\"index\":0},{\"selector\":\"//H1[contains(text(),\\"Update Password\\")]\",\"index\":0}]', 3, 'h1', '', 'mouseover', '{"value":"Update Password","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Update Password","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails11.h1EZUB91TlNKField, 25, 'after', `Update Password`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 26, page.url(), '[{\"selector\":\"div.inline-block.select-none>span.flex.items-center.text-gray-700.appearance-none\",\"index\":0},{\"selector\":\"div>span\",\"index\":6},{\"selector\":\"SPAN\",\"index\":24},{\"selector\":\"//div[@aria-label=\\"Profile Menu\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"\\n        \\n        \\n      ","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"\\n        \\n        \\n      ","type":"undef"}');
  await MK.onClick(pageDetails4.spanrEcpEzFNg9Field, 26, 'before', `Muuk icon                      `, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 27, page.url(), '[{\"selector\":\"div.overflow-hidden.bg-white.border.border-gray-200.rounded.shadow-md>a.no-underline.block.px-6.py-3.text-gray-800.bg-white.hover:bg-primary-50.transition.ease-in-out.duration-200.whitespace-nowrap\",\"index\":0},{\"selector\":\"div>a\",\"index\":9},{\"selector\":\"A\",\"index\":9},{\"selector\":\"//A[contains(text(),\\"Billing\\")]\",\"index\":0}]', 3, 'a', '', 'click', '{"value":"/104/subscriptions","searchType":"href","text":"Billing"}', '{"id":"undef","name":"undef","text":"Billing","type":"undef"}');
  await MK.onClick(pageDetails11.apoC3jSx9wField, 27, 'before', `Billing`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 28, page.url(), '[{\"selector\":\"div.lg:p-10.p-4.bg-white.dark:bg-gray-900.rounded-lg.border.border-gray-200.dark:border-gray-700>h1.h3.mb-2.text-black.dark:text-white\",\"index\":0},{\"selector\":\"div>h1\",\"index\":0},{\"selector\":\"H1\",\"index\":0},{\"selector\":\"//H1[contains(text(),\\"Billing\\")]\",\"index\":0}]', 3, 'h1', '', 'mouseover', '{"value":"Billing","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Billing","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails12.h1rJcRNaT476Field, 28, 'after', `Billing`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 29, page.url(), '[{\"selector\":\"div.inline-block.select-none>span.flex.items-center.text-gray-700.appearance-none\",\"index\":0},{\"selector\":\"div>span\",\"index\":6},{\"selector\":\"SPAN\",\"index\":24},{\"selector\":\"//div[@aria-label=\\"Profile Menu\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"\\n        \\n        \\n      ","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"\\n        \\n        \\n      ","type":"undef"}');
  await MK.onClick(pageDetails4.spanrEcpEzFNg9Field, 29, 'before', `Muuk icon                      `, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 30, page.url(), '[{\"selector\":\"div.overflow-hidden.bg-white.border.border-gray-200.rounded.shadow-md>a.no-underline.block.px-6.py-3.text-gray-800.bg-white.hover:bg-primary-50.transition.ease-in-out.duration-200.whitespace-nowrap\",\"index\":0},{\"selector\":\"div>a\",\"index\":10},{\"selector\":\"A\",\"index\":10},{\"selector\":\"//A[contains(text(),\\"Accounts\\")]\",\"index\":2}]', 3, 'a', '', 'click', '{"value":"/104/accounts","searchType":"href","text":"Accounts"}', '{"id":"undef","name":"undef","text":"Accounts","type":"undef"}');
  await MK.onClick(pageDetails12.agrIrE9syX8Field, 30, 'before', `Accounts`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 31, page.url(), '[{\"selector\":\"div.sm:flex.items-center.justify-between.mb-3>h1.flex-1.h3\",\"index\":0},{\"selector\":\"div>h1\",\"index\":0},{\"selector\":\"H1\",\"index\":0},{\"selector\":\"//H1[contains(text(),\\"Accounts\\")]\",\"index\":0}]', 3, 'h1', '', 'mouseover', '{"value":"Accounts","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Accounts","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails13.h1L1H7dmtylqField, 31, 'after', `Accounts`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 32, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails13.spandziWZHXGField, 32, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 33, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails13.spanqytr7guj5XField, 33, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarAppebfc53f6_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
