
/*
* Generated by MuukTest
* Test Case ID: TC64516
* Description: Reminders Create 20 min reminder
* Generated: 2026-09-11T05:15:42.990Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   googleComw1zlr5y53vu,  dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavg8mqlmcoxvr5,  dashboardStagingNavg8zknx3pwmq,  dashboardStagingNavgsvgjf9u9ic6c,  dashboardStagingNavggnw70cgklbfr,  dashboardStagingNavg8tjcsnuzj3qe,  dashboardStagingNavg23ukecibpwgt,  dashboardStagingNavgoqflzk1fgxo,  dashboardStagingNavgl7n3b1miy3j,  dashboardStagingNavge1ynuou0dcop,  dashboardStagingNavgiu4m1aiovm79,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarApp2960b839.log';
const muukReport = new MuukReport('dashboardStagingNavgarApp2960b839');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarApp2960b839',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarApp2960b839', muukReport);
  MK.setVideoTracker(200);
	const pageDetails1 = new googleComw1zlr5y53vu();
	const pageDetails2 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails3 = new dashboardStagingNavg8mqlmcoxvr5();
	const pageDetails4 = new dashboardStagingNavg8zknx3pwmq();
	const pageDetails5 = new dashboardStagingNavgsvgjf9u9ic6c();
	const pageDetails6 = new dashboardStagingNavggnw70cgklbfr();
	const pageDetails7 = new dashboardStagingNavg8tjcsnuzj3qe();
	const pageDetails8 = new dashboardStagingNavg23ukecibpwgt();
	const pageDetails9 = new dashboardStagingNavgoqflzk1fgxo();
	const pageDetails10 = new dashboardStagingNavgl7n3b1miy3j();
	const pageDetails11 = new dashboardStagingNavge1ynuou0dcop();
	const pageDetails12 = new dashboardStagingNavgiu4m1aiovm79();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"svg.MuiSvgIcon-root.MuiSvgIcon-fontSizeMedium.text-primary-50.css-vubbuv>path\",\"index\":0},{\"selector\":\"svg>path\",\"index\":17},{\"selector\":\"path\",\"index\":18},{\"selector\":\"//button[.//span[contains(@class,\'MuiBadge-root\')]]\",\"index\":0}]', 3, 'path', '', 'mouseover', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails8.path7ks7qXFx6Field, 14, 'after', `Reminders`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"svg.MuiSvgIcon-root.MuiSvgIcon-fontSizeMedium.text-primary-50.css-vubbuv>path\",\"index\":0},{\"selector\":\"svg>path\",\"index\":17},{\"selector\":\"path\",\"index\":18},{\"selector\":\"//button[.//span[contains(@class,\'MuiBadge-root\')]]\",\"index\":0}]', 3, 'path', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails8.path7ks7qXFx6Field, 15, 'before', `Reminders`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.css-1k66m85>input.MuiInputBase-input.MuiOutlinedInput-input.css-1x5jdmq\",\"index\":0},{\"selector\":\"div>input\",\"index\":3},{\"selector\":\"INPUT[name=\'content_plain\'][placeholder=\'Remind me about...\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':rj:\'][@name=\'content_plain\'][@placeholder=\'Remind me about...\'][@type=\'text\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":rj:","name":"content_plain","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails9.input70TRj6FN0BField, 16, 'after', `Reminder 20 min`, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"p.MuiTypography-root.MuiTypography-body1.flex.items-center.gap-1.capitalize.css-16qymjc>span.max-w-52.text-ellipsis.overflow-hidden\",\"index\":0},{\"selector\":\"p>span\",\"index\":0},{\"selector\":\"SPAN\",\"index\":46},{\"selector\":\"//SPAN[contains(text(),\\"in 20 min\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"in 20 min","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"in 20 min","type":"undef"}');
  await MK.onClick(pageDetails9.spannNUrRzhRm8Field, 17, 'before', `in 20 min`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"button.MuiButtonBase-root.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-colorPrimary.break-all.w-full.flex.justify-start.px-1.py-0.rounded-md.text-base.text-neutral-20.font-normal.text-left.hover:bg-secondary-90.css-1wvg4b>p\",\"index\":0},{\"selector\":\"button>p\",\"index\":7},{\"selector\":\"P\",\"index\":21},{\"selector\":\"//P[contains(text(),\\"Reminder 20 min\\")]\",\"index\":0}]', 3, 'p', '', 'click', '{"value":"Reminder 20 min","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Reminder 20 min","type":"undef"}');
  await MK.onClick(pageDetails10.p2gyHJBpfxkLField, 18, 'before', `Reminder 20 min`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 19, page.url(), '[{\"selector\":\"button.flex.items-center.border.rounded-lg.border-neutral-80.bg-white.px-2.gap-1>span.MuiTypography-root.MuiTypography-caption.whitespace-nowrap.font-bold.text-neutral-40.css-1p728zq\",\"index\":0},{\"selector\":\"button>span\",\"index\":14},{\"selector\":\"SPAN\",\"index\":55},{\"selector\":\"//SPAN[contains(text(),\\"Clear\\")]\",\"index\":0}]', 3, 'span', '', 'mouseover', '{"value":"Clear","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Clear","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails9.span8gi2N0Fpd4Field, 19, 'after', `Clear`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"div.flex.gap-2>button.flex.items-center.border.rounded-lg.border-neutral-80.bg-white.px-2.gap-1\",\"index\":0},{\"selector\":\"div>button\",\"index\":17},{\"selector\":\"BUTTON[role=\'button\'][type=\'button\']\",\"index\":0},{\"selector\":\"//BUTTON[@role=\'button\'][@type=\'button\'][normalize-space() = \\"Clear\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Clear","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Clear","type":"button"}');
  await MK.onClick(pageDetails9.buttonlJC446HA8zField, 20, 'before', `Clear`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 21, page.url(), '[{\"selector\":\"div.MuiPaper-root.MuiPaper-elevation.MuiPaper-rounded.MuiPaper-elevation0.MuiAlert-root.MuiAlert-colorSuccess.MuiAlert-standardSuccess.MuiAlert-standard.css-6rmxgy>div.MuiAlert-message.css-127h8j3\",\"index\":0},{\"selector\":\"div>div\",\"index\":6},{\"selector\":\"DIV\",\"index\":7},{\"selector\":\"//DIV[contains(text(),\\"The reminder has been updated successful\\")]\",\"index\":0}]', 3, 'div', '', 'mouseover', '{"value":"The reminder has been updated successfully","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"The reminder has been updated successfully","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails9.divYJtllNCorMField, 21, 'after', `The reminder has been updated successfully`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarApp2960b839_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
