
/*
* Generated by MuukTest
* Test Case ID: TC62158
* Description: Edit and adjust my task information within the task drawer Reassign the task
* Generated: 2026-09-07T02:43:05.170Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavg8mqlmcoxvr5,  dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavg5f05sqbgwy6o,  dashboardStagingNavgf3aog1gy5mu,  dashboardStagingNavgiu4m1aiovm79,  dashboardStagingNavgtnd2ciy9trjc,  dashboardStagingNavgq4t68r1ov3g,  dashboardStagingNavgzkdhpabe4he,  dashboardStagingNavgllgtujbllz93,  dashboardStagingNavgbdkxq4v1rz6e,  dashboardStagingNavgwpww231kx1yh,  dashboardStagingNavglgmzb6kl603,  dashboardStagingNavgsquoemce49i9,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarApp999e4fad.log';
const muukReport = new MuukReport('dashboardStagingNavgarApp999e4fad');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarApp999e4fad',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarApp999e4fad', muukReport);
  MK.setVideoTracker(0);
	const pageDetails1 = new dashboardStagingNavg8mqlmcoxvr5();
	const pageDetails2 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails3 = new dashboardStagingNavg5f05sqbgwy6o();
	const pageDetails4 = new dashboardStagingNavgf3aog1gy5mu();
	const pageDetails5 = new dashboardStagingNavgiu4m1aiovm79();
	const pageDetails6 = new dashboardStagingNavgtnd2ciy9trjc();
	const pageDetails7 = new dashboardStagingNavgq4t68r1ov3g();
	const pageDetails8 = new dashboardStagingNavgzkdhpabe4he();
	const pageDetails9 = new dashboardStagingNavgllgtujbllz93();
	const pageDetails10 = new dashboardStagingNavgbdkxq4v1rz6e();
	const pageDetails11 = new dashboardStagingNavgwpww231kx1yh();
	const pageDetails12 = new dashboardStagingNavglgmzb6kl603();
	const pageDetails13 = new dashboardStagingNavgsquoemce49i9();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-m3hfr4>span.text-xs.whitespace-break-spaces.w-fit.text-center\",\"index\":1},{\"selector\":\"li>span\",\"index\":1},{\"selector\":\"SPAN\",\"index\":8},{\"selector\":\"//SPAN[contains(text(),\\"Tasks\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Tasks","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Tasks","type":"undef"}');
  await MK.onClick(pageDetails1.spanrNwSd7xTwjField, 14, 'before', `Tasks`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 15, page.url());
  
  
  
  
  
  
  
   console.log('step:15'); 
  logIndex = 15;
  // Selector for task rows in the grid
const taskSelector =
  '//div[@role="gridcell"][@data-field="legend"]/a/span[normalize-space() = "Task"]';
const emptyGridSelector = '//div[contains(text(),"No rows")]';

// Wait briefly for the grid to settle, then count matches
const taskLocator = page.locator(taskSelector);
let taskCount = 0;

try {
  await taskLocator.first().waitFor({ state: 'visible', timeout: 5000 });
  taskCount = await taskLocator.count();
} catch {
  taskCount = 0;
}

if (taskCount > 0) {
  snippetLog(`Found ${taskCount} task(s). Running delete actions...`);

  // Click the "Select Tasks" button
  await page.click('//button[contains(text(), "Select Tasks")]');
  //await page.waitForTimeout(2000);

  // Click the "select all" checkbox
  await page.click('//input[@name="select_all_rows"]');
  //await page.waitForTimeout(2000);

  // Open "More options"
  await page.click('//button[@id="more-menu"]');

  // Click the "Delete" option
  await page.click('//span[contains(text(), "Delete")]');

  // Confirm the dialog
  await page.keyboard.press('Enter');
  for (let i = 0; i < 3; i++) {
    await page.keyboard.press('Tab');
  }
  await page.keyboard.press('Enter');
} else {
  snippetLog('No tasks found. Nothing to delete.');
}

// Verify the grid is empty afterwards
const isGridEmpty = await page
  .locator(emptyGridSelector)
  .isVisible()
  .catch(() => false);

if (isGridEmpty) {
  snippetLog('Grid is empty after the actions.');
} else {
  snippetLog(`Grid still has ${await taskLocator.count()} task(s).`);
}
   await MK.takeScreenshot(15); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"div.MuiBox-root.css-1jr7naq>button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.css-bj6f2k\",\"index\":0},{\"selector\":\"div>button\",\"index\":4},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":4},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"New Task\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"New Task","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"New Task","type":"button"}');
  await MK.onClick(pageDetails5.buttonezSgGKH7nEField, 16, 'before', `New Task`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.Mui-focused.MuiInputBase-formControl.MuiInputBase-adornedEnd.css-pr07w6>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputAdornedEnd.css-qwdxx6\",\"index\":0},{\"selector\":\"div>input\",\"index\":3},{\"selector\":\"INPUT[name=\'legend\'][placeholder=\'Create new task\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r4n:\'][@name=\'legend\'][@placeholder=\'Create new task\'][@type=\'text\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r4n:","name":"legend","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails5.inputeQu63vFPBeField, 17, 'after', `Task`, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.MuiInputBase-adornedEnd.css-pr07w6>button.MuiButtonBase-root.MuiButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeSmall.MuiButton-outlinedSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeSmall.MuiButton-outlinedSizeSmall.MuiButton-colorPrimary.css-150c2mk\",\"index\":0},{\"selector\":\"div>button\",\"index\":29},{\"selector\":\"BUTTON[type=\'submit\']\",\"index\":1},{\"selector\":\"//BUTTON[@type=\'submit\'][normalize-space() = \\"Create\\"]\",\"index\":0}]', 3, 'button', 'submit', 'click', '{"value":"Create","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Create","type":"submit"}');
  await MK.onClick(pageDetails5.buttonQOFlRcZgdField, 18, 'before', `Create`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 19, page.url(), '[{\"selector\":\"div.flex.items-center.relative.min-h-9>p.MuiTypography-root.MuiTypography-body2.text-left.inline-block.whitespace-nowrap.overflow-hidden.text-ellipsis.h-fit.w-fit.max-w-full.css-mnp47j\",\"index\":0},{\"selector\":\"div>p\",\"index\":11},{\"selector\":\"P\",\"index\":18},{\"selector\":\"//div[@role=\\"gridcell\\"][@data-field=\\"legend\\"]/a/span[contains(text(), \\"Task\\")]\",\"index\":0}]', 3, 'p', '', 'mouseover', '{"value":"Task","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Task","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails1.pwvhvowiWmoField, 19, 'after', `Task`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"div.flex.items-center.relative.min-h-9>p.MuiTypography-root.MuiTypography-body2.text-left.inline-block.whitespace-nowrap.overflow-hidden.text-ellipsis.h-fit.w-fit.max-w-full.css-mnp47j\",\"index\":0},{\"selector\":\"div>p\",\"index\":11},{\"selector\":\"P\",\"index\":18},{\"selector\":\"//div[@role=\\"gridcell\\"][@data-field=\\"legend\\"]/a/span[contains(text(), \\"Task\\")]\",\"index\":0}]', 3, 'p', '', 'click', '{"value":"Task","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Task","type":"undef"}');
  await MK.onClick(pageDetails1.pwvhvowiWmoField, 20, 'before', `Task`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 21, page.url(), '[{\"selector\":\"div.MuiBox-root.css-171onha>button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.css-mfslm7\",\"index\":0},{\"selector\":\"div>button\",\"index\":25},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":29},{\"selector\":\"//button[@aria-label=\'Someday\']/following-sibling::button[1]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"button"}');
  await MK.onClick(pageDetails11.buttondXUXkmI0NKField, 21, 'before', `Options - drawler`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 22, page.url(), '[{\"selector\":\"div.MuiListItemText-root.css-a2y5gf>span.MuiTypography-root.MuiTypography-body1.MuiListItemText-primary.css-q31gs0\",\"index\":3},{\"selector\":\"div>span\",\"index\":37},{\"selector\":\"SPAN\",\"index\":120},{\"selector\":\"//SPAN[normalize-space() = \\"Reassign\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Reassign","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Reassign","type":"undef"}');
  await MK.onClick(pageDetails13.spanRLF7NDSdWField, 22, 'before', `Reassign`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 23, page.url(), '[{\"selector\":\"div.MuiListItemText-root.MuiListItemText-dense.css-a2y5gf>span.MuiTypography-root.MuiTypography-body2.MuiTypography-noWrap.MuiListItemText-primary.css-1simrr0\",\"index\":2},{\"selector\":\"div>span\",\"index\":47},{\"selector\":\"SPAN\",\"index\":134},{\"selector\":\"//SPAN[normalize-space() = \\"VV Victor Villa\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"VV Victor Villa","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"VV Victor Villa","type":"undef"}');
  await MK.onClick(pageDetails13.spanmKcjNvfRNPField, 23, 'before', `VV Victor Villa`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 24, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(24, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('step', 25, page.url(), '[{\"selector\":\"div.MuiBox-root.css-axw7ok>button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.css-mfslm7\",\"index\":0},{\"selector\":\"div>button\",\"index\":26},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":30},{\"selector\":\"//div[@role=\'separator\']/following-sibling::button\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"button"}');
  await MK.onClick(pageDetails10.buttonGgs0MjsG4Field, 25, 'before', `Close drawler`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarApp999e4fad_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
