
/*
* Generated by MuukTest
* Test Case ID: TC_A70462
* Description: Confirm Assign to entity button prompts entity selector overlay
* Generated: 2026-09-07T02:43:19.628Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavg8mqlmcoxvr5,  dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavg5f05sqbgwy6o,  dashboardStagingNavgxbd4woeujd2i,  dashboardStagingNavgf3aog1gy5mu,  dashboardStagingNavgwnry5jsnivb,  dashboardStagingNavgiu4m1aiovm79,  dashboardStagingNavgoaunhfltkfj,  dashboardStagingNavgo3hyuoxfqztq,  dashboardStagingNavgcn67p2et5eda,  dashboardStagingNavggommsarcfz,  dashboardStagingNavgbeu0qmzfiw5i,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarAppe520b5c5.log';
const muukReport = new MuukReport('dashboardStagingNavgarAppe520b5c5');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarAppe520b5c5',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarAppe520b5c5', muukReport);
  MK.setVideoTracker(0);
	const pageDetails1 = new dashboardStagingNavg8mqlmcoxvr5();
	const pageDetails2 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails3 = new dashboardStagingNavg5f05sqbgwy6o();
	const pageDetails4 = new dashboardStagingNavgxbd4woeujd2i();
	const pageDetails5 = new dashboardStagingNavgf3aog1gy5mu();
	const pageDetails6 = new dashboardStagingNavgwnry5jsnivb();
	const pageDetails7 = new dashboardStagingNavgiu4m1aiovm79();
	const pageDetails8 = new dashboardStagingNavgoaunhfltkfj();
	const pageDetails9 = new dashboardStagingNavgo3hyuoxfqztq();
	const pageDetails10 = new dashboardStagingNavgcn67p2et5eda();
	const pageDetails11 = new dashboardStagingNavggommsarcfz();
	const pageDetails12 = new dashboardStagingNavgbeu0qmzfiw5i();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-m3hfr4>span.text-xs\",\"index\":5},{\"selector\":\"li>span\",\"index\":5},{\"selector\":\"SPAN\",\"index\":21},{\"selector\":\"//SPAN[contains(text(),\\"Accounts\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Accounts","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Accounts","type":"undef"}');
  await MK.onClick(pageDetails4.spangxWHrVLFZwField, 15, 'before', `Accounts`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 16, page.url(), '[{\"selector\":\"li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters.css-1qyfo9m>span.px-1\",\"index\":0},{\"selector\":\"li>span\",\"index\":8},{\"selector\":\"SPAN\",\"index\":49},{\"selector\":\"//SPAN[contains(text(),\\"MuukTest - Feature Flag Environment\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"MuukTest - Feature Flag Environment ","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"MuukTest - Feature Flag Environment ","type":"undef"}');
  await MK.onClick(pageDetails4.spany8XCnwid2ZField, 16, 'before', `MuukTest - Feature Flag Environment `, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-m3hfr4>span.text-xs.whitespace-break-spaces.w-fit.text-center\",\"index\":1},{\"selector\":\"li>span\",\"index\":1},{\"selector\":\"SPAN\",\"index\":8},{\"selector\":\"//SPAN[contains(text(),\\"Tasks\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Tasks","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Tasks","type":"undef"}');
  await MK.onClick(pageDetails1.spanrNwSd7xTwjField, 18, 'before', `Tasks`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 19, page.url());
  
  
  
  
  
  
  
   console.log('step:19'); 
  logIndex = 19;
  // Selector for task rows in the grid
const taskSelector =
  '//div[@role="gridcell"][@data-field="legend"]/a/span[normalize-space() = "Task"]';
const emptyGridSelector = '//div[contains(text(),"No rows")]';

// Wait briefly for the grid to settle, then count matches
const taskLocator = page.locator(taskSelector);
let taskCount = 0;

try {
  await taskLocator.first().waitFor({ state: 'visible', timeout: 5000 });
  taskCount = await taskLocator.count();
} catch {
  taskCount = 0;
}

if (taskCount > 0) {
  snippetLog(`Found ${taskCount} task(s). Running delete actions...`);

  // Click the "Select Tasks" button
  await page.click('//button[contains(text(), "Select Tasks")]');
  //await page.waitForTimeout(2000);

  // Click the "select all" checkbox
  await page.click('//input[@name="select_all_rows"]');
  //await page.waitForTimeout(2000);

  // Open "More options"
  await page.click('//button[@id="more-menu"]');

  // Click the "Delete" option
  await page.click('//span[contains(text(), "Delete")]');

  // Confirm the dialog
  await page.keyboard.press('Enter');
  for (let i = 0; i < 3; i++) {
    await page.keyboard.press('Tab');
  }
  await page.keyboard.press('Enter');
} else {
  snippetLog('No tasks found. Nothing to delete.');
}

// Verify the grid is empty afterwards
const isGridEmpty = await page
  .locator(emptyGridSelector)
  .isVisible()
  .catch(() => false);

if (isGridEmpty) {
  snippetLog('Grid is empty after the actions.');
} else {
  snippetLog(`Grid still has ${await taskLocator.count()} task(s).`);
}
   await MK.takeScreenshot(19); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"div.MuiBox-root.css-1jr7naq>button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.css-bj6f2k\",\"index\":0},{\"selector\":\"div>button\",\"index\":4},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":4},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"New Task\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"New Task","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"New Task","type":"button"}');
  await MK.onClick(pageDetails7.buttonezSgGKH7nEField, 20, 'before', `New Task`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 21, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.Mui-focused.MuiInputBase-formControl.MuiInputBase-adornedEnd.css-pr07w6>input.MuiInputBase-input.MuiOutlinedInput-input.MuiInputBase-inputAdornedEnd.css-qwdxx6\",\"index\":0},{\"selector\":\"div>input\",\"index\":3},{\"selector\":\"INPUT[name=\'legend\'][placeholder=\'Create new task\'][type=\'text\']\",\"index\":0},{\"selector\":\"//INPUT[@id=\':r4n:\'][@name=\'legend\'][@placeholder=\'Create new task\'][@type=\'text\']\",\"index\":0}]', 2, 'input', 'text', 'assignment', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":":r4n:","name":"legend","text":"undef","type":"text"}');
  
  
  await MK.onAssignment(pageDetails7.inputeQu63vFPBeField, 21, 'after', `Task`, 'text', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 22, page.url(), '[{\"selector\":\"div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-formControl.MuiInputBase-adornedEnd.css-pr07w6>button.MuiButtonBase-root.MuiButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeSmall.MuiButton-outlinedSizeSmall.MuiButton-colorPrimary.MuiButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeSmall.MuiButton-outlinedSizeSmall.MuiButton-colorPrimary.css-150c2mk\",\"index\":0},{\"selector\":\"div>button\",\"index\":29},{\"selector\":\"BUTTON[type=\'submit\']\",\"index\":1},{\"selector\":\"//BUTTON[@type=\'submit\'][normalize-space() = \\"Create\\"]\",\"index\":0}]', 3, 'button', 'submit', 'click', '{"value":"Create","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Create","type":"submit"}');
  await MK.onClick(pageDetails7.buttonQOFlRcZgdField, 22, 'before', `Create`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 23, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-m3hfr4>span.text-xs.whitespace-break-spaces.w-fit.text-center\",\"index\":1},{\"selector\":\"li>span\",\"index\":1},{\"selector\":\"SPAN\",\"index\":8},{\"selector\":\"//SPAN[contains(text(),\\"Tasks\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Tasks","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Tasks","type":"undef"}');
  await MK.onClick(pageDetails1.spanrNwSd7xTwjField, 23, 'before', `Tasks`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 24, page.url(), '[{\"selector\":\"div.flex.items-center.relative.min-h-9>p.MuiTypography-root.MuiTypography-body2.text-left.inline-block.whitespace-nowrap.overflow-hidden.text-ellipsis.h-fit.w-fit.max-w-full.css-mnp47j\",\"index\":0},{\"selector\":\"div>p\",\"index\":11},{\"selector\":\"P\",\"index\":18},{\"selector\":\"//div[@role=\\"gridcell\\"][@data-field=\\"legend\\"]/a/span[contains(text(), \\"Task\\")]\",\"index\":0}]', 3, 'p', '', 'mouseover', '{"value":"Task","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Task","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails1.pwvhvowiWmoField, 24, 'after', `Task`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 25, page.url(), '[{\"selector\":\"button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.css-p8cfh1>svg.MuiSvgIcon-root.MuiSvgIcon-fontSizeMedium.text-primary-50.w-7.h-7.css-vubbuv\",\"index\":0},{\"selector\":\"button>svg\",\"index\":20},{\"selector\":\"svg\",\"index\":52},{\"selector\":\"//div[@data-field=\'actions\']//button\",\"index\":0}]', 3, 'svg', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails5.svgErt1jxC7abField, 25, 'before', `Open Task Details`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 26, page.url(), '[{\"selector\":\"div.MuiListItemText-root.css-a2y5gf>span.MuiTypography-root.MuiTypography-body1.MuiListItemText-primary.css-q31gs0\",\"index\":8},{\"selector\":\"div>span\",\"index\":65},{\"selector\":\"SPAN\",\"index\":180},{\"selector\":\"//SPAN[normalize-space() = \\"Assign to entity\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Assign to entity","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Assign to entity","type":"undef"}');
  await MK.onClick(pageDetails12.span1wTGLWSoV1Field, 26, 'before', `Assign to entity`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 27, page.url(), '[{\"selector\":\"div.flex.items-center.gap-1.p-4.h-16>p.MuiTypography-root.MuiTypography-body2.max-w-72.whitespace-nowrap.text-ellipsis.overflow-hidden.css-41aif7\",\"index\":0},{\"selector\":\"div>p\",\"index\":57},{\"selector\":\"P\",\"index\":58},{\"selector\":\"//P[normalize-space() = \\"Select Entity Type\\"]\",\"index\":0}]', 3, 'p', '', 'mouseover', '{"value":"Select Entity Type","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Select Entity Type","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails12.pqdhyy9UzBWField, 27, 'after', `Select Entity Type`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('keyboardpress', 28, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
   await MK.onKeyboardPress(28, 'after', `Escape`, 60000); 
  
  
  
  await muukReport.addStepInfo('step', 29, page.url(), '[{\"selector\":\"li.MuiListItem-root.MuiListItem-gutters.flex-1.flex-col.css-m3hfr4>span.text-xs.whitespace-break-spaces.w-fit.text-center\",\"index\":1},{\"selector\":\"li>span\",\"index\":1},{\"selector\":\"SPAN\",\"index\":8},{\"selector\":\"//SPAN[contains(text(),\\"Tasks\\")]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"Tasks","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Tasks","type":"undef"}');
  await MK.onClick(pageDetails1.spanrNwSd7xTwjField, 29, 'before', `Tasks`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 30, page.url(), '[{\"selector\":\"div.flex.items-center.relative.min-h-9>p.MuiTypography-root.MuiTypography-body2.text-left.inline-block.whitespace-nowrap.overflow-hidden.text-ellipsis.h-fit.w-fit.max-w-full.css-mnp47j\",\"index\":0},{\"selector\":\"div>p\",\"index\":11},{\"selector\":\"P\",\"index\":18},{\"selector\":\"//div[@role=\\"gridcell\\"][@data-field=\\"legend\\"]/a/span[contains(text(), \\"Task\\")]\",\"index\":0}]', 3, 'p', '', 'mouseover', '{"value":"Task","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Task","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails1.pwvhvowiWmoField, 30, 'after', `Task`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 31, page.url(), '[{\"selector\":\"button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium.css-p8cfh1>svg.MuiSvgIcon-root.MuiSvgIcon-fontSizeMedium.text-primary-50.w-7.h-7.css-vubbuv\",\"index\":0},{\"selector\":\"button>svg\",\"index\":20},{\"selector\":\"svg\",\"index\":52},{\"selector\":\"//div[@data-field=\'actions\']//button\",\"index\":0}]', 3, 'svg', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails5.svgErt1jxC7abField, 31, 'before', `Open Task Details`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 32, page.url(), '[{\"selector\":\"div>li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters.css-1qyfo9m\",\"index\":5},{\"selector\":\"div>li\",\"index\":8},{\"selector\":\"LI[role=\'menuitem\']\",\"index\":8},{\"selector\":\"//li[normalize-space() = \\"Delete\\"]\",\"index\":0}]', 3, 'li', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Delete","type":"undef"}');
  await MK.onClick(pageDetails3.li7KIVKECwjzField, 32, 'before', `Delete`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 33, page.url(), '[{\"selector\":\"div.MuiBox-root.css-abpg3u>h6.MuiTypography-root.MuiTypography-h6.css-1y1xs1b\",\"index\":0},{\"selector\":\"div>h6\",\"index\":1},{\"selector\":\"H6\",\"index\":1},{\"selector\":\"//h6[normalize-space() = \\"Delete Tasks\\"]\",\"index\":0}]', 3, 'h6', '', 'click', '{"value":"undef","searchType":"undef","text":"undef"}', '{"id":"undef","name":"undef","text":"Delete Tasks","type":"undef"}');
  await MK.onClick(pageDetails7.h62VULllfGWnField, 33, 'before', `Delete Task - header`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 34, page.url(), '[{\"selector\":\"div.gap-2.MuiBox-root.css-gmrfgn>button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-colorPrimary.css-bj6f2k\",\"index\":0},{\"selector\":\"div>button\",\"index\":31},{\"selector\":\"BUTTON[type=\'button\']\",\"index\":35},{\"selector\":\"//BUTTON[@type=\'button\'][normalize-space() = \\"Yes, delete this task\\"]\",\"index\":0}]', 3, 'button', 'button', 'click', '{"value":"Yes, delete this task","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Yes, delete this task","type":"button"}');
  await MK.onClick(pageDetails7.buttonj3SPqIMYYField, 34, 'before', `Yes, delete this task`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 35, page.url(), '[{\"selector\":\"div.flex.flex-col.items-center.justify-center.gap-3.p-10>p.MuiTypography-root.MuiTypography-body1.text-neutral-20.text-lg.font-bold.css-16qymjc\",\"index\":0},{\"selector\":\"div>p\",\"index\":11},{\"selector\":\"P\",\"index\":18},{\"selector\":\"//div[contains(text(),\\"No rows\\")]\",\"index\":0}]', 3, 'p', '', 'mouseover', '{"value":"You have no tasks in your inbox","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"You have no tasks in your inbox","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails1.pnvhxZqSB3Field, 35, 'after', `You have no tasks in your inbox`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarAppe520b5c5_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
