
/*
* Generated by MuukTest
* Test Case ID: TC84298
* Description: Confirm Two-factor Authentication button triggers the Backup Codes page
* Generated: 2026-09-07T02:03:35.456Z
*/
import { expect, devices } from '@playwright/test';
import { faker } from '@faker-js/faker';
const { test } = require("../fixture");
const path = require('path');
const fs = require('fs');
import { 
   dashboardStagingNavgod25yq9dx43d,  dashboardStagingNavgupzppbviuhmp,  dashboardStagingNavgkat21kg28a4,  w3schoolsComafj2me66hboa,  dashboardStagingNavg90djub1wboef,  dashboardStagingNavgoy1kmmmd2m,  dashboardStagingNavgkclsmnhqvhz,  dashboardStagingNavgybvw8equak2q,  
} from './PageDetails';
import Muuk from './Muuk';
import MuukReport from './MuukReport';
const consoleLogs: any = []; 
const logFile = 'browser-dashboardStagingNavgarApp03825b0a.log';
const muukReport = new MuukReport('dashboardStagingNavgarApp03825b0a');
let logIndex = 0;
const snippetLogs: any = [];




test('dashboardStagingNavgarApp03825b0a',  async ({ page, context }) => {
  let pages;
  let numberPages = 1;
  let pageUpdated = false;
  let maxRetries = 0;
  let snippetValue = "";
  let snippetPattern = /snippetLog\(["']([\s\S]*?)["']\)/gs;

  const MK = new Muuk(page, context, 'dashboardStagingNavgarApp03825b0a', muukReport);
  MK.setVideoTracker(0);
	const pageDetails1 = new dashboardStagingNavgod25yq9dx43d();
	const pageDetails2 = new dashboardStagingNavgupzppbviuhmp();
	const pageDetails3 = new dashboardStagingNavgkat21kg28a4();
	const pageDetails4 = new w3schoolsComafj2me66hboa();
	const pageDetails5 = new dashboardStagingNavg90djub1wboef();
	const pageDetails6 = new dashboardStagingNavgoy1kmmmd2m();
	const pageDetails7 = new dashboardStagingNavgkclsmnhqvhz();
	const pageDetails8 = new dashboardStagingNavgybvw8equak2q();
  //globalVariables
  let password = `Angel_drums1`;
  let urlBase = `https://dashboard.staging.navgar.app/`;
  let email = `angel.ramirez@muuklabs.com`;
  let timeStmpIndex = `0`;
  let fileName = `0`;
  let randNum = `0`;
  let isVisible = `0`;
  let locator = `//BUTTON[@type="button"]`;
  let variable1 = `{{var1}}`;
  let rowLocator = `test`;
  let deleteIcon = `test`;
  let scrollContainer = `test`;
  let timeoutMs = `60000`;
  let startTime = `10`;
  let container = `test`;
  let start = `10`;
  let row = `10`;
  let currentScrollTop = `1`;
  let lastScrollTop = `1`;
  let found = `true`;
  let urlStaging = `https://dashboard.staging.navgar.app/users/sign_in`;
  let searchInput = ` `;
  let randName = `Test`;
  let expectedWord = ` `;

  // Monitor for new pages
  context.on('page', async (eventPage) => {
    page = eventPage;
    MK.updatePage(page);
    numberPages++;
    pageUpdated = true;
  });


  await page.goto(urlBase, {timeout: 20000});
  await muukReport.addStepInfo('setValueGV', 1, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  randNum = MK.onSetGV(` random number`, 4);
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('snippet', 2, page.url());
  
  
  
  
  
  
  
   console.log('step:2'); 
  logIndex = 2;
  await page.locator("//a[@href='/users/sign_in']").click();

await page.locator("//input[@id='user_email']").fill(email);

await page.locator("//input[@id='user_password']").fill(password);

await page.locator("//input[@type='submit'][@name='commit']").click();

// Check if login failed
const invalidCredentials = page.locator(
  "//p[normalize-space(text())='Invalid email or password.']"
);

if (await invalidCredentials.isVisible({ timeout: 5000 }).catch(() => false)) {
  // Second login attempt
  await page.locator("//input[@id='user_email']").fill(email);

  await page.locator("//input[@id='user_password']").fill(password);

  await page.locator("//input[@type='submit'][@name='commit']").click();
}

// Validate successful login
await expect(
  page.locator("//span[normalize-space(text())='Applications']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Messages']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Tasks']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Flow Templates']")
).toBeVisible();

await expect(
  page.locator("//span[normalize-space(text())='Entities']")
).toBeVisible();
   await MK.takeScreenshot(2); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 14, page.url(), '[{\"selector\":\"div.inline-block.select-none>span.flex.items-center.text-gray-700.appearance-none\",\"index\":0},{\"selector\":\"div>span\",\"index\":9},{\"selector\":\"SPAN\",\"index\":37},{\"selector\":\"//div[@role=\\"button\\"][@aria-label=\\"Profile Menu\\"]\",\"index\":0}]', 3, 'span', '', 'click', '{"value":"","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"undef","type":"undef"}');
  await MK.onClick(pageDetails2.spandBsGveI6J1Field, 14, 'before', `Profile button`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 15, page.url(), '[{\"selector\":\"div.overflow-hidden.bg-white.border.border-gray-200.rounded.shadow-md>a.no-underline.block.px-6.py-3.text-gray-800.bg-white.hover:bg-primary-50.transition.ease-in-out.duration-200.whitespace-nowrap\",\"index\":0},{\"selector\":\"div>a\",\"index\":6},{\"selector\":\"A\",\"index\":6},{\"selector\":\"//A[normalize-space() = \\"Profile\\"]\",\"index\":1}]', 3, 'a', '', 'click', '{"value":"/users/edit","searchType":"href","text":"Profile"}', '{"id":"undef","name":"undef","text":"Profile","type":"undef"}');
  await MK.onClick(pageDetails3.aAru7e8TVR8Field, 15, 'before', `Profile`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('assertProperty', 16, page.url());
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await MK.onAssertProperty(pageDetails3.h1nbfpLaUqbZField, 16, 'after', 'visible'); 
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 17, page.url(), '[{\"selector\":\"div.bg-white.border.border-gray-200.rounded.text-sm.font-medium>a.block.no-underline.p-3.px-6.bg-blue-600.text-white.hover:text-white\",\"index\":0},{\"selector\":\"div>a\",\"index\":17},{\"selector\":\"A\",\"index\":17},{\"selector\":\"//A[normalize-space() = \\"Password\\"]\",\"index\":1}]', 3, 'a', '', 'click', '{"value":"/104/account/password/edit","searchType":"href","text":"Password"}', '{"id":"undef","name":"undef","text":"Password","type":"undef"}');
  await MK.onClick(pageDetails6.agwu6DohvjzField, 17, 'before', `Password`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 18, page.url(), '[{\"selector\":\"div.lg:p-10.mt-4.p-4.bg-white.rounded-lg.border.border-gray-200>h2.h3\",\"index\":0},{\"selector\":\"div>h2\",\"index\":0},{\"selector\":\"H2\",\"index\":0},{\"selector\":\"//H2[normalize-space() = \\"Two-factor Authentication\\"]\",\"index\":0}]', 3, 'h2', '', 'mouseover', '{"value":"Two-factor Authentication","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Two-factor Authentication","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails6.h2OPt321FaNXField, 18, 'after', `Two-factor Authentication`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 19, page.url(), '[{\"selector\":\"div.lg:p-10.mt-4.p-4.bg-white.rounded-lg.border.border-gray-200>a.btn.btn-tertiary\",\"index\":0},{\"selector\":\"div>a\",\"index\":22},{\"selector\":\"A\",\"index\":22},{\"selector\":\"//A[normalize-space() = \\"Enable two-factor authentication\\"]\",\"index\":0}]', 3, 'a', '', 'click', '{"value":"/104/user/two_factor/backup_codes","searchType":"href","text":"Enable two-factor authentication"}', '{"id":"undef","name":"undef","text":"Enable two-factor authentication","type":"undef"}');
  await MK.onClick(pageDetails6.aebtA06tQg3Field, 19, 'before', `Enable 2FA`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 20, page.url(), '[{\"selector\":\"div.max-w-xl.mx-auto.mt-12.p-8.bg-white.rounded.border.border-gray-200>h3\",\"index\":0},{\"selector\":\"div>h3\",\"index\":0},{\"selector\":\"H3\",\"index\":0},{\"selector\":\"//H3[normalize-space() = \\"Backup Codes\\"]\",\"index\":0}]', 3, 'h3', '', 'mouseover', '{"value":"Backup Codes","searchType":"text","text":"undef"}', '{"id":"undef","name":"undef","text":"Backup Codes","type":"undef"}');
  
  
  
  await MK.onMouseover(pageDetails7.h3OJT3l0cPPoField, 20, 'after', `Backup Codes`, 'none', 60000); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
  await muukReport.addStepInfo('step', 21, page.url(), '[{\"selector\":\"div.flex.justify-between.items-center>a.btn.btn-white\",\"index\":0},{\"selector\":\"div>a\",\"index\":16},{\"selector\":\"A\",\"index\":16},{\"selector\":\"//A[normalize-space() = \\"Cancel\\"]\",\"index\":0}]', 3, 'a', '', 'click', '{"value":"/104/account/password/edit","searchType":"href","text":"Cancel"}', '{"id":"undef","name":"undef","text":"Cancel","type":"undef"}');
  await MK.onClick(pageDetails7.aKwhrJ4t0A6Field, 21, 'before', `Cancel`, 'none', 60000);  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  await muukReport.saveStep(true);
  
  
  
  
  
});



test.afterEach(async ({}, testInfo) => {
  // Save browser logs separately
  const index = testInfo.repeatEachIndex || 0;
  const _keyLog = `dashboardStagingNavgarApp03825b0a_r${index}`;
  const browserLog = `browser-${_keyLog}.log`;
  fs.writeFileSync(browserLog, consoleLogs.join('\n'));
  console.log(`Console logs saved to ${browserLog}`);

  saveSnippetLogs(_keyLog);

  await muukReport.createReportFile(_keyLog);
});


// This function allows user to send logs to the broweser logs.
// This can be called from playwright code snippets.
function browserLog(text: string){
  const timestamp = new Date().toLocaleString();
  consoleLogs.push(timestamp + " " +  text );
}

// This function allows user to send snippet logs.
// This can be called from playwright code snippets.
function snippetLog(text: string){
  snippetLogs.push('Snippet Log ' + ' - ' + logIndex + ' - ' + text);
}

// Function to create snippet logs
function saveSnippetLogs(_keyLog: string) {
  const snippetLog = `snippetLog-${_keyLog}.log`;
  const snippetFilePath = path.join('test/', snippetLog);
  let snippetContent = '';

  snippetLogs.forEach(log => {
    let match = log.match(/Snippet Log\s+-\s+(\d+)\s+-\s+(.*)/);
    if (match) {
      const stepNumber = match[1];
      const message = match[2]; 
      snippetContent += `MuukSnippetStep ${stepNumber}: ${message}\n`;
    }
  });

  // Write all snippet logs into a single file
  fs.writeFileSync(snippetFilePath, snippetContent);
  console.log(`All snippet logs saved to ${snippetFilePath}`);
}
